### ISSUE TITLE
Is there a way to put additional data to RequestContext

### ISSUE THREAD

**Issue by Xcorpio** [akka/akka-http#1717] opened 2017-12-29 03:29 UTC
Here is my situation:

RootRoutes.scala
```scala
  lazy val allRoutes: Route =
    handleExceptions(RoutesExceptionHandler.handler) {
      homeRoutes ~
        handleRejections(RoutesRejectionHandler.handler) {
          authRoutes ~ {
            cookie(Config.extSsoCookie) { token =>
              authorizeAsync(ctx => Authorization.hasPermissions(token.value, ctx)) {
                dbRoutes ~
                  jobRoutes 
              }
            }
          }
        }
    }
```

dbRoutes
```scala
  lazy val dbRoutes =
    pathPrefix("db") {
      ImageRoutes.imageRoutes
    }
```
i want to put additional Authorization data to `RequestContext` in `Authorization.hasPermissions`, so I can extract it in sub inner routes like `ImageRoutes.imageRoutes`. like
```scala
 val imageRoutes =
    pathPrefix("image") {
      customDataExtract(..) { customData => 
       path("list") {
         // do with customData
          ....
       }
     }
```
It is just like `Attribute` in `HttpServletRequest` . 
I read lots of docs and can't find a way to implement it.
Is there a round way to do that?

**Comment by ktoso** [comment] 2017-12-29 11:44
We currently do this by adding headers, you can make a custom header and include anything you want in there. It's not elegant though and we agree.

There's a ticket about implementing just that, attributes: https://github.com/akka/akka-http/issues/1500

Please track that ticket as we may get to solving it in early 2018 I think.
Closing this as duplicate

**Comment by ktoso** [comment] 2017-12-29 11:44
Duplicate of https://github.com/akka/akka-http/issues/1500

**Closed** 2017-12-29 11:44 UTC
