### ISSUE TITLE
Scala DSL serializes "\"a" into ""a", which is illegal.

### ISSUE THREAD

**Issue by rbudzko** [akka/akka-http#600] opened 2016-11-30 10:46 UTC
While use case is rather rare, it might be useful to fix it as most of json parses will fail.

**Comment by jrudolph** [comment] 2016-12-05 10:54
What part of the Scala DSL do you mean?

**Comment by jrudolph** [comment] 2016-12-05 10:54
Can you post an example?

**Comment by rbudzko** [comment] 2016-12-05 17:41
Please, see #590. It is about marshaller used by default in scala DSL, so I've tested in on simple `complete("\"a")`.

**Comment by jrudolph** [comment] 2016-12-05 18:03
The default string marshaller should marshal to a `text/plain` response. 

For this route

```scala
path("blub") { complete("\"a") }
```

that's the output for me:

```
$ curl -v http://localhost:8080/blub 
* Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 8080 (#0)
> GET /blub HTTP/1.1
> User-Agent: curl/7.35.0
> Host: localhost:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server akka-http/10.0.0+14-f21dd7bd+20161205-1625 is not blacklisted
< Server: akka-http/10.0.0+14-f21dd7bd+20161205-1625
< Date: Mon, 05 Dec 2016 18:01:03 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 2
< 
* Connection #0 to host localhost left intact
"a
```

which is as expected.

So, I still seem to be missing what the problem is and how this is related to json?

**Comment by rbudzko** [comment] 2016-12-06 07:57
I'll test again on working example to be sure but won't it behave the same way for string field of a class, so we end up with unescaped quote?

**Comment by rbudzko** [comment] 2016-12-07 10:26
```
val route =
    pathPrefix("a") {
      get {
        complete(Model("\"a"))
      }
    } ~ pathPrefix("b") {
      get {
        complete("\"a")
      }
    }
```

It produces `{"field":"\"a"}` and `"a` depending on the endpoint. I've used wrong wording. Json format seems to handle it correctly. Jackson escapes `"` not only for objects but for root strings as well (ie `mapper.writeValueAsString`).

Thinking about it again - if scala dsl output is a king we should do something about Jackson not about default marshaller of scala routing DSL. Hmm ⁉️

**Comment by jrudolph** [comment] 2017-02-27 10:45
Closing. I think the problem here is that one of the json marshallers applied accidentally.

**Closed by jrudolph** 2017-02-27 10:45 UTC
Labels: bug
