### ISSUE TITLE
Allow accept headers with charset by default

### ISSUE THREAD

**Issue by markusjura** [akka/akka-http#1217] opened 2017-06-20 15:24 UTC
If a client sets an accept header in the HTTP request, Akka HTTP is checking if the HTTP response matches the given accept header. If the response does not match the accept header Akka HTTP by default returns a `406 Not Acceptable` status code.

This logic is perfect. However, Akka HTTP does not allow all formats of an accept header, e.g. If an HTTP endpoint returns `text/plain`, then the following accept header `Accept: text/plain; charset=UTF-8` results in a `406 Not Acceptable` status code. By default, Akka HTTP only allows accept headers that contain no charset parameter.

This can be manually changed by adding an additional parser setting to the Akka HTTP server during startup:

```
val `text/plain(UTF-8)` = MediaType.customWithFixedCharset("text", "plain", `UTF-8`)
val parserSettings = ParserSettings(context.system).withCustomMediaTypes(`text/plain(UTF-8)`)
val serverSettings = ServerSettings(context.system).withParserSettings(parserSettings)

Http(context.system).bindAndHandle(route, ip, port, settings = serverSettings)
```

This manual setting is tedious. It would be nice if Akka HTTP could, by default, support accept headers that contain a `charset` parameter. This format is not forbidden by [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt) and the default in Play if the [ContentTypes](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/StandardValues.scala#L12-L76) helper objects are used. Also, this stackoverflow answer states that it is a valid format: https://stackoverflow.com/a/7367532/1375326

**How to reproduce**

Start Akka HTTP server (version 10.0.7):

```
sbt new https://github.com/akka/akka-http-scala-seed.g8
cd my-akka-http-project
sbt "runMain com.example.WebServerHttpApp"
```

Send HTTP request with accept header that contains charset parameter:

```
curl -v -H "Accept: text/plain; charset=UTF-8" http://localhost:8080
* Rebuilt URL to: http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: text/plain; charset=UTF-8
>
< HTTP/1.1 406 Not Acceptable
< Server: akka-http/10.0.7
< Date: Tue, 20 Jun 2017 15:04:43 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 70
<
Resource representation is only available with these types:
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
text/plain
```

Sending an accept header without a charset parameter works:

```
curl -v -H "Accept: text/plain" http://localhost:8080
* Rebuilt URL to: http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: text/plain
>
< HTTP/1.1 200 OK
< Server: akka-http/10.0.7
< Date: Tue, 20 Jun 2017 15:24:25 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 21
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
Server up and running
```

**Comment by huntc** [comment] 2017-06-21 06:47
More info for you... this used to work prior to upgrading to 10.0.7 i.e. we had no problem with 10.0.3.

**Comment by raboof** [comment] 2017-06-21 07:04
I wonder if this might have to do with https://github.com/akka/akka-http/pull/964 (released in 10.0.6).

**Comment by raboof** [comment] 2017-06-21 07:10
Possible duplicate of #1139 - could you check if the problem persists on version 10.0.8?

**Comment by ktoso** [comment] 2017-06-21 19:24
Yeap, as I mentioned on chat while we were looking at it with Markus :)

And I confirm 10.0.8 resolves this issue:

```
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-testkit_2.12/10.0.8/akka-http-testkit_2.12-10.0.8.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-http-testkit_2.12;10.0.8!akka-http-testkit_2.12.jar (9053ms)
[info] downloading https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.1/scalatest_2.12-3.0.1.jar ...
[info] 	[SUCCESSFUL ] org.scalatest#scalatest_2.12;3.0.1!scalatest_2.12.jar(bundle) (35070ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-testkit_2.12/2.4.19/akka-stream-testkit_2.12-2.4.19.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-stream-testkit_2.12;2.4.19!akka-stream-testkit_2.12.jar (4741ms)
[info] downloading https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.4.19/akka-testkit_2.12-2.4.19.jar ...
[info] 	[SUCCESSFUL ] com.typesafe.akka#akka-testkit_2.12;2.4.19!akka-testkit_2.12.jar (2204ms)
[info] downloading https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.1/scalactic_2.12-3.0.1.jar ...
[info] 	[SUCCESSFUL ] org.scalactic#scalactic_2.12;3.0.1!scalactic_2.12.jar(bundle) (8103ms)
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn] 	* com.typesafe.akka:akka-stream_2.12:2.4.19 -> 2.5.2
[warn] Run 'evicted' to see detailed eviction warnings
[info] Compiling 4 Scala sources to /private/tmp/my-akka-http-project/target/scala-2.12/classes...
[warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

Multiple main classes detected, select one to run:

 [1] com.example.WebServer
 [2] com.example.WebServerHttpApp

Enter number: 2

[info] Running com.example.WebServerHttpApp
Press RETURN to stop...
[INFO] [06/21/2017 20:22:30.714] [WebServerHttpApp-akka.actor.default-dispatcher-4] [akka.actor.ActorSystemImpl(WebServerHttpApp)] Server online at http://localhost:8080/
```

```
$ curl -v -H "Accept: text/plain; charset=UTF-8" http://localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: text/plain; charset=UTF-8
>
< HTTP/1.1 200 OK
< Server: akka-http/10.0.8
< Date: Wed, 21 Jun 2017 19:22:59 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 21
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

**Comment by huntc** [comment] 2017-06-21 23:26
Thanks for the follow-up. Shall we close this then?

**Comment by ktoso** [comment] 2017-06-21 23:27
Check on your side please, but yes. It seems my close click did not get through on hotel wifi.

**Closed by ktoso** 2017-06-21 23:27 UTC
Labels: 1 - triaged, t:core

**Comment by markusjura** [comment] 2017-06-23 09:03
Tested it with Akka 10.0.8 again. This version is fixing the issue.
