### ISSUE TITLE
Multipart-Form-Data in akka-http, missing quotes in Content-Disposition field

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#386] opened 2016-10-12 08:11 UTC
<a href="https://github.com/KrzyMucha"><img src="https://avatars.githubusercontent.com/u/14311593?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KrzyMucha](https://github.com/KrzyMucha)**
_Wednesday Oct 12, 2016 at 08:05 GMT_
_Originally opened as https://github.com/akka/akka/issues/21656_
---

When we use akka-http for http request with following code:

```
Multipart
            .FormData(Multipart.FormData.BodyPart("file",
                HttpEntity.Strict(MediaTypes.`image/jpeg`, ByteString("test")), Map("filename" -> "somefile.jpeg"))).toEntity()
```

Then Http request is as follows

```
User-Agent: [akka-http/2.4.8]
Transfer-Encoding: [chunked]
Host: [localhost:8089]
Content-Type: [multipart/form-data; boundary=xWtacaNwjOWLKFExaR8fOv6Q; charset=UTF-8]

--xWtacaNwjOWLKFExaR8fOv6Q
Content-Type: image/jpeg
Content-Disposition: form-data; filename=somefile.jpeg; name=file

test
--xWtacaNwjOWLKFExaR8fOv6Q--
```

Parameters **filename** and **file** are without quotation marks. However following HTTP specification this params should be quoted. As result some servers (ex. "django" app) are not able to see attached files.

**Comment by ktoso** [comment] 2016-10-12 08:11
<a href="https://github.com/ktoso"><img src="https://avatars.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Wednesday Oct 12, 2016 at 08:10 GMT_

----

Please open the issue on github.com/akka/akka-http instead, sinve the project has moved.

AFAIR there is no need to quote these according to the https://tools.ietf.org/html/rfc6266 spec

```
     filename-parm       = "filename" "=" value
                         | "filename*" "=" ext-value

       value                   = token | quoted-string
```

notice the `|` there.

Let's please continue in the right repo.

**Comment by ktoso** [comment] 2016-10-12 08:28
<a href="https://github.com/KrzyMucha"><img src="https://avatars.githubusercontent.com/u/14311593?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KrzyMucha](https://github.com/KrzyMucha)**
_Wednesday Oct 12, 2016 at 08:05 GMT_
_Originally opened as https://github.com/akka/akka-http/issues/387_

----

Information about requirement I found here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html, paragraph **19.5.1 Content-Disposition**
```
filename-parm = "filename" "=" quoted-string
disp-extension-parm = token "=" ( token | quoted-string )
```

**Comment by ktoso** [comment] 2016-10-12 08:32
Seems you're right, according to https://www.w3.org/Protocols/rfc2616/rfc2616-sec19.html#sec19.5.1 @KrzyMucha.
Would you be able to contribute a fix for this? It's relatively simple, I'm happy to help if you need pointers to get started.

**Comment by KrzyMucha** [comment] 2016-10-12 08:33
I can do fix

**Comment by jrudolph** [comment] 2016-10-12 08:55
I'm pretty sure there should be a related ticket lurking somewhere.

**Comment by jrudolph** [comment] 2016-10-12 09:05
This seems to be a duplicate of this one: https://github.com/akka/akka/issues/18788. There we concluded that RFC 2616 is not the most recent one and RFC 6266 also allows filename parameter values without quotes. Still, if this was only recently changed (2011) it might make sense to add extra quotes even if they are not strictly required by the latest spec.

**Comment by jrudolph** [comment] 2016-10-12 09:08
[Appendix A of RFC 6266](https://tools.ietf.org/html/rfc6266#appendix-A) says:

```
   o  RFC 2616 only allows "quoted-string" for the filename parameter.
      This would be an exceptional parameter syntax, and also doesn't
      reflect actual use.
```

**Comment by jrudolph** [comment] 2016-10-12 09:13
Also looking at this [stackoverflow answer](http://stackoverflow.com/a/6745788/7647) which seems to imply that browsers also seem to be very confused about what they generate. (Though I guess it would need to be re-checked with recent browsers.)

**Comment by KrzyMucha** [comment] 2016-10-12 09:21
What I found is that other clients (I checked curl and dispatch.io) put values of  parameters "name" and "filename" in quoted marks, like this:
```
Content-Disposition: form-data; name="file"; filename="6117776844.jpeg"
```
Should the fix enforce similar behaviour for akka-http?

**Comment by ktoso** [comment] 2016-10-12 10:16
Seems that would be perhaps safer than now.
As the linked discussion said it "Browser compatibility is a mess." :-/

**Comment by KrzyMucha** [comment] 2016-11-03 09:04
@ktoso I created pull request for this, however I made some mess before (first time on github doing this). Anyway doing my best :)

**Comment by ktoso** [comment] 2016-11-03 10:24
Cool, thanks a lot Krzysztof :-)

**Comment by jrudolph** [comment] 2016-11-03 13:41
Fixed by https://github.com/akka/akka-http/pull/471.

**Closed by jrudolph** 2016-11-03 13:41 UTC
Labels: 3 - in progress, discuss, t:core
