### ISSUE TITLE
Broken documentation links when trying to access the latest version

### ISSUE THREAD

**Issue by WadeWaldron** [akka/akka-http#1005] opened 2017-03-30 16:56 UTC
I attempted to visit this page:

http://doc.akka.io/docs/akka/2.4.9/scala/http/client-side/request-level.html

It gives me the warning that this is not the latest version and has a link to the latest version which is:

http://doc.akka.io/docs/akka/2.4.17/scala/http/client-side/request-level.html

This link is broken. I get a 404 when I follow it.

**Comment by jlprat** [comment] 2017-03-30 17:14
Documentation for Akka HTTP is now independent from the Akka one. The new location is http://doc.akka.io/docs/akka-http/current/

**Comment by WadeWaldron** [comment] 2017-03-30 17:22
Seems like these broken links are a problem. Google takes me to the old version, and the redirects to the new version aren't helpful. Is closing this issue the right approach here?

I realize the documentation has moved. But if people can't find the new documentation because the Google is still directing them to old versions, and the redirects don't work properly, then how are people going to find what they are looking for?

**Comment by johanandren** [comment] 2017-03-30 17:24
I think we need to fix that old-docs-javascript somehow to deal with the akka-http-move.

**Comment by jlprat** [comment] 2017-03-30 17:26
Wouldn't that be part of Akka then?

**Comment by jlprat** [comment] 2017-03-30 17:36
Sorry for the quick finger closing.

**Comment by johanandren** [comment] 2017-03-30 17:46
I'm not quite sure where that script lives, yes, probably in the old akka docs, so we'd have to go back and update or something. I think @ktoso knows best how it works.

**Comment by ktoso** [comment] 2017-03-30 19:54
Correct, this should be in akka/akka and yes we will fix it during the new-docs work.
It is not possible to automagically make all things work, we will have to spend some time on prepping scripts and sed-ing entire docs codebases.

**Comment by ktoso** [comment] 2017-03-30 19:57
Closing and opening in the in Akka as that's where where effort really starts.

**Comment by ktoso** [comment] 2017-03-30 19:58
https://github.com/akka/akka/issues/22659

**Closed** 2017-03-30 19:58 UTC
Labels: 1 - triaged, bug, t:docs

**Comment by jonas** [comment] 2017-03-30 20:44
@ktoso I suggest we also close this one as duplicate of the akka/akka one: #809

**Comment by ktoso** [comment] 2017-03-30 20:45
Yeah, let's
