### ISSUE TITLE
Pool is getting stuck after hours / days finally hitting `max-open-requests`

### ISSUE THREAD

**Issue by derekwyatt** [akka/akka-http#637] opened 2016-12-09 18:57 UTC
I've build a reverse http proxy (perhaps you guys are familiar with my app at this point) and we're getting severe problems with the client portion at random times.

We get between 2000 and 4000 requests per minute and relay those to the proxied server.  Things run fine for days, sometimes, other times about a day.  And then at some point, we see that the requests we received in the server portion do not get sent out of the client portion.  I have logs that show me when a request is received on the server side, and when we receive the response from the client side.

Given these entries I can match up requests with responses and know when we have unfulfilled requests and there's a point in time when we stop sending requests and the queue just fills up.  The server to which we're proxying sees a drop in the inbound network rate so it's not getting the requests, but we're certainly queueing them.

This queue builds over multiple minutes.  I'm not sure why the default request timeout (20s) doesn't toss them out.

I've been kicked out of production for a third time, unfortunately and I need to get back in, but I'm lost on what's going on here.

Can anyone provide some insight?

I monitor the number of 'sockets' with `netstat -na | grep 10.212.3.141 | wc -l` that gets logged every second.  This hovers around 250 but can spike to the thousands in "bad times"

**Comment by jrudolph** [comment] 2016-12-12 09:55
Thanks for the report, @derekwyatt.

> Given these entries I can match up requests with responses and know when we have unfulfilled requests and there's a point in time when we stop sending requests and the queue just fills up.

Are there also ongoing requests at the server at that time? Can you rule out that it's not some responses that are hanging?

> This queue builds over multiple minutes. I'm not sure why the default request timeout (20s) doesn't toss them out.

There's only a request timeout on the server, not on the client, so that requests aren't pruned from any queue on the client side.

**Comment by derekwyatt** [comment] 2016-12-13 14:39
> Are there also ongoing requests at the server at that time? Can you rule out that it's not some responses that are hanging?

There are some responses that take a long time, but AFAICT this isn't the culprit.  Monitoring the low level network traffic to the server shows that it simply stops receiving requests.  The queue builds up over a multi-minute period (I have set it to 16384, afterall) and during that time, the network traffic to the server is extremely low.

As well, the number of unfulfilled requests is far lower than the number of available connections.

> There's only a request timeout on the server, not on the client, so that requests aren't pruned from any queue on the client side.

Right.  Damn.  But I don't think the requests are even getting to the server anyway, so providing that timeout wouldn't really very helpful anyway.

**Comment by jrudolph** [comment] 2017-02-27 16:46
Closing this one. It is probably not a bug but a problem with either the request rate or some requests getting stuck. We recently merged [a new documentation chapter](http://doc.akka.io/docs/akka-http/current/java/http/client-side/pool-overflow.html) about why you might hit `max-open-requests`.

Apart from that we are considering adding more timeouts that would enable to prune requests from the queue.

**Comment by derekwyatt** [comment] 2017-02-27 17:11
Perhaps, however... I don't believe I hit any of the issues mentioned in
that doc. I had set the max requests to 28,000 and still hit it at odd
times, while experiencing request rates of ~100 per second; not high load.
It's possible that the response entity was not being drained but if that
was the case then there might be something wrong with the akka server. My
client code was making a call downstream and then passing the response to
the akka server code to be sent upstream. i.e. I was merely plumbing the
two together. So if the entity wasn't being  handled properly then I can't
imagine how I would be able to know that or have the influence to correct
it.

If nothing else, when the error is hit there should be an option to dump
all of the outstanding requests so that we can see what's going on. I found
it very difficult to do this because everything was bound up in streams
that didn't have the appropriate request context available.

I've changed to nginx here instead of using akka, so it's no longer a
problem for me, but that doc doesn't give me any "aha" moments. I already
did everything it states.

It seems to me that akka http has never had the breadth of testing that I
was putting it through - a highly generalized http proxy, intended to
handle "any" request and response - so there looks to be a great
opportunity for testing here. Build a simple reverse proxy and put it in
front of a non-akka, non-trivial website app that gets a moderate amount of
traffic and see what happens.

And for full disclosure, I tried no less than seven other Java based http
proxies and frameworks and none of them worked fully. If it weren't for
nginx I would be dead in the water.

Based on my history with akka http, I believe you should find a lot of
interesting behaviour in short order if you build a reverse proxy with it
and deploy it to at least one non-trivial spot. I tried to get it working
for three months without success against a pretty standard ASP server.
After switching to nginx a month ago, dropping my Scala code unaltered into
it as a rewrite module, I have had zero errors and the system load is down
by an order of magnitude.

You guys know more than I do about your toolkit, without question, but I
would urge you to push further into verifying the validity of this highly
generalized use case.

**Comment by jrudolph** [comment] 2017-02-28 12:02
Thanks for the added info, @derekwyatt. Maybe I was a bit fast with closing this one. I agree we should have better diagnostics to find out what's the issue here. Also adding some long-time testing definitely makes sense.

We just got a similar report in #908.

**Comment by jrudolph** [comment] 2017-07-26 13:26
I'm going to close this issue again, not because I think that all issues are fixed but moreover because it doesn't include enough information to debug a particular issue. We have a few ideas of hardening the pool further which will be documented in other tickets.

**Closed by jrudolph** 2017-07-26 13:26 UTC
Labels: 1 - triaged, bug
