### ISSUE TITLE
Response entity failures kill client pool

### ISSUE THREAD

**Issue by jrudolph** [akka/akka-http#416] opened 2016-10-20 18:06 UTC
It was really hard to find out how problems with a response are fed back into the pool so that at the end the complete pool is shutdown.

I changed GraphStageLogic.failStage to wrap all exceptions with more information to get at the trace of how the error propagated like this:

``` scala
  final def failStage(ex: Throwable): Unit = {
    def stageName: String = try {
      val outerField = getClass.getDeclaredField("$outer")
      outerField.setAccessible(true)
      outerField.get(this) match {
        case MapAsyncUnordered(_, func) ⇒ s"MapAsyncUnordered(${func.getClass})"
        case Map(func)                  ⇒ s"Map(${func.getClass})"
        case Collect(func)              ⇒ s"Collect(${func.getClass})"
        case _                          ⇒ getClass.toString
      }
    } catch {
      case x ⇒ getClass.toString
    }

    val newEx = new RuntimeException(s"Failing stage in $stageName", ex).fillInStackTrace()
    // use newEx instead of ex
  }
```

You then get a stack trace like this (stripped the actual code lines) if while receiving a response entity the connection breaks:

```
java.lang.RuntimeException: Failing stage in class akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$3
Caused by: java.lang.RuntimeException: Failing stage in class akka.stream.impl.fusing.Log$$anon$23
Caused by: java.lang.RuntimeException: Failing stage in class akka.http.impl.engine.client.PoolConductor$Route$$anon$4
Caused by: java.lang.RuntimeException: Failing stage in class akka.http.impl.engine.client.PoolConductor$SlotSelector$$anon$1
Caused by: java.lang.RuntimeException: Failing stage in MapAsyncUnordered(class akka.http.impl.engine.client.PoolConductor$$anonfun$apply$2$$anonfun$4)
Caused by: java.lang.RuntimeException: Failing stage in class akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1
Caused by: java.lang.RuntimeException: Failing stage in Collect(class akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$defaultEntity$1$$anonfun$1)
Caused by: java.lang.RuntimeException: Failing stage in class akka.stream.impl.fusing.SubSource$$anon$4
Caused by: java.lang.RuntimeException: Failing stage in class akka.stream.impl.fusing.StatefulMapConcat$$anon$25
Caused by: java.lang.RuntimeException: Failing stage in class akka.http.impl.engine.client.OutgoingConnectionBlueprint$ResponseParsingMerge$$anon$6
Caused by: java.lang.RuntimeException: Failing stage in Collect(class akka.http.impl.engine.client.OutgoingConnectionBlueprint$$anonfun$6$$anonfun$5)
Caused by: java.lang.RuntimeException: Failing stage in class akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7
.RuntimeException: Failing stage in class akka.stream.impl.fusing.GraphStages$Detacher$$anon$2
Caused by: java.lang.RuntimeException: Failing stage in class 
Caused by: akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
```

The interesting connection is

```
Caused by: java.lang.RuntimeException: Failing stage in MapAsyncUnordered(class akka.http.impl.engine.client.PoolConductor$$anonfun$apply$2$$anonfun$4)
Caused by: java.lang.RuntimeException: Failing stage in class akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1
```

where an entity error suddenly gets reported as an error in the RawSlotEvent channel. The `mapAsyncUnordered` is the one from this line: https://github.com/akka/akka-http/blob/master/akka-http-core/src/main/scala/akka/http/impl/engine/client/PoolConductor.scala#L78-L78

Turns out that PoolSlot does

``` scala
val (entity, whenCompleted) = HttpEntity.captureTermination(response.entity)
          //...
          push(eventsOut, SlotEvent.RequestCompletedFuture(whenCompleted.map(_ ⇒ SlotEvent.RequestCompleted(slotIx))))
```

to capture termination of a response entity to find out that a connection is free again in the Future `whenCompleted`.

This is then handled in the linked-above `mapAsyncUnordered`:

``` scala
      val flatten = Flow[RawSlotEvent].mapAsyncUnordered(slotSettings.maxSlots) {
        case x: SlotEvent.Disconnected                ⇒ FastFuture.successful(x)
        case SlotEvent.RequestCompletedFuture(future) ⇒ future
        case x: SlotEvent.ConnectedEagerly            ⇒ FastFuture.successful(x)
        case x                                        ⇒ throw new IllegalStateException("Unexpected " + x)
      }
```

So, the `mapAsyncUnordered` will escalate an error in the entity stream to an error on the pool level which will subsequently kill the complete pool.

**Comment by gosubpl** [comment] 2016-10-26 20:00
Looking into this. Hope this will not prove too difficult...

**Comment by gosubpl** [comment] 2016-10-27 12:00
@jrudolph perhaps I am missing something, but is there a reproducer for this or shall I try to invent my own?

**Comment by jrudolph** [comment] 2016-10-27 13:27
Yes, writing the test (probably in ConnectionPoolSpec) is probably most of the work. I have some half-finished test. I'll try to wrap it up and post it as a branch somewhere. Might make sense to delay working on it until then.

**Comment by gosubpl** [comment] 2016-10-27 21:38
Ok @jrudolph , so I am waiting now for your test branch. I think that you could consider posting it even in a very rough state, I will try to iron out all the problems. It would be great if I had something to work on during the weekend...

**Comment by jrudolph** [comment] 2016-10-28 07:46
@gosubpl I posted it here: https://github.com/akka/akka-http/compare/jr/w/416-fix-connection-pool-crash?expand=1. The first commit adds a lot more debug output (including a copy of an akka-stream source file which will add stacktraces causes when a stage propagates an exception). The second commit adds the test. The line which makes it fail is

```scala
errorOnConnection1.failure(new RuntimeException)
```

which will kill the pool.

**Comment by gosubpl** [comment] 2016-10-28 08:30
@jrudolph thanks, will take it from there

**Comment by gosubpl** [comment] 2016-10-30 12:22
@jrudolph please let me know if I am going in the right direction. The obvious fix (which makes the tests pass) would be:
```
          val completedF : Future[PoolSlot.SlotEvent.RequestCompleted] =
            whenCompleted.map(_ ⇒ SlotEvent.RequestCompleted(slotIx))
              .recoverWith{case _ => FastFuture.successful(SlotEvent.RequestCompleted(slotIx))}
          push(eventsOut, SlotEvent.RequestCompletedFuture(completedF))
```
So this would mean that the request completed, no matter whether it completed successfully or not. For sure some logging should be added here to let _ipsos custodes_ see what has happened.
Wha do you think?

**Comment by leachbj** [comment] 2016-10-31 01:54
A failure on the entity should still close the slot but the slot closing is signalled from the `PoolSlot` to the `PoolConductor` so I think this needs to call see `PoolSlot.disconnect`, that will fail any requests that started after the one that we're currently failing and send the `SlotEvent.Disconnected` event back.  I'm not sure what the recoverWith should map the result to though, it needs an ignore event since the disconnect would use the disconnected to update that slot.

**Comment by gosubpl** [comment] 2016-10-31 21:50
@leachbj @jrudolph  I think that the slot actually gets disconnected. `disconnect` from `SlotProcessor.GraphStateLogic` gets called and we get `Disconnected` evend, as evidenced below.
```
0 (1) connection cancelled slot
0 (6) connection errored with The connection closed with error: Connection reset by peer
0 connection failed with The connection closed with error: Connection reset by peer
0 disconnecting... isConnected: true ex.isDefined: true, inflights: 0
[DEBUG] [10/31/2016 22:32:50.095] [ConnectionPoolSpec-akka.actor.default-dispatcher-2] [akka.actor.LocalActorRefProvider(akka://ConnectionPoolSpec)] resolve of path sequence [/user/StreamSupervisor-0/$$b#-1002416078] failed
0 retries: List() failures: List()
[DEBUG] [10/31/2016 22:32:50.120] [ConnectionPoolSpec-akka.actor.default-dispatcher-4] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [slotEvents 0] Element: Disconnected(0,0)
HttpResponse(200 OK,List(Server: akka-http/2.4.11, Date: Mon, 31 Oct 2016 21:32:49 GMT, Connection: close),HttpEntity.CloseDelimited(application/octet-stream),HttpProtocol(HTTP/1.1))
Now respond to request 2
```
see the `0 disconnecting... isConnected: true ex.isDefined: true, inflights: 0` and later `Disconnected(0,0)` above.

Even the failure of the connection is registered (with the extended custom logging, though): `connection failed with The connection closed with error: Connection reset by peer`

Both the disconnect and log happen due to `PoolSlot.onUpstreamFailure` being called.

So the `Request` gets completed but the slot gets `Disconnected`.

The one thing that troubles me is that we still get `HttpResponse(200 OK ... )` despite obviously server failing.

Am I right in thinking that the slot is properly closed due to the `Disconnect` above? Can we live with 200 OK being generated instead of 500 Internal Server Error?
WDYT?

**Comment by jrudolph** [comment] 2016-11-01 10:57
So, in this case we are seeing two errors, one on the connection that is signaled to `PoolSlot.onUpstreamFailure`, the other on the entity stream. I think we must make sure that only one of these signals reaches the PoolConductor. Otherwise, we'll risk a race condition and an exception in the state machine in the PoolConductor.

I'd suggest, that we ignore the error in the entity stream, instead, and rely on the same error also being reported on the connection. WDYT?

**Comment by leachbj** [comment] 2016-11-02 02:37
That makes sense, `PoolSlot` should deal with the failing connection by closing the slot and the entity stream error should be visible to the consumer of that stream.
@gosubpl that's also how we justify the HTTP 200, since the response header was successful from the server so we correctly report that in the HttpResponse.  The body is a stream so any issues with that are just encoded with the standard stream encodings.
That change I just pushed is basically the same as @gosubpl's but won't generate a `RequestCompleted` event when the stream errors.

**Comment by gosubpl** [comment] 2016-11-02 09:38
@leachbj my immediate thought after reading the comment above by @jrudolph was to implement this in the way you have done in your commit.

However, before that, I did a little debugging, and the outcome of it is, that though the race between the two messages is real, actually both of them are needed.
I have added some poor's man debugging (just pushed) and the workflow looks like that:
```
DEBUG] [11/01/2016 22:47:35.889] [ConnectionPoolSpec-akka.actor.default-dispatcher-8] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-0)] [test] Element: ByteString(97, 98, 99)
inflight in onPush before pop: [RequestContext(HttpRequest(HttpMethod(GET),/a,List(Host: localhost:35901),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1)),List(scala.concurrent.impl.CallbackRunnable@4a85e6a),0)]
inflight in onPush: []
[DEBUG] [11/01/2016 22:47:35.922] [ConnectionPoolSpec-akka.actor.default-dispatcher-5] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [responseOut] Element: ResponseContext(RequestContext(HttpRequest(HttpMethod(GET),/a,List(Host: localhost:35901),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1)),List(scala.concurrent.impl.CallbackRunnable@4a85e6a),0),Success(HttpResponse(200 OK,List(Server: akka-http/2.4.11, Date: Tue, 01 Nov 2016 21:47:35 GMT, Connection: close),HttpEntity.CloseDelimited(application/octet-stream),HttpProtocol(HTTP/1.1))))
[DEBUG] [11/01/2016 22:47:35.925] [ConnectionPoolSpec-akka.actor.default-dispatcher-5] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [slotEvents 0] Element: RequestCompletedFuture(List())
[DEBUG] [11/01/2016 22:47:35.961] [ConnectionPoolSpec-akka.actor.default-dispatcher-8] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [requestIn] Element: RequestContext(HttpRequest(HttpMethod(GET),/b,List(Host: localhost:35901),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1)),List(scala.concurrent.impl.CallbackRunnable@5e482b44),0)
[DEBUG] [11/01/2016 22:47:35.961] [ConnectionPoolSpec-akka.actor.default-dispatcher-8] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [slotCommandIn 1] Element: DispatchCommand(RequestContext(HttpRequest(HttpMethod(GET),/b,List(Host: localhost:35901),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1)),List(scala.concurrent.impl.CallbackRunnable@5e482b44),0))
[DEBUG] [11/01/2016 22:47:35.975] [ConnectionPoolSpec-akka.actor.default-dispatcher-5] [akka://ConnectionPoolSpec/system/IO-TCP/selectors/$a/3] Resolving localhost before connecting
[DEBUG] [11/01/2016 22:47:35.976] [ConnectionPoolSpec-akka.actor.default-dispatcher-5] [akka://ConnectionPoolSpec/system/IO-TCP/selectors/$a/3] Attempting connection to [localhost/127.0.0.1:35901]
[DEBUG] [11/01/2016 22:47:35.978] [ConnectionPoolSpec-akka.actor.default-dispatcher-10] [akka://ConnectionPoolSpec/system/IO-TCP/selectors/$a/0] New connection accepted
[DEBUG] [11/01/2016 22:47:35.979] [ConnectionPoolSpec-akka.actor.default-dispatcher-4] [akka://ConnectionPoolSpec/system/IO-TCP/selectors/$a/3] Connection established to [localhost:35901]
/b
Waiting for error to trigger connection pool failure
[... lots of error messages ...]
0 (1) connection cancelled slot
akka.stream.StreamTcpException: The connection closed with error: Connection reset by peer
0 (6) connection errored with The connection closed with error: Connection reset by peer
0 connection failed with The connection closed with error: Connection reset by peer
0 disconnecting... isConnected: true ex.isDefined: true, inflights: 0
0 retries: List() failures: List()
[]
Received Disconnect... failed: 0 on Loaded(1)...
... transitioning to Loaded(1)
[DEBUG] [11/01/2016 22:47:36.146] [ConnectionPoolSpec-akka.actor.default-dispatcher-2] [akka.stream.Log(akka://ConnectionPoolSpec/user/StreamSupervisor-2)] [slotEvents 0] Element: Disconnected(0,0)
Received Request Completed... slotState: Loaded(1) transitioning to...
... Idle
Now respond to request 2
```
So the actual situation is like that:
Response goes to preparation, request gets removed from `inflights` because it goes into processing -> Future that should generate the body of response fails -> Disconnected is generated with a number of failures 0 as the response has already been prepared and and inflight removed -> `Disconnected` transitions the `PoolSlot` state machine from `Loaded(1)` to ... `Loaded(1)` as the number of failures is 0 ->  `RequestCompleted` (generated in my code) transitions `Loaded(1)` to `Idle`.

Were the `RequestCompleted` message missing, the slot would have remained in `Loaded(1)` state.

In the case of inverted ordering of messages (which can potentially happen in some situations, as we don't control the timing, but is unlikely due to real sequence of events) we would get following transition:
`RequestCompleted` would move us from `Loaded(1)` to `Idle` and subsequent `Disconnected` would transition us further to `Unconnected`. This is the only difference from the previous situation.

I don't yet fully understand the subtle difference between `Idle` and `Unconnected`. However, I think that adapting your approach would require accommodating for unloading the slot (e.g. by not filtering out the message but processing it in the state machine). Maybe I am missing something...

I have already spent some considerable time on this as my impression after the Wednesday akka-http community call ( https://github.com/akka/akka-meta/issues/34 ) was that this is urgently needed, and would be very happy to be able to complete with a PR :)

**Comment by jrudolph** [comment] 2016-11-02 10:08
Ok, I see. Thanks for checking what the state machine actually does. So, I think the difference between those two cases is relevant for the scheduling decision, `Idle` means a persistent connection is still open but nothing is running on it, while `Unconnected` means just that. The current `PoolConductor` will more likely schedule something on an `Idle` connection than on an `Unconnected` one.

So, it seems with the more likely state changes lead to the `Idle` state which is technically wrong. It might be hard to fix that properly so as long as we document that something needs to be improved there I'd be fine with accepting the simple fix.

Thanks for persevering, @gosubpl.

**Comment by leachbj** [comment] 2016-11-02 22:58
So the possible ordering here is;
Restating your summary above @gosubpl  - if we map the response failures to `SlotEvent.RequestCompleted(slot)` we get;

1. Fail before the response headers (onUpstreamFailure);
    `SlotEvent.Disconnected(slot, 1)`; transitions from `Loaded(1)` => `Unconnected`
2. Fail after the response headers (Future failed and then onUpstreamFailure);
    `SlotEvent.RequestCompleted(slot)`; transitions from `Loaded(1)` => `Idle`
    `SlotEvent.Disconnected(slot, 0)`; transitions from `Idle` => `Unconnected`
3. Fail after the response headers (onUpstreamFailure and then Future failed);
    `SlotEvent.Disconnected(slot, 0)`; transitions from `Loaded(1)` => `Loaded(1)`
    `SlotEvent.RequestCompleted(slot)`; transitions from `Loaded(1)` => `Idle`

This last would mean that a subsequent request would be routed to a slot that appears to be `Idle` but is actually `Unconnected`.  Like @jrudolph says this slot would be preferred over an `Unconnected` one (but thats no real concern) but also over a slot that is actually connected and `Idle` which isn't ideal but wouldn't break.

I'm not sure if case 2 presents a chance for a request to sneak through to the slot before the `onUpstreamFailure` gets processed.  If that happened though the 2nd event would be `Disconnected(slot, 1)` so I think thats fine.

In case 3 if pipelining was enabled and a request was processed before the 2nd event then we should see a `Disconnected(slot, 1)` before or after the pending `RequestCompleted(slot)` which should leave us in `Unconnected` regardless of delivery order.

So +1 on @gosubpl's change.

**Comment by jrudolph** [comment] 2016-11-07 12:25
Thanks, @leachbj, for investigating all the options.

**Closed** 2016-11-07 13:59 UTC
Labels: 3 - in progress, bug, t:client, t:core
