### ISSUE TITLE
Expose asJava/asScala for Model objects

### ISSUE THREAD

**Issue by jasongilanfarr** [akka/akka-http#1078] opened 2017-05-02 22:30 UTC
I'm working on following a very similar pattern to Akka HTTP in regards to having a java and scala api. In doing so, I'm actually finding that its very difficult to convert between the scala and javadsl. For example, having a small extension that adds redirect support to `Http` and `HttpExt` using the right types, yet only having one implementation. 

Basically, the core issue is that `akka.http.impl.util.JavaMapping` is package-private (and a lot of its tooling is _also_ private). I understand the need to make internal APIs, but having `{to,as}{Scala,Java}` is actually _very_ useful for application and library developers wishing to build on akka http.

**Comment by jonas** [comment] 2017-05-03 01:12
This looks like a duplicate of #661 so I will go ahead and close this one. Feel free to ❤️ , 👍 and comment on that ticket with any additional insights. Making the API public is still being discussed, however, we now have a [standardized way](http://doc.akka.io/api/akka/2.5/akka/annotation/ApiMayChange.html) to make new APIs available that are not set in stone. Contributions such as a PR would be greatly appreciated.

**Closed by jonas** 2017-05-03 01:12 UTC
