### ISSUE TITLE
Websocket client closed immediately

### ISSUE THREAD

**Issue by epot** [akka/akka-http#1040] opened 2017-04-19 13:20 UTC
I am trying to open a websocket to a local server I have with the exact same code as here (http://doc.akka.io/docs/akka-http/10.0.5/scala/http/client-side/websocket-support.html#client-side-websocket-support - section webSocketClientFlow), just replacing the url with a local url starting with wss as my server is configured as a HTTPS server. 
If I look at the logs I just see:

    2017-04-19 15:14:10,923 [debug] - akka.stream.impl.io.InputStreamPublisher - No more bytes available to read (got `-1` from `read`)
    2017-04-19 15:14:11,185 [debug] - akka.io.TcpOutgoingConnection - Resolving localhost before connecting
    2017-04-19 15:14:11,188 [debug] - akka.io.SimpleDnsManager - Resolution request for localhost from Actor[akka://ClusterSystem/system/IO-TCP/selectors/$a/0#-317536067]
    2017-04-19 15:14:11,188 [debug] - akka.io.TcpOutgoingConnection - Attempting connection to [localhost/127.0.0.1:443]
    2017-04-19 15:14:11,189 [debug] - akka.io.TcpOutgoingConnection - Connection established to [localhost:443]
    closed

On the server side, nothing is ever reached (I put some breakpoints with no success).

If I try to create the websocket with another client it works fine. It may be a SSL issue, but I have the same behavior with all SSL disabled (and the logs does not say anything else).
Any idea ?

Latest version (10.0.5) is used.

**Comment by jrudolph** [comment] 2017-04-19 13:26
Hi @epot, thanks for the report. It seems the reference / link to the source is missing? If you post a standalone reproducer that would increase chances that someone can look into it.

**Comment by epot** [comment] 2017-04-19 13:38
oops sorry, link fixed.

**Comment by jrudolph** [comment] 2017-04-19 14:08
We also need some approximation of the server as well. If the issue happens without SSL, can you try to capture a dump of the TCP traffic with wireshark/tcpdump?

**Comment by epot** [comment] 2017-04-19 14:10
I will try to do that. Is there any way to increase the verbosity or break somewhere in akka-http ? I am pretty sure the error is on my side, but even in debug I cannot see anything.

**Comment by epot** [comment] 2017-04-19 14:20
Ok so after checking - I should have done it before - no problem if the server runs without SSL.

**Comment by epot** [comment] 2017-04-19 14:24
I just got an occurent of:

    2017-04-19 16:22:33,571 [debug] - akka.io.TcpOutgoingConnection -  - Closing connection due to IO error java.io.IOException: An existing connection was forcibly closed by the remote host

That I never got before. I am guessing this is a SSL error, but I tried to disable all checks - to narrow down the issue since I get no specific log - with this, and the connection never happens:

    val badSslConfig = AkkaSSLConfig().mapSettings(s =>
      s.withLoose(s.loose.withDisableSNI(true)
        .withAcceptAnyCertificate(true)
        .withAllowLegacyHelloMessages(Some(true))
        .withAllowUnsafeRenegotiation(Some(true))
        .withAllowWeakCiphers(true)
        .withAllowWeakProtocols(true)
        .withDisableHostnameVerification(true))
    )

    val badCtx = Http().createClientHttpsContext(badSslConfig)

    val webSocketFlow = Http().webSocketClientFlow(WebSocketRequest(url), connectionContext = badCtx)

**Comment by jrudolph** [comment] 2017-05-08 11:14
Ok, let's keep this open a while longer if you figure out how to trigger it exactly, let us know.

**Comment by epot** [comment] 2017-05-09 13:07
It's definitely when the server SSL is incorrect in some way. Using a self certificate with a Play! dummy app should do the trick. Do you want me to put somewhere on Github such settings ?

**Comment by ktoso** [comment] 2017-05-10 04:33
Yes, if you could prepare a reproducer repo that would help a lot - then we
can spend more time on fixing rather than trying to reproduce.

-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 9 May 2017 at 22:07:36, epot (notifications@github.com) wrote:

It's definitely when the server SSL is incorrect in some way. Using a self
certificate with a Play! dummy app should do the trick. Do you want me to
put somewhere on Github such settings ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/1040#issuecomment-300156738>, or mute
the thread

**Comment by zfeng-cliqr** [comment] 2017-05-11 17:46
Same here. Trying a wss service with valid certificate e.g. wss://echo.websocket.org/, it works totally fine.

But if trying a websocket server with self-signed certificate. Trying the exact same setting as @epot epot, to disable all checks that I find inside AkkaSSLConfig, it still cannot connect.

**Comment by jrudolph** [comment] 2020-03-23 10:28
Closing for now

**Closed by jrudolph** 2020-03-23 10:28 UTC
Labels: 1 - triaged, bug, help wanted, t:client, t:core, t:tls
