### ISSUE TITLE
cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice

### ISSUE THREAD

**Issue by Birdflying1005** [akka/akka-http#1429] opened 2017-09-18 11:10 UTC
I am using akka-http to be a http client to invoke other http service.  When the connections are idle exceeding some minutes, the 1st invoke will meet this error as below, and 2nd time will be ok. That problem does exist from 10.0.1.
```
[ERROR] [09/18/2017 03:48:34.175] [Gateway-akka.actor.default-dispatcher-68] [akka://Gateway/user/StreamSupervisor-1/flow-33-0-mergePreferred] Error in stage [akka.http.impl.engine.client.PoolSlot$SlotProcessor@fb97ff4e]: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
java.lang.IllegalArgumentException: requirement failed: cannot pull port (SubSinkInlet(SlotProcessor.ResponseSink)) twice
        at scala.Predef$.require(Predef.scala:224)
        at akka.stream.stage.GraphStageLogic$SubSinkInlet.pull(GraphStage.scala:1087)
        at akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1$$anon$4.onPull(PoolSlot.scala:214)
        at akka.stream.impl.fusing.GraphInterpreter.processPull(GraphInterpreter.scala:506)
        at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:412)
        at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)
        at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:42)
        at akka.stream.impl.fusing.ActorGraphInterpreter$RequestMore.execute(ActorGraphInterpreter.scala:247)
        at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:514)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
        at akka.actor.ActorCell.invoke(ActorCell.scala:496)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[ERROR] [09/18/2017 03:48:34.182] [Gateway-akka.actor.default-dispatcher-72] [akka://Gateway/user/pool-master] connection pool for PoolGateway(hcps = HostConnectionPoolSetup(169.46.112.20,11080,ConnectionPoolSetup(ConnectionPoolSettings(32,4,5,1024,1,30 seconds,ClientConnectionSettings(Some(User-Agent: akka-http/10.0.10),10 seconds,1 day,512,None,<function0>,List(),ParserSettings(2048,16,64,64,8192,64,8388608,256,1048576,Strict,RFC6265,true,Full,Error,Map(If-Range -> 0, If-Modified-Since -> 0, If-Unmodified-Since -> 0, default -> 12, Content-MD5 -> 0, Date -> 0, If-Match -> 0, If-None-Match -> 0, User-Agent -> 32),false,<function1>,<function1>,<function2>),None),TCPTransport),akka.http.scaladsl.HttpConnectionContext$@c425fdb7,akka.event.MarkerLoggingAdapter@ae952d4f))) has shut down unexpectedly
```

**Comment by jrudolph** [comment] 2017-09-18 11:24
Hi @Birdflying1005,

Thanks for the report.

> That problem does exist from 10.0.1.

Have you checked if it still exists on 10.0.10?

**Comment by jrudolph** [comment] 2017-09-18 11:25
Btw, it seems to be a duplicate of https://github.com/akka/akka-http/issues/938, right?

**Comment by Birdflying1005** [comment] 2017-09-18 11:58
@jrudolph  Sure. I recreated the problem on 10.0.10.  

looks it is duplicated with #938.   The difference between 10.0.1 and 10.0.10 is 
`connection pool for PoolGateway` information has been printed out by akka-http.

**Comment by jrudolph** [comment] 2017-09-18 12:46
@Birdflying1005 thanks for the confirmation. Do you have a reproducer you could post to #938?

Duplicate of #938.

**Closed by jrudolph** 2017-09-18 12:46 UTC
