### ISSUE TITLE
One2OneBidiFlow$OutputTruncationException exception

### ISSUE THREAD

**Issue by idzivinskyi** [akka/akka-http#2066] opened 2018-06-13 00:01 UTC
With migrating to new akka-http (val akka = "2.5.13", val akkaHttp = "10.1.2") I got an error:

```
[system-akka.actor.default-dispatcher-3] ERROR a.a.ActorSystemImpl - Internal server error, sending 500 response
akka.http.impl.util.One2OneBidiFlow$OutputTruncationException: Inner flow was completed without producing result elements for 1 outstanding elements
```

Steps to reproduce:
1. Use code below
2. Open in chrome (or your favorite browser) http://localhost:8080
3. Reload tab 2 times

```
import akka.actor.{Actor, ActorRef, ActorSystem, Props}
import akka.http.scaladsl.Http
import akka.http.scaladsl.server.{Directives, Route}
import akka.pattern._
import akka.stream.ActorMaterializer
import akka.util.Timeout

import scala.concurrent.duration._
import scala.concurrent.{ExecutionContext, Future}
import scala.io.StdIn

object TestOne2OneBidiFlow extends App with Directives {

  implicit val system: ActorSystem = ActorSystem("system")

  implicit val executionContext: ExecutionContext = system.dispatcher

  implicit val materializer: ActorMaterializer = ActorMaterializer()

  implicit val timeout: Timeout = 2 seconds

  class Foo extends Actor {
    override def receive: Receive = {
      case _ =>
        Thread.sleep(1000)
        sender() ! Some(0)
    }
  }

  val foo: ActorRef = system.actorOf(Props(new Foo()))

  val route: Route = get {
    val future = foo ? "test"

    onSuccess(future) { _ =>
      complete("pong")
    }
  }

  val server: Future[Http.ServerBinding] = Http().bindAndHandle(Route.handlerFlow(route), "localhost", 8080)

  server.foreach { b =>
    println(s"Server started on ${b.localAddress.toString}")
  }

  println(s"Server online at http://localhost:8080/\nPress RETURN to stop...")
  StdIn.readLine()
  server.foreach(_.terminate(1 second))
}
```

Question: How handle this case properly?

**Comment by johanandren** [comment] 2018-06-13 08:16
The trigger for the logged error is not actually reloading the page, but reloading before the previous one had completed, right?

**Comment by raboof** [comment] 2018-06-13 08:54
Hello @idzivinskyi,

The main problem is in the parameter to `get`:

```
{
    val future = foo ? "test"

    onSuccess(future) { _ =>
      complete("pong")
    }
}
```

Since `val future = foo ? "test"` is not dependent on any input, this is just a constant block, `foo ? "test"` is only evaluated once and that one future is used for each request - which you obviously don't want.

A quick way to fix it in this case is to move it into the `onSuccess` (like `onSuccess(foo ? "test")`).

After this change I still see the `OutputTruncationException` (but only from the browser, not from curl). I can't explain that just yet, and don't see it with version 10.1.1. This is definitely something we will investigate further.

**Comment by raboof** [comment] 2018-06-13 09:11
My suspicion is that what's going on is when you reload the page before it has finished loading, the browser closes/cancels the previous request before the response has been sent, and we changed something between 10.1.1 and 10.1.2 that now causes that warning to be logged in that case. I assume you don't actually see a 500 error in the browser, is that correct?

(after a couple of refreshes you'll see a 500 error due to `akka.pattern.AskTimeoutException`, but that is to be expected)

**Comment by idzivinskyi** [comment] 2018-06-13 17:10
@raboof I have the same assumption. The client does not see 500 (I hope so), but I see the increased rate of 500 on balancer site, which makes me think that something wrong going on. 

Previous versions handled this situation by closing request before it finished on the server side. I think something changed there, but I could be wrong.

**Comment by eerikpotter** [comment] 2018-06-13 17:52
We experience the same error, including a memory leak with the version update from 10.1.1 to 10.1.2. So it's not only logging unfortunately.

**Comment by idzivinskyi** [comment] 2018-06-13 18:47
@eerikpotter same for me with the memory leak, but I was not been able to find root cause yet.

**Comment by mr-git** [comment] 2018-06-13 19:39
We have memory leak too - from heap dump it seems that memory leak originates in `MasterServerTerminator`, specifically `GracefulTerminatorStage` in `AtomicReference`.
It seems that these connection terminators are never removed from hashset of alive connections...

**Comment by ignasi35** [comment] 2018-06-13 20:04
I think this issue is also what's failing Play's [`WSSpec`](https://github.com/playframework/playframework/blob/master/framework/src/play-ahc-ws/src/test/scala/play/libs/ws/WSSpec.scala#L19-L51) which uses an AHC client to send a single `POST` request.

The `WSSpec` from Play seems a pretty good reproducer for it's simplicity (no load, proxy/gateway or browser required to see the failure).

**Comment by johanandren** [comment] 2018-06-14 06:53
The memory leak is tracked in #2067

**Comment by raboof** [comment] 2018-06-14 08:31
@ignasi35 thanks for that! It indeed seems related, and this is also a useful indication that this is something that also impacts non-error situations. What's worse, though, is that (looking with wireshark) it seems in this case it isn't triggered by the client closing the request side of the connection early... perhaps because the request body is chunked?

**Comment by ignasi35** [comment] 2018-06-14 11:01
@raboof if it's of any help, @marcospereira [pointed to other tests](https://github.com/playframework/playframework/pull/8471#issuecomment-397088119) un Play's suite that also fail.

**Closed** 2018-06-15 10:07 UTC
Labels: bug
