### ISSUE TITLE
Request entity completes normally on HttpIdleTimeoutException

### ISSUE THREAD

**Issue by kstokoz** [akka/akka-http#2116] opened 2018-07-14 19:14 UTC
On POST/PUT request when processing entity stream elements takes longer than server idle timeout caller receives `connection reset error` (expected), but entity flow completes normally (not expected) processing only part of the stream.

Reproducer:
```
object CompleteStreamReproducer extends App {

  val actorSystemConfig = ConfigFactory.parseString(
    """
      akka {
        loglevel = DEBUG
        loggers = ["akka.event.slf4j.Slf4jLogger"]
      }
      akka.http.server.parsing.max-content-length = infinite

      akka.http.server.idle-timeout = 5s
    """
  )

  implicit val system = ActorSystem("actor-system", actorSystemConfig)
  implicit val materializer = ActorMaterializer(ActorMaterializerSettings.create(system).withDebugLogging(true))(system)
  import system.dispatcher

  val route: Route =
    (path("putData") & put) {
      extractRequestEntity { entity =>
        complete {
          entity.dataBytes.map { data =>
            val start = System.currentTimeMillis()

            // simulate CPU intensive task like encryption, encoding, etc.
            while ((System.currentTimeMillis() - start) < 10000) {}

            data
          }.runWith(Sink.fold(0L){ (acc, s) => acc + s.length }).map { length =>
            println(s"Total length: $length")
            "OK"
          }.andThen {
            case result => println(s"Completed with $result")
          }
        }
      }
    }

  val bindingFuture = Http().bindAndHandle(route, "localhost", 8081)
  System.in.read()
}
```

Trying to send data:
```
$ curl -vv -X PUT -H "Content-Type: text/plain" "http://localhost:8081/putData" --data-binary @output-1G.dat
* Connected to localhost (127.0.0.1) port 8081 (#0)
> PUT /putData HTTP/1.1
> Host: localhost:8081
> User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
> Accept: */*
> Referer:
> Content-Type: text/plain
> Content-Length: 1073741824
> Expect: 100-continue
>
< HTTP/1.1 100 Continue
< Server: akka-http/10.1.1
< Date: Sat, 14 Jul 2018 19:08:25 GMT
* Recv failure: Connection reset by peer
* stopped the pause stream!
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

On Server side:
```
[2018-07-14 19:07:36.384 +0000] DEBUG - Successfully bound to /127.0.0.1:8081
[2018-07-14 19:08:25.339 +0000] DEBUG - New connection accepted
[2018-07-14 19:08:31.065 +0000] DEBUG - Aborting tcp connection to /127.0.0.1:60161 because of upstream failure: akka.http.impl.engine.HttpIdleTimeoutException: HTTP idle-timeout encountered, no bytes passed in the last 5 seconds. This is configurable by akka.http.[server|client].idle-timeout.
Total length: 65536
Completed with Success(OK)
[2018-07-14 19:08:55.625 +0000] INFO  - Request timeout encountered for request [PUT /putData Default(1073741824 bytes)]
```

As one can see processing entity stream completes normally processing only 65kb out of 1G.

**Comment by johanandren** [comment] 2018-07-16 11:16
Verified that I see the same. Thanks for the reproducer.

**Comment by johanandren** [comment] 2018-07-16 12:50
The problem is a race between the cancelation coming upstream and the error going downstream. This will require something like akka/akka#23908 before we can do anything about it I'm afraid.

I've pushed the reproducer encoded as a test in: https://github.com/johanandren/akka-http/tree/wip-2116-reproducer-johanandren

Recommended workaround, for now, is to set `akka.http.server.idle-timeout = 5s` high enough that your CPU bound never is what triggers the idle timeout.

**Comment by jrudolph** [comment] 2020-04-20 09:28
Fixed in #3022.

**Closed by jrudolph** 2020-04-20 09:28 UTC
Labels: 3 - in progress, bug, t:server
