### ISSUE TITLE
Chunked response stream not cancelled when TCP connection is shut down

### ISSUE THREAD

**Issue by rkuhn** [akka/akka-http#926] opened 2017-03-05 09:50 UTC
Given a server that sends SSE to a browser, when the browser closes the TCP connection (triggered by `EventSource.close()` from JavaScript) the SSE source is not shut down immediately, but only 60sec later after the idle timeout (I used `Source.actorRef` and DeathWatch). I have verified that the TCP connection is indeed gone immediately, so there must be an issue with termination propagation in the server layer. Unfortunately I don’t have time to dive into the machinery right now.

**Comment by ktoso** [comment] 2017-03-05 10:09
AFAIR we fixed such big recently, are you in the latest version?

**Comment by rkuhn** [comment] 2017-03-05 10:23
I assume that 10.0.4 is still the latest, and I am using it.

**Comment by ktoso** [comment] 2017-03-05 10:27
Yeah. We'll look into it then.
Any additional hints to reproduce are welcome.

**Comment by rkuhn** [comment] 2017-03-05 10:41
Really simple: open an EventSource from JS, get a few events, then call close() on it and open another EventSource that you keep listening to. Notice that the first connection goes away immediately but the SSE stream on the server only terminates a minute later.

**Comment by jrudolph** [comment] 2017-03-27 16:32
Seems to work for me in 10.0.5. I used the route shown below and then browsed to the URL. When I hit escape so that the TCP connection is closed, the logging stage shows "Downstream finished" immediately as expected.

```scala
path("events") {
  import de.heikoseeberger.akkasse.EventStreamMarshalling._
  import scala.concurrent.duration._

  def timeToServerSentEvent(time: LocalTime) =
    ServerSentEvent(DateTimeFormatter.ISO_LOCAL_TIME.format(time))

  complete(
    Source
      .tick(2.seconds, 2.seconds, NotUsed)
      .map(_ => {
        val now = LocalTime.now()
        println(s"Emitting $now")
        now
      })
      .map(timeToServerSentEvent)
      .keepAlive(1.second, () => ServerSentEvent.heartbeat)
      .log("events")
  )
}
```

**Comment by jrudolph** [comment] 2017-03-27 16:32
Log output:

```
backend Server is listening on localhost:8080
backend [DEBUG] [03/27/2017 18:32:24.773] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
backend [DEBUG] [03/27/2017 18:32:24.831] [default-akka.actor.default-dispatcher-2] [akka://default/system/IO-TCP/selectors/$a/0] New connection accepted
backend [DEBUG] [03/27/2017 18:32:26.024] [default-akka.actor.default-dispatcher-3] [akka.stream.Log(akka://default/user/StreamSupervisor-0)] [events] Element: 
backend 
backend Emitting 18:32:27.028
backend [DEBUG] [03/27/2017 18:32:27.036] [default-akka.actor.default-dispatcher-6] [akka.stream.Log(akka://default/user/StreamSupervisor-0)] [events] Element: data: 18:32:27.028
backend 
backend 
backend [DEBUG] [03/27/2017 18:32:28.047] [default-akka.actor.default-dispatcher-3] [akka.stream.Log(akka://default/user/StreamSupervisor-0)] [events] Element: 
backend 
backend Emitting 18:32:29.018
backend [DEBUG] [03/27/2017 18:32:29.018] [default-akka.actor.default-dispatcher-6] [akka.stream.Log(akka://default/user/StreamSupervisor-0)] [events] Element: data: 18:32:29.018
backend 
backend 
backend [DEBUG] [03/27/2017 18:32:29.019] [default-akka.actor.default-dispatcher-4] [akka://default/system/IO-TCP/selectors/$a/1] Closing connection due to IO error java.io.IOException: Broken pipe
backend [DEBUG] [03/27/2017 18:32:29.027] [default-akka.actor.default-dispatcher-6] [akka.stream.Log(akka://default/user/StreamSupervisor-0)] [events] Downstream finished.
```

**Comment by jrudolph** [comment] 2017-07-26 14:33
We could never reproduce this one so going to close it. Feel free to reopen with more information.

**Comment by ortex** [comment] 2018-08-24 22:11
I think I have similar issues: https://stackoverflow.com/questions/51995444/akka-http-chunked-response-stream-not-cancelled-when-tcp-connection-is-shut-do

@jrudolph @ktoso Could you take a look?

**Comment by jffrn** [comment] 2019-02-15 16:22
I was just trying SSE out with akka-http and I think this is still a problem. I adapted @jrudolph's route and, after going on the browser and calling EventSource.close() through the javascript console, the connection only closes after the idle-timeout:
```scala 
path("events")  {
    import akka.http.scaladsl.marshalling.sse.EventStreamMarshalling._

    def timeToServerSentEvent(time: LocalTime) =
        ServerSentEvent(DateTimeFormatter.ISO_LOCAL_TIME.format(time))

    complete {
      Source(1 to 3)
        .map(_ => {
          val now = LocalTime.now()
          println(s"Emitting $now")
          now
        })
        .map(timeToServerSentEvent)
        .log("events")
    }
}
```

**Comment by jrudolph** [comment] 2020-05-19 12:11
Duplicate of (newer) #1977.

**Closed by jrudolph** 2020-05-19 12:11 UTC
Labels: 1 - triaged, bug, help wanted, t:core
