### ISSUE TITLE
StackOverflowError on invalid media range in accept header.

### ISSUE THREAD

**Issue by mrumkovskis** [akka/akka-http#1072] opened 2017-04-30 13:41 UTC
Route produces java.lang.StackOverflowError (shuts the server down) if http request contains Accept header with invalid media range like: '*/xml'

For example: Accept: */xml

Can be reproduced on almost any running akka-http server using routing DSL including sample one provided in the documentation: http://doc.akka.io/docs/akka-http/current/scala/http/introduction.html#using-akka-http
Was not able to reproduce error using ScalatestRouteTest

This seems due to the error in header parsing i.e.
`akka.http.scaladsl.model.headers.Accept.parseFromValueString("*/xml").toOption.get.acceptsAll == true`

akka-http version: 10.0.5

**Comment by ktoso** [comment] 2017-05-01 12:37
Hi and thanks for the reproducer!
You're right, it should not fail so not-nicely, I'll have a look into it right away.

**Comment by jrudolph** [comment] 2017-05-02 12:15
We seem to have multiple problems here leading to the explained outcome:
 * `*/xml` is allowed as a valid media range. It seems to be allowed by [the grammar in RFC 7231](https://tools.ietf.org/html/rfc7231#section-5.3.2) but it isn't clearly defined what the meaning would be. We also didn't decide and didn't foresee that there will be other media ranges with mainType == "*" other than "*/*" and returned `acceptsAll == true`.
 * `RequestContextImpl.complete` allows unbounded recursion through `attemptRecoveryFromUnacceptableResponseContentTypeException` (in this particular case, what happens is that `*/xml` qualifies as `acceptsAll == true` but still doesn't accept anything).

History:

In https://github.com/akka/akka/issues/16494, support for `withAcceptAll` was added but it didn't foresee the `*/xyz` media-range which seems to be valid by grammar (but what should it mean?). In the model it returns `true` for `acceptsAll` but the actual range checking doesn't accept all media types. 

In https://github.com/akka/akka/issues/19397 and https://github.com/akka/akka/issues/19842 (fixed in https://github.com/akka/akka/issues/19849), it was attempted to make non-200 responses ignore the accept header. The solution was to rerun the marshalling with `withAcceptAll` in the case of non-2xx responses. This handling was added in a prominent place in `RequestContextImpl`. This is problematic for various reasons:

 * The fix was added at a code path that basically every request runs through, risking unintended side-effects (like here).
 * Marshallers might be run twice for one `complete` call. That might be unexpected.
 * A marshaller can already decide whether to take part in content negotiation or not. If it returns an opaque marshalling, it will work regardless of the `Accept` header.
 * So, in fact, the problem described in https://github.com/akka/akka/issues/19397 is only one of the `fromStatusCodeXXX` marshallers. That's the only place where non-2xx status codes can be injected. So, that's the place where it might be possible to fix it in a less-intrusive way.

**Comment by jrudolph** [comment] 2017-05-03 09:05
Fixed in #1075 and #1076. Followed up in #1082.

**Closed** 2017-05-03 09:04 UTC
Labels: 3 - in progress, bug

**Comment by jrudolph** [comment] 2017-05-03 09:05
Thanks a lot, @mrumkovskis to make us aware of this issue.

**Comment by mrumkovskis** [comment] 2017-05-03 13:23
Thanks @jrudolph @ktoso for quick reaction! Waiting for release 10.0.6 to upgrade my projects.
