### ISSUE TITLE
zero-copy file transfer support?

### ISSUE THREAD

**Issue by scf37** [akka/akka-http#638] opened 2016-12-10 15:04 UTC
I wasn't able to find out how to do zero-copy file transfer in akka-http server. [This one](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/FileChannel.html#transferTo(long,%20long,%20java.nio.channels.WritableByteChannel)).

Possibly it could be done by adding another `HttpEntity` type just like in Netty.

**Comment by jrudolph** [comment] 2016-12-12 10:07
@scf37, zero-copy file transfer is not supported in akka-http. It worked to some degree in spray but it turned out to be hard to maintain. Also, the performance benefits are not clear. E.g. `transferTo` blocks on IO and calls need to be managed not to starve threads.

If this would be implemented, it should probably similar to the existing support in Akka IO:
 * akka-stream network IO API would need a new interface with a data type that would also allow to specify bytes from files
 * in akka-http we would need to support that data type in all of the HttpEntity, replacing `Source[ByteString]` with `Source[ByteStringOrFromFile]`
 * directives like `getFromFile` etc would need to be adapted not to load data from files directly

A long time ago I suggested an alternative implementation to change `ByteString` to allow specification of "bytes from a file". There was already a PR on this a long time ago but we decided to postpone it: https://github.com/akka/akka/pull/2110

**Comment by jrudolph** [comment] 2016-12-12 10:08
I'm closing this as a duplicate of #270.

**Closed by jrudolph** 2016-12-12 10:08 UTC
Labels: 1 - triaged, t:core

**Comment by viktorklang** [comment] 2016-12-12 15:52
Also, serving static files is better done by a proxy or CDN.

-- 
Cheers,
√

On Dec 12, 2016 2:08 AM, "Johannes Rudolph" <notifications@github.com>
wrote:

I'm closing this as a duplicate of #270
<https://github.com/akka/akka-http/issues/270>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/638#issuecomment-266389304>, or mute
the thread
