### ISSUE TITLE
all the akka http java example links are dead

### ISSUE THREAD

**Issue by swatiaole** [akka/akka-http#1531] opened 2017-11-15 20:12 UTC
I am new to akka, and came here through akka.io documentation page to get the example source codes for practice. but none of the java example links are working here, getting 404 for all. this is very disappointing. Please can you help fixing this urgently? :( Thanks.

**Comment by jonas** [comment] 2017-11-15 21:19
Thanks a lot for reporting this @swatiaole.
In order to address this it would be very helpful if you can provide the URLs of one or more pages where the example source code links are not working.

**Comment by jonas** [comment] 2017-11-23 13:17
@swatiaole A reminder that without your help we will unfortunately have to close this ticket.

**Comment by jonas** [comment] 2017-11-30 02:47
It could sound like the same issue reported in #1581.

**Comment by jrudolph** [comment] 2017-11-30 09:07
Yep, let's close this one as a duplicate of #1581. @swatiaole if you meant something else, please let us know.

**Closed by jrudolph** 2017-11-30 09:07 UTC
Labels: 0 - new, bug, t:docs, t:java
