### ISSUE TITLE
Head Requests without GET

### ISSUE THREAD

**Issue by benoj** [akka/akka-http#653] opened 2016-12-13 09:40 UTC
Adding a resource endpoint with only a HEAD method results in a method not allowed response even though the method is defined. This requires me to set `akka.http.server.transparent-head-requests=off` which is slightly annoying.

If i have specifically defined a HEAD method, surely this should mean that the GET request with stripping body behaviour should be overridden?

**Comment by jrudolph** [comment] 2016-12-13 10:30
Yes, that's a known issue of the current implementation. I'm closing this as a duplicate of #40. We are currently considering an improvement in #549.

**Closed by jrudolph** 2016-12-13 10:30 UTC
