### ISSUE TITLE
Entities containing JSON arrays cannot be marshalled

### ISSUE THREAD

**Issue by johnhungerford** [akka/akka-http#3817] opened 2021-05-25 16:23 UTC
When I try to send an http request using `Http().singleRequest()`, with an entity built from a string in the form of "[ ... ]" (no matter what is inside the array), I get an NPE.

Akka version: 2.6.8
akka-http version: 10.2.4

Here is the code:

```scala

for {
            response <- Http().singleRequest(
                HttpRequest(
                    method = HttpMethods.POST,
                    uri = baseUrl + s"/submit",
                    entity = HttpEntity( ContentTypes.`application/json`, """["value-1","value-2","value-3]""" )
                )
            )
            body <- {
                Unmarshal( response.entity ).to[ String ]
            }
        } yield {
            val res = read[ PollResponse ]( body )
            UUID.fromString( res.jobId )
        }
```

The above snippet results in the following exception:

```
ERROR akka.actor.ActorSystemImpl - Error during processing of request: 'java.lang.NullPointerException (No error message supplied)'. Completing with 500 Internal Server Error response. To change default exception handling behavior, provide a custom ExceptionHandler.
java.lang.NullPointerException: null
        at akka.http.scaladsl.model.HttpEntity$.apply(HttpEntity.scala:294)
        at akka.http.scaladsl.marshalling.PredefinedToEntityMarshallers.$anonfun$stringMarshaller$1(PredefinedToEntityMarshallers.scala:46)
        at akka.http.scaladsl.marshalling.Marshaller$$anon$3.$anonfun$apply$2(Marshaller.scala:149)
        at akka.http.scaladsl.marshalling.Marshalling$WithOpenCharset.$anonfun$map$6(Marshaller.scala:206)
        at akka.http.scaladsl.marshalling.Marshal$$anonfun$selectMarshallingForContentType$2.$anonfun$applyOrElse$1(Marshal.scala:28)
        at akka.http.scaladsl.marshalling.Marshal.$anonfun$toResponseFor$1(Marshal.scala:71)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
        at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
        at akka.http.scaladsl.marshalling.Marshal.toResponseFor(Marshal.scala:55)
        at akka.http.scaladsl.marshalling.ToResponseMarshallable.apply(ToResponseMarshallable.scala:17)
        at akka.http.scaladsl.marshalling.ToResponseMarshallable.apply$(ToResponseMarshallable.scala:16)
        at akka.http.scaladsl.marshalling.ToResponseMarshallable$$anon$1.apply(ToResponseMarshallable.scala:22)
        at akka.http.scaladsl.server.RequestContextImpl.complete(RequestContextImpl.scala:39)
        at akka.http.scaladsl.server.directives.RouteDirectives.$anonfun$complete$1(RouteDirectives.scala:51)
        at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
        at akka.http.scaladsl.server.StandardRoute$$anon$1.apply(StandardRoute.scala:19)
        at akka.http.scaladsl.server.directives.FutureDirectives.$anonfun$onComplete$3(FutureDirectives.scala:37)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$2(FastFuture.scala:37)
        at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
        at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$3(FastFuture.scala:52)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
        at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

This appears to happen no matter what kind of array I include: `[]`, `[{"test":"test"},{"test":"test-2"}]`, or `[1,2,3,4]`. It goes away if I replace the array with a json object: `{"test":"test"}`, or `{}`.

I have tried to create the entity by generating the byte string myself, but I get the same exception:

```scala
entity = HttpEntity.Strict( ContentTypes.`application/json`, ByteString( "[\"test-string\"]".getBytes( "utf-8" ) ) )
```

What is especially problematic is that I get the same exception if I set the content type to plain text:

```scala
entity = HttpEntity( ContentTypes.`text/plain(UTF-8)`, """["value-1","value-2","value-3]""" )
```

While I think it is a bad design to exclude top-level arrays from JSON bodies, it is clearly a problem to reject them when the content type is plain text. There should be no marshaling to speak of going on when you provide a string body for a plain text content type.

Top-level json arrays should be supported since they are valid json. If they are not, they should produce a readable exception, not an NPE.

**Comment by johnhungerford** [comment] 2021-05-25 16:58
Looks like I missed something. Now that I've made the array a field of a json object, I'm still getting an NPE:

```scala
entity = HttpEntity( ContentTypes.`application/json`, """{"excluded_phrases":["something"]}""" )
```

So it can't be due to akka's lack of support for top-level json arrays as I had suspected. Still trying to figure out what's going on...

**Comment by raboof** [comment] 2021-05-25 17:03
This might have been a better fit for https://discuss.akka.io

That said, indeed I don't see anything wrong in the client code you shared here. Indeed pointing `baseUrl` at `https://akka.io` it fetched the website error page just fine.

The stack trace suggests this might be a problem at the server, not the client.

I turned your example into a minimal project at https://github.com/raboof/akka-http-reproduce-3817 and it seems to work fine:

```
sbt:akka-http-reproduce-3817> run
[info] compiling 1 Scala source to /home/aengelen/dev/akka-http-reproduce-3817/target/scala-2.12/classes ...
[info] running Main 
http://localhost:38447
Got request ["value-1","value-2","value-3]
Got response
Response
```

Could you expand the server-side of that project with the relevant bits of the code you're calling, showing the problem?

**Comment by raboof** [comment] 2021-06-01 10:28
> I'm unconvinced now that this is necessarily an issue on Akka's side. I'm sure I'm doing something wrong somewhere. Thanks for giving it the time you already have @raboof :)

Sure, happy to! Hope you find out what the problem is. I'll close this issue for now, but feel free to open a forum thread or issue depending on what you find ;)

**Closed by raboof** 2021-06-01 10:28 UTC
