### ISSUE TITLE
2.12 / 2.5.31 Outgoing request stream error

### ISSUE THREAD

**Issue by bitsofinfo** [akka/akka-http#3041] opened 2020-04-03 21:06 UTC
scala 2.12

2.5.31

`ActorSystemImpl`  random `Outgoing request stream error` spewed into logs from 

```
akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anon$2: Pool slot was shut down
```

No clue what this is or if its something to worry about

**Comment by jrudolph** [comment] 2020-04-06 10:43
Which version of akka-http do you use? It's probably a duplicate of #2728. An update to akka-http 10.1.11 might help.

**Comment by bitsofinfo** [comment] 2020-04-06 13:46
@jrudolph no clue, here is my gradle

```
	compile('com.typesafe.akka:akka-actor_2.12:2.5.31')
	compile('com.typesafe.akka:akka-slf4j_2.12:2.5.31')
	compile('com.typesafe.akka:akka-cluster_2.12:2.5.31')
	compile('com.typesafe.akka:akka-contrib_2.12:2.5.31')
	compile('com.typesafe.akka:akka-cluster-tools_2.12:2.5.31')

	compile group: 'com.lightbend.akka.management', name: 'akka-management-cluster-bootstrap_2.12', version: '1.0.6'
  	compile group: 'com.lightbend.akka.discovery', name: 'akka-discovery-kubernetes-api_2.12', version: '1.0.6'
  	compile group: 'com.typesafe.akka', name: 'akka-discovery_2.12', version: '2.5.31'
```

**Comment by bitsofinfo** [comment] 2020-04-06 13:46
@jrudolph the latter are my only declared dependencies to akka

**Comment by bitsofinfo** [comment] 2020-04-07 15:50
@jrudolph ... so what should I do here? is this a legit issue to be concerned about? what changes do I need to make to my build.gradle to resolve this?

**Comment by jrudolph** [comment] 2020-04-08 08:41
I see, no wonder that this is confusing. So, the akka-http dependency is pulled in transitively for you with akka management.

Adding an explicit dependency to akka-http with a higher version number should help:

```
	compile('com.typesafe.akka:akka-http_2.12:10.1.11')
```

Incidentally, here's some information about how you can see your concrete dependency tree including transitive dependencies with gradle: https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html

**Comment by jrudolph** [comment] 2020-04-15 13:01
We'll also upgrade the dependencies in akka-management (see https://github.com/akka/akka-management/pull/656), so the issue will be solved with the next version.

I'm closing this issue here for now. Let us know if adding the explicit dependency did not work.

**Closed by jrudolph** 2020-04-15 13:01 UTC
Labels: 0 - new

**Comment by pandey47D** [comment] 2023-04-21 12:53
@jrudolph facing the same issue. What is the concern with these messages?
