### ISSUE TITLE
Docs Http- Server-Sent Events Support

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1454] opened 2017-10-04 20:12 UTC
<a href="https://github.com/gastonlucero"><img src="https://avatars2.githubusercontent.com/u/9569274?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [gastonlucero](https://github.com/gastonlucero)**
_Wednesday Oct 04, 2017 at 19:03 GMT_
_Originally opened as https://github.com/akka/akka/issues/23782_

----

In [SSE-Support](https://doc.akka.io/docs/akka-http/current/scala/http/sse-support.html ) , scala marshalling and unmarshalling examples are the same, java examples are ok.

**Comment by jonas** [comment] 2017-10-04 22:19
Duplicate of #1445 and fixed in https://github.com/akka/akka-http/pull/1446

@ktoso I’ll let you manage the status and labeling of this one.

**Comment by jrudolph** [comment] 2017-10-05 08:06
Duplicate of #1445.

**Closed by jrudolph** 2017-10-05 08:06 UTC
