### ISSUE TITLE
Provide Coordinated Shutdown for Akka HTTP

### ISSUE THREAD

**Issue by jlprat** [akka/akka-http#1210] opened 2017-06-19 14:28 UTC
Make sure coordinated shutdown can be used in Akka HTTP, so pending requests can be processed before shutting the server down.

This idea originated as a comment from @raboof in https://github.com/akka/akka-http/pull/1207

> Would be cool if we had a nice way to "drain" ("stop listening for new requests but finish in-flight ones and shut down", with a timeout). Can we do that?

Further info: http://doc.akka.io/docs/akka/current/scala/actors.html#coordinated-shutdown
[Gitter Message](https://gitter.im/akka/dev?at=5947cc7af6a78eab48630612)

**Comment by ktoso** [comment] 2017-06-19 15:26
I just checked, it seems that indeed we never got to adding http to the phases of coordinated shutdown. So here we need to actually do that, and then document using coordinated shutdown with akka http :)

Somewhat related https://github.com/akka/akka-http/issues/188

**Comment by jlprat** [comment] 2017-06-19 15:28
Updating the ticket then.

**Comment by idzivinskyi** [comment] 2017-10-23 23:28
@jlprat @ktoso What the status of this task? Is there a workaround for this solution? 

As I understand from a bunch of opened and closed tickets ```serverBinding.unbind``` will just reject **new** connections when the opened connections still will work. In that case, does this code make any sense? 

```
  private val bind: Future[ServerBinding] = Http().bindAndHandle(flow, host, port)

  CoordinatedShutdown(system).addTask(
    CoordinatedShutdown.PhaseBeforeServiceUnbind, "http_shutdown") { () =>

    bind.map(_.unbind).flatMap { _ =>
      Http().shutdownAllConnectionPools
    }.map { _ =>
      Done
    }
  }
```

**Comment by ktoso** [comment] 2017-10-23 23:40
The status is as you see ;-) There's no hidden magical communication channels.

It's the wrong phase I think, rather this should be in:

```
  /**
   * Stop accepting new incoming requests in for example HTTP.
   */
  val PhaseServiceUnbind = "service-unbind"
```

as documented. Would you like to take a stab at this issue and submit a PR?

**Comment by idzivinskyi** [comment] 2017-10-25 22:30
@ktoso I would like to do it, but I have a question. `unbind` will just stop all new connections. How to stop all incoming connections? `Http().shutdownAllConnectionPools` - it looks like it does not make any sense without closing all incoming connections.

**Comment by jonas** [comment] 2017-12-09 18:25
Also related with #907

**Comment by jrudolph** [comment] 2017-12-11 09:30
`Http().shutdownAllConnectionPools` will forcibly stop all outgoing connections. `unbind` will stop accepting new incoming connections but it doesn't kill existing incoming ones, that would have to be implemented as well.

**Comment by johanandren** [comment] 2018-01-30 07:48
Note that it should be possible to opt out of this, since specific applications may have other needs (for example keep the HTTP server alive and respond after leaving the cluster)

**Comment by wsargent** [comment] 2018-02-27 19:10
Also related: https://github.com/akka/akka-http/issues/59

**Comment by ignasi35** [comment] 2018-07-17 10:13
> Note that it should be possible to opt out of this, since specific applications may have other needs (for example keep the HTTP server alive and respond after leaving the cluster)

+1 with a preference for `opt-in` vs `opt-out`. I think Akka HTTP as a library should not register any task on `CoordinatedShutdown` by default and instead provide docs or code to achieve it.

**Comment by ignasi35** [comment] 2018-07-17 10:14
Really late to the party,. just noticed https://github.com/akka/akka-http/pull/2072 😅

**Comment by ignasi35** [comment] 2018-07-18 19:33
If Akka-HTTP registers tasks into Coordinated Shutdown it will need to provide a means to disable them using a conf setting or something (as mentioned [above](https://github.com/akka/akka-http/issues/1210#issuecomment-361504084)). I find this default to be counter-intuitive.

I think Akka should provide the tools and the docs recommending how to use them.

Play and Lagom, OTOH, try to hide all the machinery and provide default setups that are reasonable enough. I that case I do think registering tasks by default is the right approach.

----------------

> Right though that's different

Oh, I see the difference now. 🤦‍♂️ 

Then, I think this issue should _only_ document how to connect the [graceful termination](https://github.com/akka/akka-http/pull/2072) with Coordinated Shutdown and maybe include some recommendations on when and when not to do it?

IIUC, at the moment it's possible to close akka HTTP using `unbind` or `terminate` so not adding default tasks still leaves it to a user to choose what to invoke.

I'm still not 100% decided what the best option is but, ATM, I think `only docs and not register Coordinated Shutdown tasks` is the right choice. Could be convinced otherwise. 😄

**Comment by michaelpisula** [comment] 2018-08-31 11:32
If `only docs and not register Coordinated Shutdown tasks` is the agreed solution, I could take a stab at adding it to the docs, I have a working solution I posted some weeks back on the discuss thingy. Would be happy to help :-)

**Comment by hseeberger** [comment] 2019-03-18 08:28
I think in order to properly support Coordinated Shutdown we need to modify or supplement `terminate`, because `unbind` should happen during `PhaseServiceUnbind` while the other stuff (finishing already accepted requests, draining new requests on established connections, etc.) should happen during `PhaseServiceRequestsDone`.

Would it be possible to expose the `terminateAction` or offer a method which delegates to that? 

Maybe we should even rename `terminate` to `unbindAndTermninate` and use the name `terminate` for a method which only does what the current `terminateAction` does.

**Comment by jroper** [comment] 2019-04-18 03:38
@hseeberger `unbind()` is idempotent, I had a look at the code, all it does is delegate to the Akka IO `ServerBinding.unbind`, which eventually delegates to this method, which is clearly idempotent:

https://github.com/akka/akka/blob/87354a6c9e61cdaacbaef8ddd116f7d56d5b47ea/akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala#L142-L148

So it doesn't really matter if `terminate` calls it - the only negative side effect may be that an `Unbind` message gets dead lettered - this can probably be avoided by checking if the `unbindPromise` is completed before sending the `Unbind` message [here](https://github.com/akka/akka/blob/87354a6c9e61cdaacbaef8ddd116f7d56d5b47ea/akka-stream/src/main/scala/akka/stream/impl/io/TcpStages.scala#L79).

So this is the way I'm doing coordinated shutdown:

```scala
      val shutdown = CoordinatedShutdown(system)

      shutdown.addTask(CoordinatedShutdown.PhaseBeforeServiceUnbind, "http-unbind") { () =>
        binding.unbind().map(_ => Done)
      }

      shutdown.addTask(CoordinatedShutdown.PhaseServiceRequestsDone, "http-graceful-terminate") { () =>
        binding.terminate(10.seconds).map(_ => Done)
      }

      shutdown.addTask(CoordinatedShutdown.PhaseServiceStop, "http-shutdown") { () =>
        Http().shutdownAllConnectionPools().map(_ => Done)
      }
```

**Comment by hseeberger** [comment] 2019-04-18 13:30
@jroper thanks. I had already figured out that unbind is idempotent and I'm shutting down exactly like you have shown ;-)

**Comment by cyburgee** [comment] 2019-04-30 22:21
@jroper I've implemented a graceful shutdown similar to how you've demonstrated, however I'm seeing that chunked responses are being munged and return garbage even if the service is just returning a small bit of json that definitely could be returned within the termination hard deadline. have you seen or dealt with this issue?

**Comment by mikela** [comment] 2020-01-15 22:03
@cyburgee If you don't mind _temporary hacks_  you could add a `Thread.sleep` before actually triggering the termination, something like:
```
val binding = Http().bindAndHandle(routes, "127.0.0.1", 8080)
shutdown.addTask(CoordinatedShutdown.PhaseServiceUnbind, "http-unbind") { () =>
  binding.flatMap(_.unbind()).map(_ => Done)
}
shutdown.addTask(CoordinatedShutdown.PhaseServiceRequestsDone, "http-graceful-termination") { () =>
  binding.flatMap(b =>
    Future(Thread.sleep(10000)).flatMap(_ => b.terminate(15.seconds))
  ).map(_ => Done)
}
```
And in the conf:
```
akka.coordinated-shutdown.default-phase-timeout = 15s
```
This will unbind the port and then enforce a "minimum delay" so all in-flight responses can return normally if they return in less than 10s. 

The problems with this solution are that:
1. Any request that takes longer than 10s will still have the problem you mentioned.
2. The phase will take 10s even if there are no in-flight requests.

**Comment by hseeberger** [comment] 2020-01-16 07:52
Instead of sleep you should use akka.pattern.after which already gives you a Future.

**Comment by mikela** [comment] 2020-01-16 08:26
Thank you! Edited.

**Comment by jroper** [comment] 2020-01-16 10:27
@cyburgee No, I haven't seen that, but I also haven't been using it in anger enough yet to see that. It sounds like what you're seeing is a bug. If you're able to reproduce, or can show more errors/interesting logs, it would be very helpful if you raised an issue about it.

**Comment by ignasi35** [comment] 2020-02-02 05:33
Related to https://github.com/playframework/playframework/pull/9970 (Play `2.8.1`)

**Comment by ennru** [comment] 2020-05-14 14:03
I've opened #3142 which includes a simple way to add the recommended steps to Coordinated shutdown.

**Comment by ennru** [comment] 2020-05-26 13:24
With #3142 users can now add their server bindings to Akka Coordinated shutdown.

**Closed by ennru** 2020-05-26 13:24 UTC
Labels: help wanted, t:core

**Comment by alexklibisz** [comment] 2021-01-07 01:15
I ran into this while using akka-grpc on k8s, which is still on akka-http 10.1.2 (before @ennru's fix above). If you're running in k8s, a simple solution is to follow @mikela's suggestion above, but set `akka.coordinated-shutdown.default-phase-timeout` to a value greater than your pod's `terminationGracePeriodSeconds` (30s by default). Ideally one should coordinate the duration passed to akka.pattern.after with the terminationGracePeriodSeconds and the default-phase-timeout.

**Comment by raboof** [comment] 2021-01-07 08:03
Thanks for the suggestion!

> akka-grpc on k8s, which is still on akka-http 10.1.2 (before @ennru's fix above)

Note that it is also possible to run Akka gRPC with Akka HTTP 10.2.2 (because Akka HTTP 10.2.2 is binary compatible with 10.1.x).
