### ISSUE TITLE
HttpServerSpec: have a programmatically set timeout handler

### ISSUE THREAD

**Issue by raboof** [akka/akka-http#1566] opened 2017-11-28 12:10 UTC
https://jenkins.akka.io:8498/job/pr-validator-akka-http/1768/consoleFull

**Comment by jrudolph** [comment] 2017-11-28 12:18
Probably a duplicate of #595 or #1376?

**Comment by jrudolph** [comment] 2019-02-12 14:36
Didn't happen for a long time.

**Closed by jrudolph** 2019-02-12 14:36 UTC
Labels: failed
