### ISSUE TITLE
akka-http 10.0.11 (akka 2.5.7) memory leak

### ISSUE THREAD

**Issue by idzivinskyi** [akka/akka-http#1613] opened 2017-12-08 22:57 UTC
After updating to a new version of `akka`(10.0.11) and `akk-http`(2.5.7). I got a memory leak:

Memory:
<img width="420" alt="screen shot 2017-12-08 at 1 10 29 pm" src="https://user-images.githubusercontent.com/1756485/33785291-3399d812-dc19-11e7-8508-e28168deeebf.png">

CPU: 
<img width="418" alt="screen shot 2017-12-08 at 1 13 41 pm" src="https://user-images.githubusercontent.com/1756485/33785393-a446cc6e-dc19-11e7-83cd-cf8632a008ea.png">

I have memory dump which was made after restart of machine:

Unhealthy: 
<img width="930" alt="screen shot 2017-12-08 at 1 44 11 pm" src="https://user-images.githubusercontent.com/1756485/33786573-813e2dd4-dc1e-11e7-8734-9be962df22c8.png">

If compare it with `akka`(10.0.10) and `akk-http`(2.5.6)
Healthy:
<img width="932" alt="screen shot 2017-12-08 at 1 44 31 pm" src="https://user-images.githubusercontent.com/1756485/33786618-a3ed6d7c-dc1e-11e7-8f77-e500f9883ff4.png">

The memory report from eclipse mat is:

```
One instance of "akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1" loaded by "sun.misc.Launcher$AppClassLoader @ 0x700000000" occupies 156,298,648 (28.91%) bytes. The memory is accumulated in one instance of "java.lang.Object[]" loaded by "<system class loader>".

Keywords
sun.misc.Launcher$AppClassLoader @ 0x700000000
akka.http.impl.engine.client.PoolSlot$SlotProcessor$$anon$1
java.lang.Object[]
```

It appears with both `legacy` and `new` client thread pools.

**Comment by ktoso** [comment] 2017-12-09 01:51
Please upgrade to Akka 2.5.8, which fixes this.

-- 
Konrad Malawski

**Comment by jrudolph** [comment] 2017-12-11 09:33
Indeed, this was probably caused by https://github.com/akka/akka/issues/24046. I'm closing this for now, please let us know if it is still a problem using Akka 2.5.8.

**Closed by jrudolph** 2017-12-11 09:33 UTC

**Comment by idzivinskyi** [comment] 2017-12-11 17:50
Yes, just tested. It resolved the issue. Thank you.

**Comment by jrudolph** [comment] 2017-12-11 20:16
Great thanks for testing.

Am 11.12.2017 18:50 schrieb "Ilya Dzivinskyi" <notifications@github.com>:
