### ISSUE TITLE
Unmarshalling JSON depends on routes order and request size

### ISSUE THREAD

**Issue by otrebski** [akka/akka-http#1802] opened 2018-01-19 21:23 UTC
I want to have one URL to send request with single element (as JSON object) or list of elements (JSON array). I have defined routes like in example below:

```scala
  val routes: Route = {

    val singleRoute = (post & entity(as[User])) { user =>
      complete {
        Response(s"Single user $user")
      }
    }
    val listRoute = (post & entity(as[List[User]])) { users =>
      complete {
        Response(s"List of users, size ${users.size}")

      }
    }
    
    path("u1") {
      listRoute ~
        singleRoute
    } ~ path("u2") {
      singleRoute ~
        listRoute
    }
    
  }

```
We have defined 2 URL's `u1` and `u2`. Both URL's are trying  to unmarshall JSON object or JSON array. Difference is in order.
`u1` tries to unmarshall JSON array first, `u2` tries to unmarshall JSON object first. If request is smaller than 128kB, both URL's works. If request is bigger than 128kB, only `u1` is able to unmarshall JSON array.
Error looks like this (Requests send with IntelliJ Rest client):
```http request
POST http://localhost:9000/u2
Content-Type: application/json
Accept: application/json

< ./biggerThan128kb.json

HTTP/1.1 400 Bad Request
Server: akka-http/10.0.11
Date: Fri, 19 Jan 2018 07:48:59 GMT
Content-Type: text/plain; charset=UTF-8
Content-Length: 71

The request content was malformed:
Object expected in field 'firstName'
```

On the other hand, sending request smaller than 128kb works fine:
```http request
POST http://localhost:9000/u2
Content-Type: application/json
Accept: application/json

HTTP/1.1 200 OK
Server: akka-http/10.0.11
Date: Fri, 19 Jan 2018 21:10:33 GMT
Content-Type: application/json
Content-Length: 35

{"body":"List of users, size 1914"}

```

Example project: [https://github.com/otrebski/akka-http-128kb](https://github.com/otrebski/akka-http-128kb)
HTTP requests: [https://github.com/otrebski/akka-http-128kb/blob/master/test.http](https://github.com/otrebski/akka-http-128kb/blob/master/test.http)

**Comment by jrudolph** [comment] 2018-01-23 16:48
That's because with big enough entities it's likely that akka-http will not receive them in one go and creates a streamed request entity. Streamed request entities can currently only be read once. If you want to rejection / route alternatives to work with entity and streamed entities you need to strictify the entity first. Try the `toStrictEntity` directive around the whole route.

**Comment by ktoso** [comment] 2018-01-23 16:49
Docs here:
http://doc.akka.io/docs/akka-http/current/java/http/implications-of-streaming-http-entity.html

Though we’d want to improve the situation eventually.

-- 
Cheers,
Konrad 'ktoso <http://kto.so>' Malawski
Akka <http://akka.io/> @ Lightbend <http://lightbend.com/>

On January 20, 2018 at 6:23:52, Krzysztof (notifications@github.com) wrote:

I want to have one URL to send request with single element (as JSON object)
or list of elements (JSON array). I have defined routes like in example
below:

  val routes: Route = {

    val singleRoute = (post & entity(as[User])) { user =>
      complete {
        Response(s"Single user $user")
      }
    }
    val listRoute = (post & entity(as[List[User]])) { users =>
      complete {
        Response(s"List of users, size ${users.size}")

      }
    }

    path("u1") {
      listRoute ~
        singleRoute
    } ~ path("u2") {
      singleRoute ~
        listRoute
    }

  }

We have defined 2 URL's u1 and u2. Both URL's are trying to unmarshall JSON
object or JSON array. Difference is in order.
u1 tries to unmarshall JSON array first, u2 tries to unmarshall JSON object
first. If request is smaller than 128kB, both URL's works. If request is
bigger than 128kB, only u1 is able to unmarshall JSON array.
Error looks like this (Requests send with IntelliJ Rest client):

POST http://localhost:9000/u2Content-Type: application/jsonAccept:
application/json

< ./biggerThan128kb.json

HTTP/1.1 400 Bad RequestServer: akka-http/10.0.11Date: Fri, 19 Jan
2018 07:48:59 GMTContent-Type: text/plain;
charset=UTF-8Content-Length: 71

The request content was malformed:
Object expected in field 'firstName'

On the other hand, sending request smaller than 128kb works fine:

POST http://localhost:9000/u2Content-Type: application/jsonAccept:
application/json

HTTP/1.1 200 OKServer: akka-http/10.0.11Date: Fri, 19 Jan 2018
21:10:33 GMTContent-Type: application/jsonContent-Length: 35

{"body":"List of users, size 1914"}

Example project: https://github.com/otrebski/akka-http-128kb
HTTP requests:
https://github.com/otrebski/akka-http-128kb/blob/master/test.http

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/1802>, or mute the thread

**Comment by jrudolph** [comment] 2018-03-06 15:10
Let's treat this as a duplicate of existing tickets around this topic.

**Closed by jrudolph** 2018-03-06 15:10 UTC
Labels: 0 - new
