### ISSUE TITLE
RepointableActorRef: Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.

### ISSUE THREAD

**Issue by relgames** [akka/akka-http#373] opened 2016-10-06 21:18 UTC
(moved from https://github.com/akka/akka/issues/21632)

I use both server DSL and http client.
I'm seeing `No elements passed in the last 1 minute` exceptions in logs:

```
[2016-10-06 22:51:59,234] [  DEBUG] [patcher-13] [akka://app/user/pool-master/PoolInterfaceActor-1] a.h.i.e.c.PoolInterfaceActor: Shutting down host connection pool to maps.googleapis.com:443
[2016-10-06 22:51:59,715] [  DEBUG] [patcher-13] [akka://app/user/pool-master/PoolInterfaceActor-0] a.h.i.e.c.PoolInterfaceActor: Shutting down host connection pool to localhost:8080
[2016-10-06 22:52:35,374] [  DEBUG] [patcher-11] [akka://app/user/StreamSupervisor-1/flow-7-0-unknown-operation] a.a.RepointableActorRef: Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
akka.actor.Actor$class.aroundReceive(Actor.scala:484)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

After not getting any suggestions in Gitter [1](https://gitter.im/akka/akka?at=57f572c2d45d7f0f5266e822) [2](https://gitter.im/akka/akka?at=57f6a7e970fcb5db0c35cfc5) [3](https://gitter.im/akka/akka?at=57f4f0a80ec6f9457da34ade) I tried to debug it myself: I wrote logging wrappers for both server and client HttpEntities:

```
    Route createRoute() {
        return mapRequest(req -> {
            Source<ByteString, Object> data = req.entity().getDataBytes()
                .log("my-request");
            return req.withEntity(HttpEntities.create(req.entity().getContentType(), data));
        }, this::oldRouter);
    }
```

and same for http requests (I use one utility class which uses Http flow across the whole app so all http requests are going through it):

```
                        .thenApply(resp -> {
                            log.debug("Got response for {}: {}", requestId, resp);

                            Source<ByteString, Object> data =  resp.entity().getDataBytes()
                                .log("my-debug-" + requestId);

                            return resp.withEntity(HttpEntities.create(resp.entity().getContentType(), data));
                        });
```

And then I counted all incoming requests vs number of `Upstream finished` log messages:

```
[2016-10-06 22:51:27,938] [  DEBUG] [patcher-10] [akka.stream.Log(akka://app/user/StreamSupervisor-0)] a.s.Materializer: [my-request] Upstream finished.
```

And numbers do match for both server and client. Which means I'm consuming entities correctly for both http DSL and http client sides. 

Still, I see TimeoutExceptions, and I suspect there is a leak somewhere. Last week the application stopped getting HttpResponses and I had to restart it.

What I want from this issue:
1) If it's a real leak, the fix is needed;
2) If there is no leak and my code is wrong, I need a way to clearly see which http request or response is not consumed, meaning akka needs better error message than just " Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute".

**Comment by relgames** [comment] 2016-10-06 21:21
Note to the comment https://github.com/akka/akka/issues/21632#issuecomment-252088706:

I'm consuming all responses correctly, either by converting it to String or using Sink.ignore().
Still I see timeout exceptions. I tried to set akka.http.host-connection-pool.idle-timeout = 2 s and I indeed see ```Shutting down host connection pool``` after 2 seconds, but then I still see ```Aborting tcp connection``` after 60 seconds:

```
[2016-10-06 23:15:02,396] [  DEBUG] [spatcher-3] [akka://feedigy/user/pool-master/PoolInterfaceActor-1] a.h.i.e.c.PoolInterfaceActor: Shutting down host connection pool to maps.googleapis.com:443
[2016-10-06 23:15:02,784] [  DEBUG] [spatcher-3] [akka://feedigy/user/pool-master/PoolInterfaceActor-0] a.h.i.e.c.PoolInterfaceActor: Shutting down host connection pool to localhost:8080
[2016-10-06 23:16:06,522] [  DEBUG] [spatcher-2] [akka://feedigy/user/StreamSupervisor-1/flow-7-0-unknown-operation] a.a.RepointableActorRef: Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
```

**Comment by relgames** [comment] 2016-10-06 21:23
Would be really nice to see what connection exactly is causing timeouts, not just generic log message.

**Comment by ktoso** [comment] 2016-10-06 21:24
Yes, I agree let's improve that. Contribs welcome, one should find the `idleTimeout` in the pipeline and replace it with a special stage

**Comment by relgames** [comment] 2016-10-06 21:33
I've been able to confirm: the message is indeed caused by host connection pooling:
```
$ lsof -P -p 52083 | grep TCP
java    52083 relgames   70u    IPv6 0x2696540b383d69ef       0t0       TCP *:7533 (LISTEN)
java    52083 relgames   88u    IPv6 0x2696540b408fda2f       0t0       TCP localhost:8081 (LISTEN)
java    52083 relgames   92u    IPv6 0x2696540b35a1f4af       0t0       TCP localhost:59343->localhost:8080 (ESTABLISHED)
java    52083 relgames   93u    IPv6 0x2696540b408fea4f       0t0       TCP localhost:59344->localhost:8080 (ESTABLISHED)
java    52083 relgames   94u    IPv6 0x2696540b27024a4f       0t0       TCP rgworkx.local:59345->ams16s30-in-f10.1e100.net:443 (ESTABLISHED)
java    52083 relgames   95u    IPv6 0x2696540b437ea4cf       0t0       TCP localhost:59346->localhost:8080 (ESTABLISHED)
java    52083 relgames   96u    IPv6 0x2696540b27025a6f       0t0       TCP localhost:59347->localhost:8080 (ESTABLISHED)
```

When timeouts happen, connections are gone in lsof.
I will try to improve the message.

BTW, shouldn't it close all connections when a pool is shutting down?..

**Comment by alcortaj** [comment] 2016-11-01 18:00
s

**Comment by ktoso** [comment] 2016-12-02 12:26
Closing this as it's a duplicate of https://github.com/akka/akka-http/issues/505

**Closed** 2016-12-02 12:26 UTC
Labels: 1 - triaged
