### ISSUE TITLE
Document or provide adding "response timeout"

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#622] opened 2016-12-06 23:32 UTC
It's less trivial since it requires to drain the response entity anyway even if it came "too late".
Simple impl would be:

```scala
package akka.http.scaladsl.client

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.Materializer

import scala.concurrent.{Future, Promise}
import scala.concurrent.duration.FiniteDuration
import scala.util.{Failure, Success}

final case class ResponseTimeoutException(request: HttpRequest, message: String) extends RuntimeException(message)

final class FancyClientTimeouts(implicit system: ActorSystem, mat: Materializer) {
  val http = Http(system)


  def singleRequestWithTimeout(request: HttpRequest, responseTimeout: FiniteDuration): Future[HttpResponse] = {
    val response = http.singleRequest(request)
    val p = Promise[HttpResponse]()

    // allocating failure here since this way the stacktrace will point to where this was called from:
    val timeoutException = RequestTimeoutException(request, s"Response did not arrive within $responseTimeout")
    
    
    // timeout exception
    val timeoutCancellable = system.scheduler.scheduleOnce(responseTimeout, new Runnable {
      override def run(): Unit = p.tryFailure(timeoutException)
    })
    
    response.onComplete {
      case Success(res) => 
        timeoutCancellable.cancel()
        // we attempt to suceed the Future, not with 2 steps because of atomicity of the swap
        try p.success(res) catch {
          case _: Throwable =>
            system.log.debug("Draining entity body for late response [{} {}], which was completed with timeout ({}) failure already.", request.method, request.uri, responseTimeout)
            res.discardEntityBytes() // we discard the databytes explicitly, to avoid stalling the connection
            
        }
      case Failure(failed) => 
        timeoutCancellable.cancel()
        p.tryFailure(failed)
    }
    
    p.completeWith(response.map { res =>
      timeoutCancellable.cancel()
      res
    })

    p.future
  }

}

```

**Comment by amansh1491** [comment] 2018-09-20 13:52
@ktoso  I have written a java code for Http Request Timeout , I am facing following issue =>

If possible , please check my code - 
After 4 successful response , all other request's are getting stucked and failing with Request Timeout 

Overriden following in reference.conf :- 
akka.http.host-connection-pool.max-connections = 4
akka.http.host-connection-pool.max-retries = 3
akka.http.host-connection-pool.max-open-requests = 16384

CODE >>>> 

private <T> CompletableFuture<T> failAfter(FiniteDuration duration, Cancellable[] cancellables) {
        CompletableFuture<T> promise = new CompletableFuture<>();
        cancellables[0] = system.scheduler().scheduleOnce( duration,
                                                           () -> promise.completeExceptionally(new HttpRequestTimeoutException()),
                                                           system.dispatcher()

        );
        return promise;
    }

    public CompletionStage<HttpResponse> singleRequestWithTimeout(HttpRequest request, int length) {
        Cancellable[] cancellables = new Cancellable[1];
        CompletableFuture<HttpResponse> oneSecondTimeout = failAfter(FiniteDuration.apply(length,MILLISECONDS),cancellables);
        CompletionStage<HttpResponse> responseC = http.singleRequest(request);
        return responseC.
                applyToEither(oneSecondTimeout,resp -> {
                             cancellables[0].cancel();
                             if( !oneSecondTimeout.isCompletedExceptionally()) {
                                  oneSecondTimeout.complete(resp);
                             }
                             return resp;
                }).exceptionally( throwable -> {
                    logger.error("Problem", throwable);
                    System.out.println(" Exception occurred, timeout issue");
                    discardEntityBytes(responseC);
                    return null;
                });
    }

    private  void discardEntityBytes(CompletionStage<HttpResponse> respC) {
        System.out.println("Discarding Entity Bytes");
        respC.thenApply( httpResponse -> httpResponse.entity()
                                                     .discardBytes(materializer));
    }

**Comment by juanavelez** [comment] 2020-02-06 16:27
It'd be great if request(response) timeout can be added to the request-level Akka Http Client.

**Comment by jrudolph** [comment] 2020-02-10 10:11
See also #42. Closing as a duplicate of that more general ticket (but we know it's still important).

**Closed by jrudolph** 2020-02-10 10:11 UTC
Labels: 1 - triaged, help wanted, t:core, t:docs
