### ISSUE TITLE
form directives strict about character encoding in content type header

### ISSUE THREAD

**Issue by kag0** [akka/akka-http#1239] opened 2017-06-26 23:32 UTC
I'm trying to implement a simple OAuth 2 user credentials token grant in akka http, but am getting an unexpected error.

My route is just this
```scala
path("token") {
    post {
      formField('grant_type) {
        case "password" =>
          formFields('username, 'password) { (username, password) =>
          complete(s"$username : $password")
        }
        case _ => complete(StatusCodes.BadRequest)
      }
    }
  }
```
and curling this in
```bash
curl -X POST \
http://localhost:8080/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-d 'grant_type=password&username=jim%40jim.jim&password=pass'
```
earns me this error in the http response body
```
The form field 'grant_type' was malformed: application/x-www-form-urlencoded (of class akka.http.scaladsl.model.ContentType$WithMissingCharset)
```
If I add ;charset=UTF-8 to the end of the Content-Type header, it's fine and works as expected.

Is there a setting somewhere to make the server not require an encoding, or is this a bug?

setup information: Scala 2.11.11, akka-http 10.0.8, JDK 8, fedora linux

(externally asked at https://stackoverflow.com/questions/44742102/akka-http-strict-about-character-encoding-in-content-type)

**Comment by raboof** [comment] 2017-06-27 07:04
Hi @kag0, thanks for your report. Could you try with version 10.0.9? 10.0.8 indeed had a regression when handling content types that fail to specify the charset, and our fix also resolves the issue in your reproducer above.

**Comment by daddykotex** [comment] 2017-06-27 19:12
I had the same problem, but a 404 (which happens because my route is build differently). Going to 10.0.9 fixed the issue.

**Comment by daddykotex** [comment] 2017-06-27 19:15
by the way @kag0 
I'm working on a similar thing here, and you could simplify with:
```
path("token") {
    post {
      formField('grant_type ! "password") {
          formFields('username, 'password) { (username, password) =>
          complete(s"$username : $password")
        }
      }
    }
  }
```

**Comment by raboof** [comment] 2017-06-27 21:09
(closing for now as @daddykotex reported success with 10.0.9, feel free to reopen or open a new issue if you still run into problems with that version)

**Closed by raboof** 2017-06-27 21:09 UTC

**Comment by kag0** [comment] 2017-06-27 21:27
Thanks @raboof, will give 9 a shot.

and thanks for reporting in @daddykotex. I've got that matching in there because I intend to be handling other grant types as well. But if you're just doing password, you can simplify even more with:
```scala
path("token") {
    post {
      formFields('grant_type ! "password", 'username, 'password) { (username, password) =>
        complete(s"$username : $password")
      }
    }
  }
```
