### ISSUE TITLE
HTTPS connections continue to read the entire response body when cancelled

### ISSUE THREAD

**Issue by ominiom** [akka/akka-http#1023] opened 2017-04-10 20:06 UTC
The following program (with akka-http 10.0.5) exhibits the problem.

Network statistics for the process show that the entire 10 MB response has been received even though it is cancelled immediately.

Using `cachedHostConnectionPool` instead and performing the same request over http generally shows < 100KB received (probably just the first chunk of data received before cancellation takes effect)

```scala
package test

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.{Sink, Source}

import scala.util.Success

object TestCase {

  val uri = Uri("https://cloudharmony.com/probe/test10mb.jpg")

  implicit val system = ActorSystem("system")
  implicit val materializer = ActorMaterializer()

  implicit val executionContext = scala.concurrent.ExecutionContext.global

  val httpFlow = Http(system).cachedHostConnectionPoolHttps[Uri](
    host = s"${uri.authority.host}"
  )

  def main(args: Array[String]) {
    val request = HttpRequest(uri = uri)

    Source.single((request, uri))
      .via(httpFlow)
      .runWith(Sink.head)
      .foreach {
        case (Success(response), uri) =>
          response.entity.withoutSizeLimit.dataBytes.runWith(Sink.cancelled)
      }
  }

}
```

**Comment by jlprat** [comment] 2017-04-10 20:16
Somehow related to #738

**Comment by jrudolph** [comment] 2017-04-13 10:10
Thanks for providing the reproducer, @ominiom. This seems to be a duplicate of https://github.com/akka/akka-http/issues/983. I'm closing this for now but feel free to reopen if you think it's a different issue.

**Closed** 2017-04-24 09:15 UTC

**Comment by jrudolph** [comment] 2017-06-26 14:21
I tried the reproducer but everything seems to work as expected on top of current master (a46958b56a3225bfaf4b53d1c5d11cb3e5a11119) and on v10.0.5. I posted the concrete test I used and the log here: https://gist.github.com/jrudolph/a746baf1a792e48bb4a314aba610a771.

By enabling `log-unencrypted-network-bytes` you can see that the connection closed when `Sink.cancelled` is used and the slot immediately reconnects to run the second request.

Network statistics might be off just due to the reason that the OS network stack might have already received data while the app is still closing down the connection (for me it takes < 2s to download the 10MB) but it could be something else of course.

If you are still interested in this issue, could you maybe run my version of the reproducer and post the log?
