### ISSUE TITLE
ConnectionPoolSpec failure

### ISSUE THREAD

**Issue by rbudzko** [akka/akka-http#491] opened 2016-11-07 14:46 UTC
Please see https://jenkins.akka.io:8498/job/pr-validator-akka-http/242/

**Comment by jrudolph** [comment] 2016-11-07 14:51
Duplicate of #299 ;)

**Closed by jrudolph** 2016-11-07 14:51 UTC

**Comment by rbudzko** [comment] 2016-11-07 14:52
Using issue search still too hard for me :(.
