### ISSUE TITLE
ArrayIndexOutOfBoundsException in HttpHeaderParser

### ISSUE THREAD

**Issue by gregbeech** [akka/akka-http#2001] opened 2018-04-30 13:42 UTC
This is a _terrible_ bug report because other than the exception itself I don't have the details of what caused this error and no reproducing case. We've seen it a couple of times in our production environment, likely as a result of people sending deliberately malformed header content.

I realise it's going to be very hard to investigate without a repro so feel free to close this, but thought I'd report it anyway.

```
java.lang.ArrayIndexOutOfBoundsException: 762
    at akka.http.impl.engine.parsing.HttpHeaderParser.parseHeaderValue(HttpHeaderParser.scala:194)
    at akka.http.impl.engine.parsing.HttpHeaderParser.parseHeaderLine(HttpHeaderParser.scala:130)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseHeaderLines(HttpMessageParser.scala:125)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseHeaderLines$(HttpMessageParser.scala:116)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseHeaderLines(HttpRequestParser.scala:43)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseMessage(HttpRequestParser.scala:76)
    at akka.http.impl.engine.parsing.HttpMessageParser.startNewMessage(HttpMessageParser.scala:100)
    at akka.http.impl.engine.parsing.HttpMessageParser.startNewMessage$(HttpMessageParser.scala:98)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.startNewMessage(HttpRequestParser.scala:43)
    at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$startNewMessage$1(HttpMessageParser.scala:101)
    at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$startNewMessage$1$adapted(HttpMessageParser.scala:101)
    at akka.http.impl.engine.parsing.HttpMessageParser.$anonfun$continue$2(HttpMessageParser.scala:265)
    at akka.http.impl.engine.parsing.HttpMessageParser.run$1(HttpMessageParser.scala:64)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseBytes(HttpMessageParser.scala:78)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseBytes$(HttpMessageParser.scala:62)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseBytes(HttpRequestParser.scala:43)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseSessionBytes(HttpMessageParser.scala:60)
    at akka.http.impl.engine.parsing.HttpMessageParser.parseSessionBytes$(HttpMessageParser.scala:55)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.parseSessionBytes(HttpRequestParser.scala:43)
    at akka.http.impl.engine.parsing.HttpRequestParser$$anon$1.onPush(HttpRequestParser.scala:54)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:411)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
    at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:469)
    at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:560)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:742)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:757)
    at akka.actor.Actor.aroundReceive(Actor.scala:517)
    at akka.actor.Actor.aroundReceive$(Actor.scala:515)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:667)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:590)
    at akka.actor.ActorCell.invoke(ActorCell.scala)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run$$original(Mailbox.scala:224)
    at akka.dispatch.Mailbox.run(Mailbox.scala:32)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by johanandren** [comment] 2018-04-30 13:57
Better this than nothing! Thanks for reporting.

**Comment by jrudolph** [comment] 2018-09-26 08:44
Closing as a duplicate of #1484 but really good to know that it seems to happen with a unique index (`762`).

**Closed by jrudolph** 2018-09-26 08:44 UTC
Labels: bug, t:server
