### ISSUE TITLE
ScalatestRouteTest ignores config setting "akka.http.server.remote-address-header"

### ISSUE THREAD

**Issue by NeuroNex** [akka/akka-http#923] opened 2017-03-03 00:33 UTC
Using akka-http 2.4.7: ScalatestRouteTest doesn't honor the configuration setting `akka.http.server.remote-address-header = on`. The `Remote-Address` header is not injected automatically in the request header bu akka-http engine. Is it bug or intentional design?

Detailed description and test code in: [akka-http does not add Remote-Address in request headers](http://stackoverflow.com/questions/42545243/akka-http-does-not-add-remote-address-in-request-headers)

**Comment by jrudolph** [comment] 2017-03-08 11:32
@NeuroNex thanks for the report. The akka-http-testkit doesn't actually use the engine but runs just the routing layer, therefore there's no engine to inject the header.

It might still sense to inject something just for testing if the header is configured. The question is mostly what to inject if there's no actual TCP connection. It could be added in `RouteTest.scala` where the `RequestContext` is built. (Same needs to be done for javadsl).

**Comment by ktoso** [comment] 2017-03-08 12:40
I once implemented a 

```scala
/** INTERNAL API - not (yet?) ready for public consuption */
private[akka] trait IntegrationRoutingSpec extends WordSpecLike with Matchers with BeforeAndAfterAll
```

which looks like the usual one but uses ~!> to signal that "hey, this will use a real server". We could consider polishing it up and releasing at some point perhaps.

If you're interested in that a contrib for it would be pretty nice I think. Just look for that class and it would need enough polish and docs to make it exposable to the general public (API should look the same as the normal spec)

**Comment by jonas** [comment] 2017-03-08 12:54
And there's even a ticket for that: #39

**Comment by ktoso** [comment] 2017-03-08 13:01
Ah right, closing this one as a duplicate of https://github.com/akka/akka-http/issues/39 then.
Thanks in advance for any community help in that.

**Closed by ktoso** 2017-03-08 13:01 UTC
Labels: 1 - triaged, community, t:server, t:testing

**Comment by ktoso** [comment] 2017-03-08 13:24
Right, sorry. Yes I think `a way to setup tests that run more layers` is a good idea to go about it.
