### ISSUE TITLE
dotnet-core 3.1 grpc client causes "Http2ServerDemux: handleOutgoingEnded received unexpectedly in state Closed"

### ISSUE THREAD

**Issue by laszlox** [akka/akka-http#2977] opened 2020-02-21 14:23 UTC
Hi,

I created a very simple, hello-world like akka-grpc server (akka 2.5.23, akka-http 10.1.11), supporting a single unary endpoint. If I call it from the akka-grpc client (or even nodejs), it works perfectly fine.

However calling from a very simple, vanilla dotnet-core 3.1 client fails about once every 5-10 tries, and akka-http logs:

```Http2ServerDemux: handleOutgoingEnded received unexpectedly in state Closed. This indicates a bug in Akka HTTP, please report it to the issue tracker. "```

The dotnet-core client gets:

```Error starting gRPC call: An error occurred while sending the request```

As far as I can see, my service endpoint implementation completes fine, the issue happens afterwards.

I noticed that the dotnet-core client sends different HTTP2 settings than the akka-grpc or nodejs one (e.g. it sends SETTINGS_HEADER_TABLE_SIZE(0) but it doesn't send SETTINGS_MAX_HEADER_LIST_SIZE(8192), SETTINGS_INITIAL_WINDOW_SIZE(1048576) and SETTINGS_MAX_CONCURRENT_STREAMS(0)).

I attached an example [akka-grpc server](https://github.com/akka/akka-http/files/4236433/akkagrpc-bug-server.tar.gz) and [dotnet core client](https://github.com/akka/akka-http/files/4236438/akkagrpc-bug-client.tar.gz) project.

To run the server: ```sbt run```

To run the client
- install dotnet-core 3.1: https://docs.microsoft.com/en-gb/dotnet/core/install/sdk?pivots=os-linux#download-and-manually-install
- then ```dotnet run```. After about 5-10 runs, it fails with this error.

akka-http DEBUG logs:

```
[info] 2020-02-21 13:48:57,979 [13:48:57.979UTC] [DEBUG] TcpListener: New connection accepted 
[info] 2020-02-21 13:48:57,994 [13:48:57.994UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForNetworkToSendControlFrames 
[info] 2020-02-21 13:48:57,994 [13:48:57.994UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForNetworkToSendControlFrames to Idle 
[info] 2020-02-21 13:48:57,995 [13:48:57.995UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:57,995 [13:48:57.995UTC] [DEBUG] Http2ServerDemux: Got 2 settings! 
[info] 2020-02-21 13:48:57,996 [13:48:57.995UTC] [DEBUG] Http2ServerDemux: Ignoring setting SETTINGS_ENABLE_PUSH -> 0 (in Demux) 
[info] 2020-02-21 13:48:58,007 [13:48:58.007UTC] [DEBUG] Http2ServerDemux: Ignoring setting SETTINGS_HEADER_TABLE_SIZE -> 0 (in Demux) 
[info] 2020-02-21 13:48:58,008 [13:48:58.007UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,008 [13:48:58.007UTC] [DEBUG] HeaderCompression$$anon$1: Applied SETTINGS_HEADER_TABLE_SIZE(0) in header compression 
[info] 2020-02-21 13:48:58,008 [13:48:58.007UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,008 [13:48:58.008UTC] [DEBUG] Http2ServerDemux: Updating outgoing connection window by 67043329 to 67108864 
[info] 2020-02-21 13:48:58,008 [13:48:58.008UTC] [DEBUG] Http2ServerDemux: Got unhandled event SettingsAckFrame(List()) 
[info] 2020-02-21 13:48:58,011 [13:48:58.011UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,012 [13:48:58.011UTC] [DEBUG] Http2ServerDemux: Received DATA 5 for stream [1], remaining window space now 65530, buffered: 5 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: Received DATA 6 for stream [1], remaining window space now 65524, buffered: 11 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: Dispatched chunk of 11 for stream [1], remaining window space now 65524, buffered: 0 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: adjusting con-level window by 0, stream-level window by 446476, remaining window space now 512000, buffered: 0, remaining connection window space now 9999989, total buffered: 0 
[info] 2020-02-21 13:48:58,012 [13:48:58.012UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,012 [               ] [INFO ] TestGrpcServiceImpl: get(Input(hey!)) -> Output(hey! hey!) 
[info] 2020-02-21 13:48:58,013 [13:48:58.013UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,013 [13:48:58.013UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,014 [13:48:58.013UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,014 [13:48:58.014UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,016 [13:48:58.016UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,017 [13:48:58.017UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,017 [13:48:58.017UTC] [DEBUG] Http2ServerDemux: [1] buffered 33 bytes 
[info] 2020-02-21 13:48:58,017 [13:48:58.017UTC] [DEBUG] Http2ServerDemux: [1] sending 33 bytes, endStream = false, remaining buffer [0], remaining stream-level WINDOW [65502] 
[info] 2020-02-21 13:48:58,017 [13:48:58.017UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,018 [13:48:58.017UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[info] 2020-02-21 13:48:58,018 [13:48:58.018UTC] [DEBUG] Http2ServerDemux: [1] buffered 0 bytes 
[info] 2020-02-21 13:48:58,020 [13:48:58.019UTC] [WARN ] Http2ServerDemux: handleOutgoingEnded received unexpectedly in state Closed. This indicates a bug in Akka HTTP, please report it to the issue tracker. 
[info] 2020-02-21 13:48:58,020 [13:48:58.019UTC] [DEBUG] Http2ServerDemux: Changing state from WaitingForData to Idle 
[info] 2020-02-21 13:48:58,020 [13:48:58.019UTC] [DEBUG] Http2ServerDemux: Changing state from Idle to WaitingForData 
[error] 2020-02-21 13:48:58,020 [13:48:58.019UTC] [WARN ] Http2ServerDemux: handleOutgoingEnded received unexpectedly in state Closed. This indicates a bug in Akka HTTP, please report it to the issue tracker. 
```

Thanks for any help!

**Comment by raboof** [comment] 2020-02-25 17:04
I can run your test projects, but no matter how often I `dotnet run` I never see the error :(. Do you have some other way to stress it?

**Comment by laszlox** [comment] 2020-02-26 11:33
It's interesting: I can reproduce the problem on various machines (windows, redhat) at my workplace, but I couldn't reproduce it at home (windows, ubuntu). I also tried another redhat box in the office is a more vanilla build, and it happens there too.

I'll try to come up with a more stable reproduction...

Anyway, thanks for looking into it!

**Comment by jrudolph** [comment] 2020-04-06 10:42
Let's close it for now. If you can reproduce please request to reopen.

**Closed by jrudolph** 2020-04-06 10:42 UTC
Labels: 0 - new

**Comment by raboof** [comment] 2020-04-06 10:59
This might have been a duplicate of #2957 - if so then it should now be fixed!

**Comment by laszlox** [comment] 2020-04-06 11:06
Thanks, I'll ugprade and check!

**Comment by jrudolph** [comment] 2020-04-06 11:38
Good point. That version is so far only released as a nightly snapshot. You can try this version: https://bintray.com/akka/snapshots/akka-http/0.0.0%2B104-4387f72e

(Something is at odds with the version numbering, I checked that this is the latest one).
