### ISSUE TITLE
Exception Handling with ServerSentEvents (SSE)

### ISSUE THREAD

**Issue by Dollyg** [akka/akka-http#2578] opened 2019-06-26 15:42 UTC
When I try to `complete` an HttpRequest with a `Source` created from a failed future, it does not invoke the `ExceptionHandlers`.

These are my routes:
```
import akka.http.scaladsl.marshalling.sse.EventStreamMarshalling._
import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.{ExceptionHandler, Route}
import akka.stream.scaladsl.Source
import csw.commons.http.JsonSupport

import scala.concurrent.{Future, TimeoutException}

object Routes {

  implicit def handlers: ExceptionHandler = ExceptionHandler {
    case ex: TimeoutException ⇒
      complete(JsonSupport.asJsonResponse(StatusCodes.GatewayTimeout, ex.getMessage))
  }

  def route: Route =
    handleExceptions(handlers) {
      get {
        path("example") {
          complete(Source.fromFuture {
            Future.failed(new TimeoutException())
          })
        }
      }
    }
}
```

Here is a small test setup to reproduce the problem.
```
import akka.http.scaladsl.model.StatusCodes
import akka.http.scaladsl.testkit.ScalatestRouteTest
import org.scalatest.{Matchers, WordSpec}

class RoutesTest extends WordSpec with Matchers with ScalatestRouteTest {

  "Routes for command/assembly" must {
    "example route" in {
      Get("/example") ~> Routes.route ~> check {
        status shouldBe StatusCodes.GatewayTimeout
      }
    }
  }
}
```

I get the following exception on running the test:
```
java.lang.RuntimeException: Trying to await result of failed Future, see the cause for the original problem.
```

However, running the server and sending a client request from a Main App returns Status 200 OK.

**Comment by raboof** [comment] 2019-06-26 23:05
Thanks for your question and reproducer! I converted it to an actually runnable project at https://github.com/raboof/akka-http-2578

I'm not entirely sure this is a bug: what you are returning is a Source that fails immediately. So returning a `200 OK` might be fine: we successfully returned a `Source`. However, that source failed: indeed, the HTTP connection is closed with a RST:

```
$ curl -v localhost:8080/example
(...)
> GET /example HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: akka-http/10.1.8
< Date: Wed, 26 Jun 2019 22:25:13 GMT
< Transfer-Encoding: chunked
< Content-Type: text/event-stream
<
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I agree it is weird the test is failing with this exception, though, instead of also returning the 200 and a failed response entity. Right now RouteTestResultComponent:entityCreator awaits all elements. I suppose it would make sense to return a response with a failed entity in that case. I split that out into its own issue at #2579.

Your `handler` suggests you would like to register a hander for when the response times out. With a streaming response, this might not be possible: if the response has already started streaming (because a Source was found), even if it could detect the entity streaming failure the handler could not 'rewind' the response and replace it with another one.

Of course your minimal reproducer is a reduced version of your production code. If your response is a 2-step process, where initialization might fail, perhaps it might make sense to wrap the initialization of the response in an `onSuccess` directive so you can handle an initialization handler in the way you seem to intend. I created an example of this at https://github.com/raboof/akka-http-2578/compare/splitFutureAndSource .

Is that what you were looking for?

This seems to mostly work as designed. Since we use the GitHub issue tracker for bugs and feature requests rather than discussion, I'll close this issue for now. If you want to continue to discuss various approaches, https://discuss.akka.io might be a more suitable place. If you think there is a bug or feature request here, feel free to reopen the issue with more details.

**Closed by raboof** 2019-06-26 23:05 UTC

**Comment by raboof** [comment] 2019-06-27 15:08
Glad to hear it!
