### ISSUE TITLE
Akka Http.get(ActorSystem) irritates IDEA

### ISSUE THREAD

**Issue by GHogChi** [akka/akka-http#1296] opened 2017-07-21 15:53 UTC
Working in Java with akka-http-core_2.12:10.09, my invocations of Http.get(ActorSystem) are flagged as "Ambiguous method call".  

When IDEA decompiles the Http class, the problem is apparent:
```java
    public static Http get(ActorSystem var0) {
        return Http$.MODULE$.get(var0);
    }

    public static Extension get(ActorSystem var0) {
        return Http$.MODULE$.get(var0);
    }
```

My guess, having only a superficial knowledge of this stuff, is that overloads differing only in return type are illegal in Java source code for good reason: if you invoke a method and ignore the return, there's no way for the compiler/linkerish thingy to know which overload is intended. But it's apparently not illegal in class files, which I guess are generated from Scala code.

In this particular case it doesn't matter at runtime because both overloads have the same body. Being too lazy to dig deeper, I'm figuring **Http** and **Extension** are in a superclass/subclass relationship.

This is why I say it only irritates IDEA.  We can live with it.

(Thanks to Johan Andrén for steering me away from the closed thread I tried to piggyback this on.)

**Comment by jrudolph** [comment] 2017-07-25 13:44
Hi @GHogChi, can you post a screenshot? I looked in our Java test code and that isn't flagged? What IntelliJ version do you use?

**Comment by GHogChi** [comment] 2017-07-25 14:45
Johannes - glad to oblige:

We're using Community Edition 2017.2 (we're a skunkworks - trying to get the bureaucracy to approve Ultimate).

![akka http get problem 7-25-2017 9-36-30 am](https://user-images.githubusercontent.com/161585/28577869-946c69f0-711d-11e7-921e-28884aa65b4f.png)

**Comment by ktoso** [comment] 2017-07-25 15:28
It could be a regression in IntelliJ rather than something in Akka to be honest.
2017.1 works fine:

<img width="786" alt="httpapp_java_-_akka_-____code_akka_" src="https://user-images.githubusercontent.com/120979/28579971-1bc9cf48-7199-11e7-8873-21e223bc0001.png">

And we do explicitly do the override: `override def get(system: ActorSystem): Http = super.get(system)` since otherwise Java indeed has trouble with ambiguity of types.

I propose to open a ticket on the intellij issue tracker?
https://youtrack.jetbrains.com/issues/IDEA

**Comment by ktoso** [comment] 2017-07-25 15:28
(I don't think it would have anything to do with this one being ultimate, the language things are not locked down for the community version)

**Comment by ktoso** [comment] 2017-07-25 15:29
Oh wait! It could be because Scala 2.12 hm... We should check that.

**Comment by jrudolph** [comment] 2017-07-25 15:42
This looks suspicious but actually the class file is correct. This is a case of a [covariant return type](https://blogs.oracle.com/sundararajan/covariant-return-types-in-java). It will work because `Http extends Extension`, in that case javac will choose the overload with the more specific return type (which is possible because of the inheritance graph). I would suggest you file an issue in IntelliJ to investigate this issue. I don't think there's anything here we could improve.

**Comment by jrudolph** [comment] 2017-07-25 15:44
fwiw here's a Java example that compiles just fine showcasing the behavior of javac:

```java
public class Test {
    static class A {}
    static class B extends A {}

    static class D {
        A get(int i) { return null; }
    }
    static class E extends D {
        B get(int i) { return null; }
    }

    static int X() {
        E e = null;
        e.get(42);
        return 12;
    }
}
```

**Comment by GHogChi** [comment] 2017-07-25 19:46
Posted in Jetbrains forum: https://youtrack.jetbrains.com/issue/IDEA-176605 - danke, Johannes.

**Comment by ktoso** [comment] 2017-07-26 02:08
Thanks @GHogChi, I'll track that issue too then.
Closing this one for now as does not seem to be Akka itself at fault I think - we can reopen if there's anything to do.

**Closed by ktoso** 2017-07-26 02:08 UTC
Labels: 0 - new

**Comment by Weinschenk** [comment] 2018-01-12 13:26
I found a solution for the simple problem...

[https://stackoverflow.com/questions/48227225/akka-http-getactorsystem-leads-to-ambiguous-method-call-in-intellij/48227226#48227226](stackoverflow)
