### ISSUE TITLE
submit multiple files

### ISSUE THREAD

**Issue by fntz** [akka/akka-http#1048] opened 2017-04-24 13:17 UTC
hi,

i have the next route part:

```scala
val result = formData.parts.mapAsync[(String, Any)](1) {
  case file: BodyPart if file.name.contains(photo) =>
    println(s"${file.filename} --> ${file.entity.contentType.mediaType.isImage}")
    if (file.entity.contentType.mediaType.isImage) {
      val ext = file.entity.contentType
        .mediaType.fileExtensions
        .headOption.getOrElse(suffix)
      val tempFile = File.createTempFile(prefix, s".$ext")
      file.entity.dataBytes
        .runWith(FileIO.toPath(tempFile.toPath))
        .map { _ =>
          tempFile.getAbsolutePath -> 1
        }
        .recover {
          case x: Throwable =>
            log.warning(s"Failed to parse: $x")
            "error" -> 1
        }
    } else {
      log.info(s"Ignore file entity (not image): ${file.getName()}")
      Future.successful("ignore" -> 1)
    }


  case data: BodyPart =>
    data.toStrict(2.seconds).map { strict =>
      data.name -> strict.entity.data.utf8String
    }
}.runFold(Map.empty[String, Any])((map, tuple) => map + tuple)



result.onComplete {
  case Success(x) =>
    println(s"ok -> ${x}")
  case Failure(x) =>
    println(s"fail -> ${x.getMessage}")

}
```
Where i processing only image files.  It's works fine when i send from javascript only `jpg` files, or only `png`, but when i try to mix input files, i got error `Unexpected end of multipart entity`

I try to reproduce this issue with curl, but with curl it's only work with one file, but when i try to send 2 files (any jpg or png) i get the same error.

works fine:

```
curl -v -XPOST -H "Content-Type: multipart/form-data" -F "photo=@/home/user/Downloads/1.jpg"  'http://localhost:15000/api/v1/upload'

```

fail:

```
curl -v -XPOST -H "Content-Type: multipart/form-data" -F "photo=@/home/user/Downloads/1.jpg"   -F "photo1=@/home/user/Downloads/2.jpg" 'http://localhost:15000/api/v1/upload'
```

**Comment by jrudolph** [comment] 2017-04-24 14:55
I cannot reproduce this issue with your code (on current master). On which version of akka-http are you? Can you try to create a self-contained project that exhibits that problem?

**Comment by fntz** [comment] 2017-04-24 17:33
seems is my fault, sorry for inconvenience. all works fine.

**Comment by fntz** [comment] 2017-04-24 18:05
now i may reproduce it.

it works fine, when i handle form data in route class (`HttpRoute`), but the same code in Actor (`FormDataActor`) was not works correctly for 2 different files (png + pdf for example)

source: https://github.com/fntz/akka-http-form-data-example

run with `sbt run` 

and open `index.html` in browser.

**Comment by jrudolph** [comment] 2018-02-19 15:45
Seems we never got to check the reproducer and now the reproducer cannot be accessed anymore. I'm closing this for now. If this is still a problem with recent versions, please let us know!

**Closed by jrudolph** 2018-02-19 15:45 UTC
Labels: 0 - new
