### ISSUE TITLE
Dead letters with connection timeout on Http requests

### ISSUE THREAD

**Issue by KarelCemus** [akka/akka-http#2392] opened 2019-01-18 09:14 UTC
I am facing dead letters with outgoing HTTP requests and redefined (shorten) idle timeout on a connection.

I see:

```
2019-01-18 09:00:32.737 INFO    akka://default/system/IO-TCP/selectors/$a/0        Message [akka.io.TcpConnection$Unregistered$] from Actor[akka://default/system/IO-TCP/selectors/$a/0#131005314] to Actor[akka://default/system/IO-TCP/selectors/$a/0#131005314] was not delivered. [1] dead letters encountered. If this is not an expected behavior, then [Actor[akka://default/system/IO-TCP/selectors/$a/0#131005314]] may have terminated unexpectedly, This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

Here is a  minimal example to reproduce the issue. I reproduce it in 100% of cases.

```scala
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.HttpRequest
import akka.http.scaladsl.settings.ConnectionPoolSettings
import akka.stream.ActorMaterializer

import scala.concurrent.Future
import scala.concurrent.duration._
import scala.util.Success

object Application extends App {

  implicit val system = akka.actor.ActorSystem()
  implicit val mat = ActorMaterializer()(system)
  implicit val ec = system.dispatcher

  val settings = {
    val pool = ConnectionPoolSettings(system)
    pool.withConnectionSettings(
      pool.connectionSettings.withIdleTimeout(500.millis)
    )
  }

  val request = HttpRequest(uri = "https://www.google.com")

  Http().singleRequest(request, settings = settings).transformWith {
    case Success(response) =>
      response.discardEntityBytes().future()
    case _ =>
      Future.failed(new NotImplementedError())
  }

  // important keep the application running long enough
  // to see dead letters
  Thread.sleep(2000)

  system.terminate()
```

- Scala 2.12.8
- Java OpenJDK 64-Bit Server VM, Java 11.0.1
- Akka 2.5.19
- Akka HTTP 10.1.5
- possibly relates to #2391 but not sure, thus opened as a separate issue (I got no exception, only dead letters)

Not sure whether this is an issue of Akka stream or Akka HTTP.

**Comment by jrudolph** [comment] 2019-01-29 13:16
That's probably a harmless race condition while closing a connection.

I filed an issue to fix it in akka directly here: https://github.com/akka/akka/issues/26300.

**Comment by jrudolph** [comment] 2019-07-30 11:46
Closing as a duplicate of akka/akka#26300. Please check if it still happens after updating to at least Akka 2.5.22.

**Closed by jrudolph** 2019-07-30 11:46 UTC
