### ISSUE TITLE
Add OSGi manifest headers to bundle

### ISSUE THREAD

**Issue by michael-smith** [akka/akka-http#574] opened 2016-11-22 15:01 UTC
Both akka and spray support OSGi so it would be nice if the akka-http builds also included the bundle headers.

**Comment by ktoso** [comment] 2016-11-22 15:15
Would you offer validating once we add the configurations back?
We don't actively use OSGi so help in validating it's set up correctly would be welcome.

**Comment by michael-smith** [comment] 2016-11-22 15:16
No problem, thank you.

**Comment by michael-smith** [comment] 2017-02-21 18:50
Is there any update on when this might be available?

**Comment by collymy** [comment] 2017-03-01 17:14
I would be happy to validate an OSGI version of HTTP as I can't upgrade to Akka Http 10 until I get an OSGI version which means my project is currently stuck at Akka 2.4.11.

**Comment by ktoso** [comment] 2017-03-01 17:16
Would you be able to contribute some of the work needed to do?
It's currently not a priority for us (we need to focus on http/2 and play support).

**Comment by collymy** [comment] 2017-03-01 17:25
Hi,
I don't know a great deal about the build system for Akka but I do know quite a bit about the OSGI side of things. If somebody could add the basics to the Akka Http build system I would be happy to clone it and try to produce OSGI versions of the of the jars and submit back a pull request. I would need some hand holding as I have never contributed to a project before but I don't imagine it would take much as I am an experienced Scala and Java developer.
Colly

**Comment by jrudolph** [comment] 2017-03-02 10:42
The problem is that there currently is no working pipeline that would allow someone to maintain osgi metadata without much hassle. In the past, support for osgi has broken several releases because the sbt plugins deleted files from jar files etc. Unfortunately, so far, trying to support osgi was a net negative because it harmed us more than it helped for the small number of people who cared.

I guess as with every other packaging solution (deb, rpm, ...) there is also a way for osgi to create package for upstream modules without having to include packaging metadata into the upstream source code. This package could then be maintained outside of this module by people who actually care for osgi support and know what needs to be done to make it work. Could that be a solution?

**Comment by collymy** [comment] 2017-03-02 12:00
I don't know. If it is a solution then why can't Akka Http provide that solution as a separate task under SBT to produce the OSGI bundle.

**Comment by mpilquist** [comment] 2017-03-02 14:08
In my experience, the cost of maintaining OSGi versions of JARs separately from the main project is prohibitive and error prone. Additionally, it leads to classpath / dependency management problems, requiring exclusions and other nastiness. 

Having contributed OSGi support to a large number of projects and maintaining OSGi support in all my open source Scala projects, I feel comfortable saying that the total cost of including OSGi support in the upstream repository is minimal. Errors certainly occur, especially if there's a lot of dynamic classloading or optional dependencies, but they are relatively rare.

I understand that OSGi isn't a priority for the Akka team. If the community puts a PR together, what are the chances it is merged?

**Comment by ktoso** [comment] 2017-03-02 14:09
> I understand that OSGi isn't a priority for the Akka team. If the community puts a PR together, what are the chances it is merged?

Yes, I think we should not hinder adoption. Help would be very welcome, thanks in advance.

**Comment by jrudolph** [comment] 2017-03-10 10:03
Thanks for your input, @mpilquist. I hope I wasn't too harsh, my OSGi expierences have often been frustrating. I agree with Konrad that we shouldn't hinder adoption so we will accept help if the burden isn't on us to maintain OSGi metadata. And the bug in the sbt osgi plugin should be fixed before which deletes files from packages if OSGi metadata is wrong.

**Closed** 2017-04-07 16:35 UTC
Labels: 1 - triaged, community

**Comment by ktoso** [comment] 2017-04-07 16:37
Done, the next release should include the manifest metadata!
We should make sure to not ship it dead on arrival so let's sanity check that at least non osgi users were not impacted, but I hope it'll be all good.

**Comment by collymy** [comment] 2017-06-21 16:17
Hi,

I have just upgraded to 10.0.7 and I can report that the OSGI headers worked fine for me.

Thanks very much for your support.
