### ISSUE TITLE
Failed: FutureDirectivesExamplesTest

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2576] opened 2019-06-24 07:29 UTC
https://jenkins.akka.io:8498/job/akka-http-nightly/527/AKKA_VERSION=master,Node=akka-http-nightly-node,SCALA_VERSION=2.13.0,jdk=AdoptOpenJDK%2011/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

```
java.lang.AssertionError: Unexpected entity! expected:<[The server is currently unavailable (because it is overloaded or down for maintenance).]> but was:<[An error occurred: java.lang.ArithmeticException: / by zero]>
  Request was:      HttpRequest(HttpMethod(GET),/divide/10/0,List(),HttpEntity.Strict(none/none,ByteString()),HttpProtocol(HTTP/1.1))
  Route result was: Future(Success(Complete(HttpResponse(500 Internal Server Error,List(),HttpEntity.Strict(text/plain; charset=UTF-8,An error occurred: java.lang.ArithmeticException: / by zero),HttpProtocol(HTTP/1.1)))))

	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.reportDetails(JUnitRouteTest.scala:47)
	at akka.http.javadsl.testkit.JUnitRouteTestBase$$anon$1.assertEquals(JUnitRouteTest.scala:30)
	at akka.http.javadsl.testkit.TestRouteResult.assertEqualsKind(TestRouteResult.scala:227)
```

**Comment by jrudolph** [comment] 2019-08-27 08:36
Failed again on the release-2.5 branch this time: https://jenkins.akka.io:8498/job/akka-http-nightly/596/

**Comment by jrudolph** [comment] 2020-02-05 15:51
https://jenkins.akka.io:8498/job/akka-http-nightly/6/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.13.1,jdk=AdoptOpenJDK%208/testReport/junit/docs.http.javadsl.server.directives/FutureDirectivesExamplesTest/testOnCompleteWithBreaker/

**Comment by ignasi35** [comment] 2020-03-15 19:19
Duplicate of #2952

**Closed by ignasi35** 2020-03-15 19:19 UTC
Labels: failed
