### ISSUE TITLE
toStrictEntity with chunked multipart/form-data

### ISSUE THREAD

**Issue by radekg** [akka/akka-http#2213] opened 2018-09-18 12:45 UTC
Akka HTTP version: 10.1.5

I have the following route in my application:

```
private val formFieldWithUploadedFile = formFieldMap & fileUpload(config.http.fileDataField)
post {
  formFieldWithUploadedFile {
    case (formFields, (metadata, byteSource)) ⇒
      // ...
  }
}
```

When using a standard Akka HTTP client multipart upload, my request details are as follows (debug output from my program):

```
Request headers:    List(Tls-Session-Info: [Session-1, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256], Host: localhost:51299, User-Agent: akka-http/10.1.5, Timeout-Access: <function1>)
Content type:       multipart/form-data; boundary=FrHH-NXT5Vgdj31OWC64JaEB
Content length:     Some(104857774)
Is chunked:         false
Is close delimited: false
```

And this works absolutely fine.

The problematic scenario is, however, triggered when using `play-ws` standalone client. `play-ws` uses chunking for `multipart/form-data`, details of the request:

```
Request headers:    List(Tls-Session-Info: [Session-1, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256], Host: localhost:51374, Accept: */*, User-Agent: AHC/2.0, Timeout-Access: <function1>)
Content type:       multipart/form-data; boundary=GI913h7oYmEfKnm08K
Content length:     None
Is chunked:         true
Is close delimited: false
```

This request fails internally for my route with the following message: `java.lang.IllegalStateException: Substream Source cannot be materialized more than once`. According to https://github.com/akka/akka-http/issues/745, the solution is to wrap the route in `toStrictEntity(timeout)`. However, from the [scaladoc](https://github.com/akka/akka-http/blob/d0cee31292c893994141cc36f772e5c90828c341/akka-http/src/main/scala/akka/http/javadsl/server/directives/BasicDirectives.scala#L322):

```
WARNING: This will read the entire request entity into memory and effectively disable streaming.
```

This has serious implications when one needs to handle large files (1GB, maybe more).

Is there a way to avoid `toStrictEntity` for chunked uploads? I did already ask on the gitter channel (https://gitter.im/akka/akka?at=5ba0e8fdfcba1254fad31816). The suggestion was that it might, indeed, be an Akka HTTP problem as neither chunked and non-chunked would not know the multipart boundaries ahead of time.

Any ideas how to handle such scenarios?

**Comment by jrudolph** [comment] 2018-09-18 14:09
Hi @radekg, thanks for the report. The problem is that `formFieldMap` and `fileUpload` currently only work together for strict entities.

`fileUpload` alone works for streaming data, but any of the `formField*` directives will load the whole request into memory anyway.

Basically, #73 already describes the situation quite accurately.

A workaround is to start from the source code of the `fileUpload` directive but handle all parts of the multipart entity in a streaming fashion.

**Comment by jrudolph** [comment] 2018-09-18 14:10
I'm closing this as a duplicate of #73 (explicitly not because it is not a valid issue). Definitely good to keep this particular use case in mind when implementing a solution.

**Closed by jrudolph** 2018-09-18 14:10 UTC

**Comment by radekg** [comment] 2018-09-18 14:30
Thank you for the pointer, @jrudolph. By the way, maybe it would be beneficial to mention this in the [documentation](
https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/basic-directives/extractStrictEntity.html)?
