### ISSUE TITLE
StackOverflowError when using Future.foldLeft on FastFutures

### ISSUE THREAD

**Issue by dclements** [akka/akka-http#2003] opened 2018-04-30 20:50 UTC
akka-http: 10.0.13
akka: 2.5.11 (with akka-slf4j and akka-stream loaded at the same version)
scala: 2.12.5
jvm: Java 8, OpenJDK, 25.131-b11

This is the test case that seems to consistently reproduce the problem for me:

```
object FoldExceptionTest extends App {
  import scala.concurrent.ExecutionContext.Implicits.global


      val k = Range(1, 3000).map {
        y =>
          FastFuture(Try("test" + y))
      } 

      val s = Future.foldLeft(k)("") {
        (c, y) =>
          c + y
      }

  println(Await.result(s, Duration.Inf))
}
```

This code will consistently throw a stackoverflow exception that looks something like the following:

```
<some preamble>
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:42)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:302)
	at scala.concurrent.Future.flatMap$(Future.scala:302)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
	at scala.concurrent.Future$.$anonfun$foldNext$1(Future.scala:765)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:303)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$transformWith$1(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension0(FastFuture.scala:37)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.transformWith(FastFuture.scala:86)
	at scala.concurrent.Future.flatMap(Future.scala:302)
	at scala.concurrent.Future.flatMap$(Future.scala:302)
	at akka.http.scaladsl.util.FastFuture$FulfilledFuture.flatMap(FastFuture.scala:77)
(etc etc etc, repeats)
```

(The preamble varies depending on the surrounding context of the execution). 

If, instead of `3000` I use `10`, however, it works fine.  It also works fine if instead of using `Future.foldLeft` I use `FastFuture.fold`. It also works if I create the futures using `Future.fromTry` instead of `FastFuture.apply`.

**Comment by johanandren** [comment] 2018-05-02 08:53
I think it is somewhat unfortunate this is not marked internal API. In general if the futures are all completed already, the `FastFuture` is not stack safe (by design).

**Comment by johanandren** [comment] 2018-06-04 08:19
Closing this as there was no further discussion and this is "just how FastFuture works" - it is not a general purpose replacement for regular futures it is an optimization that can be used in some places where you are in control of what is going on.

**Closed by johanandren** 2018-06-04 08:19 UTC
Labels: 0 - new, t:core
