### ISSUE TITLE
java.lang.AbstractMethodError when using Akka HTTP with Akka 2.6.0 M7

### ISSUE THREAD

**Issue by fvyaba** [akka/akka-http#2720] opened 2019-09-18 17:06 UTC
I'm using akka-http(java:oracle jdk1.8.0_202, os: macos), just found 'java.lang.AbstractMethodError'.
- pom.xml(just fragement),listed below:
```
        <properties>
		<scala.version>2.13</scala.version>
		<akka-core.version>2.6.0-M7</akka-core.version>
		<akka-http.version>10.1.9</akka-http.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-actor_${scala.version}</artifactId>
			<version>${akka-core.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-stream_${scala.version}</artifactId>
			<version>${akka-core.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-http_${scala.version}</artifactId>
			<version>${akka-http.version}</version>
		</dependency>
	</dependencies>
```
- test code(using http-client api):
```
import java.util.concurrent.CompletionStage;

import akka.actor.ActorSystem;
import akka.http.javadsl.Http;
import akka.http.javadsl.model.HttpRequest;
import akka.http.javadsl.model.HttpResponse;

public class HttpActorClient {
  public static void main(String[] args) {
    final ActorSystem system = ActorSystem.create();
    final CompletionStage<HttpResponse> responseFuture = Http.get(system)
        .singleRequest(HttpRequest.create("https://akka.io"));
    responseFuture.whenComplete((r, e)->{
      System.out.println(r);
    });
  }
}
```
- err stack trace
```
Detected java.lang.NoSuchMethodError error, which MAY be caused by incompatible Akka versions on the classpath. Please note that a given Akka version MUST be the same across all modules of Akka that you are using, e.g. if you use akka-actor [2.6.0-M7 (resolved from current classpath)] all other core Akka modules MUST be of the same version. External projects like Alpakka, Persistence plugins or Akka HTTP etc. have their own version numbers - please make sure you're using a compatible set of libraries.                 
Uncaught error from thread [default-akka.actor.default-dispatcher-4]: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.NoSuchMethodError: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;
	at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:75)
	at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
	at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
	at akka.actor.Props.newActor(Props.scala:212)
	at akka.actor.ActorCell.newActor(ActorCell.scala:609)
	at akka.actor.ActorCell.create(ActorCell.scala:635)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
	at akka.dispatch.Mailbox.run(Mailbox.scala:229)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by johanandren** [comment] 2019-09-19 07:07
Duplicate of #2690 fixed in the (upcoming) next release of Akka HTTP

**Closed by johanandren** 2019-09-19 07:07 UTC
