### ISSUE TITLE
Cancelling requests from client connection pools with a timeout

### ISSUE THREAD

**Issue by vigoo** [akka/akka-http#1205] opened 2017-06-16 15:42 UTC
Putting a timeout for each request can be very important in cases where the server we are calling responds very slowly occasionally (for example on its error paths because of some wrongly configured timeouts on that side - but let's assume we can't control the server we are talking to). 

I was trying to find a way to achieve this while using the *host connection pool* without much success. I uploaded the latest one of the failed attempts with a test server as well to https://github.com/vigoo/akka-http-client-cancellation.

Digging more into how the library works I realized I can implement this if I'm directly creating outgoing connections like in the following simplified example:

```scala
val connectionFlow = Http()
       .outgoingConnection(request.uri.authority.host.toString(), request.uri.effectivePort)

val responseFuture = Source
      .single(request)
      .via(connectionFlow)
      .idleTimeout(timeout)
      .runWith(Sink.head)
```
but to use it in production I'd have to build my custom connection pool around it which I'd like to avoid if possible.

So I checked the connection pool implementation and added a similar timeout to the connection flow in `PoolSlot`, tried it out and it works find in the use case I described. Here is this initial implementation:
https://github.com/vigoo/akka-http/commit/e2559cba62f46cabb78f8c7cbc7617ab197c4d8f

If this is something we could add to the library, I'm happy to work on it more and make it a proper PR. Otherwise please give me advice on how else could I solve this issue.

**Comment by jrudolph** [comment] 2017-07-24 11:44
Hi @vigoo, thanks for the report (and sorry for keeping unanswered for so long). 

IIUC, in that form the feature shouldn't necessary at all because there already is an idle-timeout active for client connections. However, due to a bug that idle-timeout will not free the slot for further requests if you don't read the response entity (see #1248). Could that be the case here?

Apart from that, there are a few other issues around client-side timeouts that haven't been solved yet:
 * a request-timeout should also prune requests from the queue #42 
 * there are several kinds of timeouts: an idle-timeout that only triggers if a connection is completely idle, a request-timeout that spans the whole time from submitting the request to receiving the last byte of the response, a timeout between submitting a request and receiving the first byte of the response, it hasn't been decided which to support (idle-timeout is already supported)
 * there are several ways to deal with any of those timeouts: cancel the connection or keep using the connection (though cancelling would probably be the faster and more reliable solution even if it reset the TCP state)

**Comment by jrudolph** [comment] 2017-07-24 12:02
Ah, I see your idle-timeout is on the `Flow[HttpResponse, HttpRequest]` level. So, that would be "a timeout between submitting a request and receiving the first byte of the response". However, it seems that your implementation might be too simple because the `idleTimeout` will already start to run when the headers of the previous response was received. After that, time will pass until the previous response entity was read and the connection might really be idle for a while until the request gets submitted that you are interested in. Only at that point the timer should be started.

**Comment by vigoo** [comment] 2017-07-24 13:14
So, I tried to look into all the things you mentioned.

- I believe #1248 is a different issue, in our case the server is simply not responding anything within the given time interval, so there is not response entity to be consumed.
- I may be misunderstanding the code but I think the idle timeout is reset every time a new request is sent to a pool, and when it triggers, the enqueued requests are resent to the gateway but the ongoing one is not cancelled. If this is the case, I think it wouldn't solve this particular problem (that is described in https://github.com/vigoo/akka-http-client-cancellation/blob/master/README.md)
- I believe the proper solution for the issue would be the introduction of a request timeout that you described, and what is discussed in #42 too. The timeout from the submitting the request until the first byte received accidentally solves my problem, but I feel like it is a too special case and the full request timeout is a better and more fundamental feature to be supported.
- Thanks for point out that my solution is not the request timeout I thought it is. As I mentioned in the previous paragraph, it solves the "demo" problem (and actually it would solve our production problem as well, because it is the 'other service is not replying at all for minutes' scenario), but the real, end-to-end request timeout would be preferable.

Should I try to implement the real request timeout or is it something that somebody is already working on? If I should try, are there any general ideas about how to solve this? Or is there any other way to solve the issue without implementing this feature?

**Comment by jrudolph** [comment] 2017-07-26 09:44
> I may be misunderstanding the code but I think the idle timeout is reset every time a new request is sent to a pool, and when it triggers, the enqueued requests are resent to the gateway but the ongoing one is not cancelled.

As [discussed on gitter](https://gitter.im/akka/dev?at=59785a242723db8d5e4a259a) there seems to be a confusion between two different kinds of idle timeouts that akka-http provides:
 * `akka.http.host.connection-pool.idle-timeout`: the idle timeout of a pool of connections to a host, it triggers if a pool has seen no activity for the amount of time and will shut down the pool with all of its potentially idle connections after that time (mostly useful if you connect to lots of different hosts and don't want to keep pools to all of those hosts around forever)
 * `akka.http.client.idle-timeout` and `akka.http.host-connection-pool.client.idle-timeout`: the per-connection idle-timeout which triggers when no bytes were sent on a connection for some time, that's what you should use to make sure that connection are not kept hanging for an infinite amount of time. An idempotent request that runs into such an idle-timeout is retried for `akka.http.host-connection-pool.max-retries` times. By default this idle-timeout is set to 60 seconds and max-retries is set to 5, so a request that deterministically hangs every time will only be cleared from its pool slot after 5 minutes.

**Comment by ylazzari** [comment] 2017-07-26 10:50
@jrudolph Sorry for chiming in, but after reading your latest comments and what you guys discussed on gitter, it made it a lot clearer; also knowing that prior to 10.0.9, programatically setting the idle-timeout did not work. That would explain why none of my tests were working! I think reworking the documentation on that subject would help, with small use cases and code samples; a bit like you did on gitter, to show how the different settings work together and how different combinations can be set to achieve different results (e.g. what combinations of max-retries and idle-timeout allow you to achieve an absolute timeout) . I might be wrong but there seems to have been many questions and issues opened around that topic and improved documentation could go a long way. Thanks!

**Comment by Tvaroh** [comment] 2018-08-16 00:45
> However, due to a bug that idle-timeout will not free the slot for further requests if you don't read the response entity (see #1248).

@jrudolph What if response entity is infinite? Does it mean that there is no way to cancel the connection and it'll stay forever?

**Comment by jrudolph** [comment] 2020-02-06 12:44
Let's close this as a duplicate of #42.

**Closed by jrudolph** 2020-02-06 12:44 UTC
Labels: 0 - new
