### ISSUE TITLE
Websocket and not completed Future

### ISSUE THREAD

**Issue by hanny24** [akka/akka-http#1823] opened 2018-01-29 15:17 UTC
In case of failure while making initial websocket request (SocketTimeout, SSLHandshakeException...) I would expect Future[WebsocketUpgradeResponse] to be failed. But it is never completed instead. It appreas to be related to TLS. Minimal working example:
```scala
import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model.ws.{Message, WebSocketRequest}
import akka.stream.ActorMaterializer
import akka.stream.scaladsl.Flow

import scala.concurrent.Await
import scala.concurrent.duration._

object Bug extends App {
  implicit val actorSystem = ActorSystem()
  implicit val actorMaterializer = ActorMaterializer()

  val (upgradeResponse, _) = Http().singleWebSocketRequest(WebSocketRequest("ws://bad-bad-url"), Flow[Message])
  try {
    Await.result(upgradeResponse, 5.seconds)
  }
  catch {
    case _: RuntimeException => // OK, expected
    case other => throw new Exception("bug", other)
  }
  val (upgradeResponseBad, _) = Http().singleWebSocketRequest(WebSocketRequest("wss://bad-bad-url"), Flow[Message])
  try {
    Await.result(upgradeResponseBad, 5.seconds)
  }
  catch {
    case _: RuntimeException => // OK, expected
    case other => throw new Exception("bug2", other)
  }

}

```
It throws an exception with "bug2".

Akka HTTP version: 10.0.11

**Comment by doalex** [comment] 2018-02-11 00:04
This issue is probably related to #793 ?

**Comment by jrudolph** [comment] 2018-10-30 10:57
Yep, let's treat it as a duplicate of #793.

**Closed by jrudolph** 2018-10-30 10:57 UTC
Labels: 0 - new, t:websocket
