### ISSUE TITLE
Make `Sec-WebSocket-Protocol` header non-private

### ISSUE THREAD

**Issue by pjan** [akka/akka-http#608] opened 2016-12-03 00:19 UTC
The existing machinery to customize Rejection Handling requires a lot of boilerplate. We created a wrapper around, which only requires the creation of a `ToResponseMarshaller` for an `ErrorMessage` type.

In order to make it a complete alternative for the default `RejectionHandler` of `akka-http`, and not put it in the `akka.http` namespace (before potentially opensourcing it), we need access to the currently private ` Sec-WebSocket-Protocol` header.

Alternative is to put everything in the `akka.http.contrib` namespace, but would similarly like to receive input from the community / maintainers on how they feel about this.

**Comment by jonas** [comment] 2017-01-15 01:45
Closing this as a duplicate of #137. The discussion there has more details why it was defined as private a

**Closed by jonas** 2017-01-15 01:45 UTC

**Comment by jonas** [comment] 2017-01-15 01:47
There you'll also find more info in case you want to submit a PR to make it public.
