### ISSUE TITLE
headerValueByType is case-sensitive

### ISSUE THREAD

**Issue by rusho** [akka/akka-http#2435] opened 2019-02-22 16:43 UTC
As it appears, `headerValueByType` directive (as well as `optionalHeaderValueByType`) performs case-sensitive match for the headers. Eg. if I do:

```
(path("test") & post & optionalHeaderValueByType[`User-Agent`](()) ) { uaOpt =>
  complete(uaOpt.getOrElse("N/A"))
}
```

and then make a request with low-case `user-agent` header name such as:

```
curl -k -X POST -H 'user-agent: Mozilla 5.0' 'http://localhost:8090/test'
```

then I get `N/A` in the response. This is in a clear violation of RFC 7230, where in point [3.2](https://tools.ietf.org/html/rfc7230#page-22) it says:

> Each header field consists of a **case-insensitive** field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.

When instead I use `headerValueByName`, then it behaves correctly and performs case-insensitive matching. Given that in server environment we cannot control implementation of various clients, this makes `headerValueByType` unusable for us, as it causes our service to be non-compliant with the RFC.

**Comment by jrudolph** [comment] 2019-03-05 10:02
The code you posted doesn't compile. If I use

```scala
    (path("test") & post & optionalHeaderValueByType[headers.`User-Agent`](()) ) { uaOpt =>
      complete(uaOpt.map(_.toString).getOrElse("N/A"): String)
    }
```

it works for me:

```
λ curl -v -k -X POST -H 'user-agent: Mozilla 5.0' 'http://localhost:8080/test'
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> POST /test HTTP/1.1
> Host: localhost:8080
> Accept: */*
> user-agent: Mozilla 5.0
> 
< HTTP/1.1 200 OK
< Server: akka-http/10.1.7+74-e1679dea+20190228-1450
< Date: Tue, 05 Mar 2019 10:02:08 GMT
< Content-Type: text/plain; charset=UTF-8
< Content-Length: 23
< 
* Connection #0 to host localhost left intact
User-Agent: Mozilla 5.0%
```

I'm closing it as invalid/works-for-me for now but feel free to request a reopen if you can reproduce it otherwise.

**Closed by jrudolph** 2019-03-05 10:02 UTC
Labels: 0 - new
