### ISSUE TITLE
Need Automatic-Module-Name in MANIFEST.MF

### ISSUE THREAD

**Issue by xuning97** [akka/akka-http#1914] opened 2018-03-08 09:51 UTC
Can we have such meta data,?

**Comment by ktoso** [comment] 2018-03-08 09:53
Please search before opening new tickets.

Yes, it's planned.

**Comment by ktoso** [comment] 2018-03-08 09:53
Duplicate of https://github.com/akka/akka-http/issues/1853

**Closed by ktoso** 2018-03-08 09:53 UTC

**Comment by ktoso** [comment] 2018-03-08 10:06
Set to be shipped today

**Comment by xuning97** [comment] 2018-03-24 10:43
thanks a lot!
