### ISSUE TITLE
java.lang.AbstractMethodError when using Akka HTTP with Akka 2.6 M6

### ISSUE THREAD

**Issue by fvyaba** [akka/akka-http#2651] opened 2019-08-20 04:47 UTC
I'm using akka-http(java:oracle jdk1.8.0_202, os: macos), just found 'java.lang.AbstractMethodError' under benchmark(using wrk).

- pom.xml(just fragement),listed below:
```
        <properties>
		<scala.version>2.13</scala.version>
		<akka-core.version>2.6.0-M6</akka-core.version>
		<akka-http.version>10.1.9</akka-http.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-actor_${scala.version}</artifactId>
			<version>${akka-core.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-stream_${scala.version}</artifactId>
			<version>${akka-core.version}</version>
		</dependency>
		<dependency>
			<groupId>com.typesafe.akka</groupId>
			<artifactId>akka-http_${scala.version}</artifactId>
			<version>${akka-http.version}</version>
		</dependency>
	</dependencies>
```

- server side code:
```
public class ServerEngine {
  public static void start(int port) {
    ActorSystem system = ActorSystem.create("akka-http");
    Http http = Http.get(system);
    ActorMaterializer materializer = ActorMaterializer.create(system);
    HttpFacade app = new HttpFacade();
    Flow<HttpRequest, HttpResponse, NotUsed> routeFlow = app.createRoute().flow(system, materializer);

    final CompletionStage<ServerBinding> binding = http.bindAndHandle(routeFlow, ConnectHttp.toHost("127.0.01", port),
        materializer);
    binding.thenRun(() -> {
      System.out.println("akka http server listening on port " + port);
    });
  }

  public static void main(String[] args) {
    start(8080);
  }
}
```

```
public class HttpFacade extends AllDirectives {
  public Route createRoute() {
    return concat(path("", () -> get(() -> {
      return complete("ok");
    })));
  }
}
```

- benchmark script(need install [wrk](https://github.com/wg/wrk.git) first)
`wrk -t16 -c100 -d30s --timeout=15s http://127.0.0.1:8080`

- err stack trace
```
Uncaught error from thread [akka-http-akka.actor.default-dispatcher-6]: Method akka/http/impl/engine/server/HttpServerBluePrint$RequestTimeoutSupport$$anon$3$$anon$7.akka$stream$stage$OutHandler$$_lastCancellationCause_$eq(Ljava/lang/Throwable;)V is abstract, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[akka-http]
java.lang.AbstractMethodError: Method akka/http/impl/engine/server/HttpServerBluePrint$RequestTimeoutSupport$$anon$3$$anon$7.akka$stream$stage$OutHandler$$_lastCancellationCause_$eq(Ljava/lang/Throwable;)V is abstract
	at akka.http.impl.engine.server.HttpServerBluePrint$RequestTimeoutSupport$$anon$3$$anon$7.akka$stream$stage$OutHandler$$_lastCancellationCause_$eq(HttpServerBluePrint.scala)
	at akka.stream.stage.OutHandler.onDownstreamFinish(GraphStage.scala:1835)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:391)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:615)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:494)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:590)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:758)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:773)
	at akka.actor.Actor.aroundReceive(Actor.scala:532)
	at akka.actor.Actor.aroundReceive$(Actor.scala:530)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:680)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:571)
	at akka.actor.ActorCell.invoke(ActorCell.scala:541)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:269)
	at akka.dispatch.Mailbox.run(Mailbox.scala:230)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by johanandren** [comment] 2019-08-20 06:55
Probably a duplicate of akka/akka#27529 

You're on Akka. 2.6.0-M6 right?

**Comment by jrudolph** [comment] 2019-08-20 09:13
Will be fixed with https://github.com/akka/akka/pull/27531. A fix will then be out with Akka 2.6 M7. Please use Akka 2.5.x or 2.6-M5 in the mean time.

**Comment by fvyaba** [comment] 2019-08-21 01:58
thanks for the great job!

**Comment by jrudolph** [comment] 2019-09-02 10:55
Let's close this once 2.6.0-M7 was released with the fix.

**Comment by brabo-hi** [comment] 2019-09-10 05:27
I have the same issue with 2.6.0-M7

**Comment by raboof** [comment] 2019-09-10 08:32
@brabo-hi can you share the exact stack trace you are getting?

**Comment by brabo-hi** [comment] 2019-09-10 17:21
scalaVersion := "2.12.7"
lazy val akkaHttpVersion = "10.1.9"
lazy val akkaTypedVersion = "2.6.0-M7"

```
Uncaught error from thread [myactorsystem-akka.actor.default-dispatcher-3]: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;, shutting down ActorSystem[myactorsystem]
java.lang.NoSuchMethodError: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;
        at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:75)
        at akka.http.impl.engine.client.PoolInterfaceActor$.$anonfun$props$1(PoolInterfaceActor.scala:34)
        at akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:90)
        at akka.actor.Props.newActor(Props.scala:212)
        at akka.actor.ActorCell.newActor(ActorCell.scala:609)
        at akka.actor.ActorCell.create(ActorCell.scala:635)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:509)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:531)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:294)
        at akka.dispatch.Mailbox.run(Mailbox.scala:229)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:242)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

```

**Comment by raboof** [comment] 2019-09-10 20:54
> java.lang.NoSuchMethodError: akka.stream.impl.Buffer$.apply(ILakka/stream/Materializer;)Lakka/stream/impl/Buffer;
>        at akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:75)

Thanks! That is a separate issue, caused by the fact that apparently `PoolInterfaceActor.scala` uses the internal akka-streams `Buffer` API. We didn't notice this because on master we already removed this usage. So the good news is on Akka HTTP 10.1.10, which we plan to release in the coming weeks, this particular problem should be gone.

Could you perhaps test with the snapshots (i.e. `10.1.9+126-c9f3e55c`)? You'll probably need to add the `Resolver.bintrayRepo("akka", "snapshots")` resolver?

**Comment by jrudolph** [comment] 2019-11-14 12:17
Fixed by now.

**Closed by jrudolph** 2019-11-14 12:17 UTC
Labels: 3 - in progress
