### ISSUE TITLE
Failed: FileUploadDirectivesExamplesSpec

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#2930] opened 2020-02-05 10:03 UTC
https://jenkins.akka.io:8498/job/akka-http-nightly-release-10.1/AKKA_VERSION=default,Node=akka-http-nightly-node,SCALA_VERSION=2.11.12,jdk=AdoptOpenJDK%2011/788/testReport/junit/docs.http.scaladsl.server.directives/FileUploadDirectivesExamplesSpec/storeUploadedFile/

```
org.scalatest.exceptions.TestFailedException: Request was neither completed nor rejected within 3 seconds
	at akka.http.scaladsl.testkit.TestFrameworkInterface$Scalatest$class.failTest(TestFrameworkInterface.scala:24)
	at akka.http.scaladsl.server.RoutingSpec.failTest(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.failNeitherCompletedNorRejected(RouteTestResultComponent.scala:93)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.rawResponse(RouteTestResultComponent.scala:58)
	at akka.http.scaladsl.testkit.RouteTestResultComponent$RouteTestResult.response(RouteTestResultComponent.scala:39)
	at akka.http.scaladsl.testkit.RouteTest$class.response(RouteTest.scala:61)
	at akka.http.scaladsl.server.RoutingSpec.response(RoutingSpec.scala:19)
	at akka.http.scaladsl.testkit.RouteTest$class.status(RouteTest.scala:79)
	at akka.http.scaladsl.server.RoutingSpec.status(RoutingSpec.scala:19)
	at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$5$$anonfun$apply$5.apply(FileUploadDirectivesExamplesSpec.scala:77)
	at docs.http.scaladsl.server.directives.FileUploadDirectivesExamplesSpec$$anonfun$5$$anonfun$apply$5.apply(FileUploadDirectivesExamplesSpec.scala:77)
```

**Comment by ignasi35** [comment] 2020-03-15 19:47
Related to #2733 (and partially to #2691)

**Comment by ignasi35** [comment] 2020-03-15 20:08
Duplicate of #2733

**Closed by ignasi35** 2020-03-15 20:08 UTC
Labels: failed
