### ISSUE TITLE
PoolInterfaceActor NullPointerException

### ISSUE THREAD

**Issue by dcullender** [akka/akka-http#1842] opened 2018-02-08 14:31 UTC
Hi Akka Http Team,

Thanks for a great product!

Once in a while, when we start our akka system, we get the below exception. We cannot work out what exactly caused it, but seems to be when the PoolInterfaceActor is starting

```
"[13:39:46.104] [ERROR] [akka://platform/user/pool-master/PoolInterfaceActor-1] [OneForOneStrategy] akka://platform/user/pool-master/PoolInterfaceActor-1: exception during creation"
"akka.actor.ActorInitializationException: akka://backend/user/pool-master/PoolInterfaceActor-1: exception during creation"
"\tat akka.actor.ActorInitializationException$.apply(Actor.scala:193)"
"\tat akka.actor.ActorCell.create(ActorCell.scala:608)"
"\tat akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462)"
"\tat akka.actor.ActorCell.systemInvoke(ActorCell.scala:484)"
"\tat akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)"
"\tat akka.dispatch.Mailbox.run(Mailbox.scala:223)"
"\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)"
"\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)"
"\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)"
"\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)"
"\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)"
"Caused by: java.lang.NullPointerException: null"
"\tat akka.stream.scaladsl.GraphDSL$Implicits$PortOpsImpl.filter(Graph.scala:1397)"
"\tat akka.http.impl.engine.client.PoolConductor$$anonfun$apply$2.apply(PoolConductor.scala:90)"
"\tat akka.http.impl.engine.client.PoolConductor$$anonfun$apply$2.apply(PoolConductor.scala:74)"
"\tat akka.stream.scaladsl.GraphApply$class.create(GraphApply.scala:17)"
"\tat akka.stream.scaladsl.GraphDSL$.create(Graph.scala:1161)"
"\tat akka.http.impl.engine.client.PoolConductor$.apply(PoolConductor.scala:74)"
"\tat akka.http.impl.engine.client.PoolFlow$$anonfun$apply$1.apply(PoolFlow.scala:81)"
"\tat akka.http.impl.engine.client.PoolFlow$$anonfun$apply$1.apply(PoolFlow.scala:76)"
"\tat akka.stream.scaladsl.GraphApply$class.create(GraphApply.scala:17)"
"\tat akka.stream.scaladsl.GraphDSL$.create(Graph.scala:1161)"
"\tat akka.http.impl.engine.client.PoolFlow$.apply(PoolFlow.scala:76)"
"\tat akka.http.impl.engine.client.PoolInterfaceActor.initConnectionFlow(PoolInterfaceActor.scala:105)"
"\tat akka.http.impl.engine.client.PoolInterfaceActor.<init>(PoolInterfaceActor.scala:92)"
"\tat akka.http.impl.engine.client.PoolInterfaceActor$$anonfun$props$1.apply(PoolInterfaceActor.scala:34)"
"\tat akka.http.impl.engine.client.PoolInterfaceActor$$anonfun$props$1.apply(PoolInterfaceActor.scala:34)"
"\tat akka.actor.TypedCreatorFunctionConsumer.produce(IndirectActorProducer.scala:87)"
"\tat akka.actor.Props.newActor(Props.scala:213)"
"\tat akka.actor.ActorCell.newActor(ActorCell.scala:563)"
"\tat akka.actor.ActorCell.create(ActorCell.scala:589)"
"\t... 9 common frames omitted"
```
Any ideas what may have caused this?

**Comment by raboof** [comment] 2018-02-08 19:51
Which version of Akka and Akka HTTP are you on?

**Comment by dcullender** [comment] 2018-02-09 17:53
Akka : 2.5.9
Akka HTTP : 10.0.11

**Comment by jrudolph** [comment] 2018-02-12 11:45
Hi @dcullender, thanks for the report.

I don't see a way how a NPE could happen at exactly that point. `akka.stream.scaladsl.GraphDSL$Implicits$PortOpsImpl.filter` is a trait forwarder method generated by the scala compiler that cannot fail AFAIK. I wonder if part of the stack trace is missing for some reason? 

Is the issue reproducible? You could try running with `-XX:-OmitStackTraceInFastThrow` to see if that would show another stack trace.

**Comment by dcullender** [comment] 2018-02-13 12:04
Thanks for getting back to me on this.

Very weird w.r.t the line number. It happens intermittently but we will add the flag and update the issue once we have a fresh trace.

**Comment by jrudolph** [comment] 2018-02-13 12:10
Btw. which Scala version do you run? Afaik it shouldn't make any difference but since the stack trace points to a forwarder something might have changed from before.

**Comment by jrudolph** [comment] 2018-10-30 10:58
Closing for now as we don't have enough information to reproduce. Please reopen or create a new ticket with more information about how to reproduce the issue.

**Closed by jrudolph** 2018-10-30 10:58 UTC
Labels: 0 - new
