### ISSUE TITLE
NPE when using withDisableSNI = true

### ISSUE THREAD

**Issue by MasseGuillaume** [akka/akka-http#2488] opened 2019-03-26 23:38 UTC
To reproduce:

```scala
import akka.actor.ActorSystem
import akka.stream.ActorMaterializer
import akka.stream.scaladsl._

import akka.http.scaladsl.{Http, HttpsConnectionContext}
import akka.http.scaladsl.model._

import com.typesafe.sslconfig.akka.AkkaSSLConfig

import akka.http.scaladsl.unmarshalling.Unmarshal

import scala.util.{Failure, Success}
import scala.concurrent.{Future, Await}
import scala.concurrent.duration._

import org.scalatest.{AsyncFunSuite, BeforeAndAfterAll, Assertion}

import spray.json.DefaultJsonProtocol._
import akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport._

case class AkamaiTlsCheck(tls_sni_status: String)

class SniTest() extends AsyncFunSuite with BeforeAndAfterAll {
  implicit val checkFormat = jsonFormat1(AkamaiTlsCheck)
  implicit val system = ActorSystem()
  implicit val mat = ActorMaterializer()

  import system.dispatcher

  def akamaiSniTest(context: HttpsConnectionContext, isSniDisabled: Boolean): Future[Assertion] = {
    // https://github.com/akka/akka/pull/23878/files
    val akamaiPool = Http().outgoingConnectionHttps("check-tls.akamaized.net", connectionContext = context)
    val request = HttpRequest(method = HttpMethods.GET, uri = "https://check-tls.akamaized.net/v1/tlssni.json")

    val flow = 
      Source.single(request).via(akamaiPool).mapAsyncUnordered(parallelism = 1) {
       case HttpResponse(StatusCodes.OK, _, entity, _) =>
         Unmarshal(entity).to[AkamaiTlsCheck]
      }

    val expectedStatus = 
        if (isSniDisabled) "???"
        else "present"

    flow.runWith(Sink.head).map(check =>
      assert(check.tls_sni_status == expectedStatus)
    )
  }

  test("akka-http with sni disabled") {
    // throws a NPE
    val httpsWithSniDisabled = Http().createClientHttpsContext(
      AkkaSSLConfig().mapSettings(s => s.withLoose(s.loose.withDisableSNI(true)))
    )

    akamaiSniTest(httpsWithSniDisabled, isSniDisabled = true)
  }

  test("akka-http supports tls sni extension") {
    akamaiSniTest(Http().defaultClientHttpsContext, isSniDisabled = false)
  }

  override def afterAll: Unit = {
   system.terminate()
  }
}
```

```
 SniTest:
 - akka-http with sni disabled *** FAILED ***
   java.lang.RuntimeException: Delegated task threw Exception/Error
   at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1527)
   at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
   at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:813)
   at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
   at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
   at akka.stream.impl.io.TLSActor.doUnwrap(TLSActor.scala:369)
   at akka.stream.impl.io.TLSActor.doInbound(TLSActor.scala:292)
   at akka.stream.impl.io.TLSActor.$anonfun$bidirectional$1(TLSActor.scala:227)
   at akka.stream.impl.Pump.pump(Transfer.scala:201)
   at akka.stream.impl.Pump.pump$(Transfer.scala:199)
   ...
   Cause: java.lang.NullPointerException:
   at sun.net.util.IPAddressUtil.textToNumericFormatV4(IPAddressUtil.java:49)
   at sun.net.util.IPAddressUtil.isIPv4LiteralAddress(IPAddressUtil.java:241)
   at sun.security.util.HostnameChecker.isIpAddress(HostnameChecker.java:125)
   at sun.security.util.HostnameChecker.match(HostnameChecker.java:93)
   at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:455)
   at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:436)
   at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:252)
   at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136)
   at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1601)
   at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
   ...
```

**Comment by johanandren** [comment] 2019-03-27 08:51
Thanks for reporting and the detailed reproducer! Any chance you would be up for PR:ing a fix as well?

**Comment by MasseGuillaume** [comment] 2019-03-27 14:51
Yes I will check tonight.

**Comment by johanandren** [comment] 2019-03-27 15:13
Great, thanks!

**Comment by vreyespuerta** [comment] 2019-06-05 09:20
I also have the very same issue. Is there any progress? Many thanks :)

**Comment by jrudolph** [comment] 2019-06-06 09:29
https://bugs.openjdk.java.net/browse/JDK-8211339

Seems to be fixed in JDK 12. Not sure sure what we can do about it. For now, you should probably stay away from `disableSNI`.

**Comment by vreyespuerta** [comment] 2019-06-14 14:09
Ok, I will do so. Many thanks! 👍

**Comment by jrudolph** [comment] 2020-10-05 12:20
Closing as "will not fix" for now. Seems to be a problem in the JDK with an uncommon setting.

**Closed by jrudolph** 2020-10-05 12:20 UTC
Labels: 1 - triaged, help wanted, t:tls
