### ISSUE TITLE
Idle Time Out Exception

### ISSUE THREAD

**Issue by manjotmona** [akka/akka-http#2546] opened 2019-05-27 04:44 UTC
Hi,
I am using Alpakka in my application to make requests to the dynamo DB.

I got this exception twice : **akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout** encountered on connection to [dynamodb.eu-west-1.amazonaws.com:443], no bytes passed in the last 1 minute

Both the times I got the exception in same scheduler (which runs every 3 seconds to update the records in the dynamoDB using Alpakka). Alpakka also uses Akka Http to make requests to the dynamoDB.

While going through the Akka Http docs I got to know that Akka Http throws the idle timeout exception when no data passes through an open connection for the idle-timeout duration (defined in conf).

Also is this an error scenario ?

**Comment by jrudolph** [comment] 2019-07-30 09:50
Hi @manjotmona, thanks for the report and sorry for the delay. Does it still happen?

There is the possibility of a race condition where a connection hasn't been used for the timeout given by the `idle-timeout` setting and then a new request comes in, right at the moment when the timeout triggers. If it's an idempotent request like `GET` it will be retried but otherwise, e.g. for `POST`, it might just fail.

I filed #2622 for a possible improvement in our pool infrastructure. Do you think that would help?

I'm closing this one as a duplicate of the new issue for organizational reasons. If you have more input please add it here or on the new ticket.

**Closed by jrudolph** 2019-07-30 09:50 UTC
