### ISSUE TITLE
Cannot push port (requestPrepOut) twice on request timeout

### ISSUE THREAD

**Issue by kstokoz** [akka/akka-http#396] opened 2016-10-16 20:26 UTC
Consider following code:

``` scala

import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.Route
import akka.stream.ActorMaterializer

import scala.concurrent.duration._
import scala.concurrent.{Await, Promise}

object ReproducerApp extends App {

  implicit val actorSystem = ActorSystem()
  implicit val ec = actorSystem.dispatcher
  implicit val materializer = ActorMaterializer()

  private val timeout = 1.second
  private val waitTime = 2.second

  val route: Route =
    (path("testPost") & post) {
      withRequestTimeout(timeout) {
        val promise = Promise[String]()

        actorSystem.scheduler.scheduleOnce(waitTime) {
          promise.success("Timeout didn't work!")
        }

        complete {
          promise.future
        }
      }
    }

  val bindingFuture = Http().bindAndHandle(route, "localhost", 12345)

  System.in.read()
  Await.ready(actorSystem.terminate(), 5.seconds)
}
```

Executing: 

```
curl -vvv --data @fileAtLeast10Kb "http://localhost:12345/testPost"
```

Would produce:

```
[ERROR] [10/16/2016 22:20:57.381] [default-akka.actor.default-dispatcher-24] [akka://default/user/StreamSupervisor-0/flow-15-0-unknown-operation] Error in stage [akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage@5c8aff50]: requirement failed: Cannot push port (requestPrepOut) twice
java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
    at scala.Predef$.require(Predef.scala:224)
    at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:459)
    at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:400)
    at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:747)
    at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:649)
    at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
    at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
    at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
    at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
    at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
    at akka.actor.ActorCell.invoke(ActorCell.scala:495)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by ktoso** [comment] 2016-10-16 20:36
1) On what version of akka?
2) Please read doc.akka.io/docs/akka/2.4/scala/http/implications-of-streaming-http-entity.html as your handling of the incoming upload is not correct. It should not throw like you pasted here, but it would back-pressure (by design) the upload as it is now.

**Comment by kstokoz** [comment] 2016-10-16 20:39
I`m running on v. 2.4.11.
yes i know about back-pressure, but in his context it is not relevant, i think. I was trying to have minimal reproducer.

**Comment by ktoso** [comment] 2016-10-16 20:42
Thanks for reporting then, we'll have a look at it.

**Comment by jrudolph** [comment] 2016-10-18 12:13
See also #19

**Comment by jrudolph** [comment] 2017-02-20 11:16
Let's close this as a duplicate of #516 which will be fixed in the next version.

**Closed by jrudolph** 2017-02-20 11:16 UTC
Labels: 3 - in progress, bug
