### ISSUE TITLE
Almost all Akka docs refer to Akka 2.4.19

### ISSUE THREAD

**Issue by satansk** [akka/akka-http#1452] opened 2017-10-04 15:34 UTC
Such as [Low-Level Server-Side API](https://doc.akka.io/docs/akka-http/10.0.10/scala/http/server-side/low-level-api.html):

>Apart from the HTTP Client Akka HTTP also provides an embedded, Reactive-Streams-based, fully asynchronous HTTP/1.1 server implemented on top of **Streams**.

The link of the last *Streams* refers to [Akka Streams 2.4.19](https://doc.akka.io/docs/akka/2.4.19/scala/stream/index.html), while the current version should be 2.5.6.

The link is coded like this:

```scala
[@extref[Streams](akka-docs:scala/stream/index.html)]
```

and `akka-docs` is configured like this:

```scala
"extref.akka-docs.base_url" -> s"http://doc.akka.io/docs/akka/${Dependencies.akkaVersion.value}/%s",
```

and Akka HTTP get `Dependencies.akkaVersion` by:

```scala
akkaVersion := System.getProperty("akka.build.version", "2.4.19"),
```

`akka.build.version` is not a system property and is not set manually, so we get a unwanted 2.4.19 .

**Comment by agebhar1** [comment] 2017-10-04 17:53
Not only the docs refer to 2.4.19 also the dependency refer to this version. See [Maven Reppository](http://mvnrepository.com/artifact/com.typesafe.akka/akka-http-core_2.12/10.0.10):

![akka-http-core_2 12_10 0 10](https://user-images.githubusercontent.com/2443866/31190834-949a1b50-a93c-11e7-9f0a-50ff6de5e8bb.png)

Akka HTTP Core v10.0.7 refer to Akka Streams v2.4.18. 

https://github.com/akka/akka-http/blob/36944e342318568b35d2ceb66a7e96f7a90a33a4/project/Dependencies.scala#L17
is unused in `Dependencies.scala`. Should 
https://github.com/akka/akka-http/blob/36944e342318568b35d2ceb66a7e96f7a90a33a4/project/Dependencies.scala#L27
be
```scala
 akkaVersion := System.getProperty("akka.build.version", akka25Version)
```
:thinking:

**Comment by ktoso** [comment] 2017-10-04 18:14
This is by design and it is documented how to use Akka HTTP 10.x with Akka 2.5: https://doc.akka.io/docs/akka-http/current/scala/http/compatibility-guidelines.html#akka-http-10-0-x-with-akka-2-5-x 

We'll do a 10.1 that will depend on 2.5 explicitly soon though, so this question would then be resolved in a "it now depends on 2.5" way.

**Comment by ktoso** [comment] 2017-10-04 18:16
To explain the "by design" part; This is because if we depend on 2.4, people can force the 2.5 dep easily and things remain binary compatible etc. Once we depend on 2.5 we could end up using 2.5 APIs and not be compatible with 2.4 anymore.

**Comment by agebhar1** [comment] 2017-10-04 18:19
Thanks for the insights @ktoso!

**Comment by satansk** [comment] 2017-10-11 13:50
Thanks for your explanation @ktoso , we can keep this issue open until the new Akka HTTP 10.1, as it will help people with the same question.

**Comment by jrudolph** [comment] 2017-10-11 14:25
We already have a few tickets for that issue. Let's close this one as a duplicate of https://github.com/akka/akka-http/issues/1151. We hope to resolve the situation in the coming months.

**Closed by jrudolph** 2017-10-11 14:25 UTC
Labels: 0 - new

**Comment by ktoso** [comment] 2017-10-11 14:26
Agree, thanks

—
Konrad `kto.so` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 11 October 2017 at 23:25:51, Johannes Rudolph (notifications@github.com)
wrote:

We already have a few tickets for that issue. Let's close this one as a
duplicate of #1151 <https://github.com/akka/akka-http/issues/1151>. We hope
to resolve the situation in the coming months.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/1452#issuecomment-335828218>, or mute
the thread
