### ISSUE TITLE
Marshaller matches MIME types case sensitively

### ISSUE THREAD

**Issue by alar17** [akka/akka-http#2147] opened 2018-08-15 08:52 UTC
Mime types are case-insensitive. However, when we use the Akka http Marshaller to serve the content as a response to a request which includes accept header (with the different letter case), the response code would be 406.

Here is the reproducer code:
```
import static akka.http.javadsl.server.Directives.completeOK;
import static akka.http.javadsl.server.Directives.get;
import static akka.http.javadsl.server.Directives.pathEndOrSingleSlash;
import static akka.http.javadsl.server.Directives.route;

import akka.http.javadsl.marshalling.Marshaller;
import akka.http.javadsl.model.ContentType;
import akka.http.javadsl.model.HttpEntities;
import akka.http.javadsl.model.RequestEntity;
import akka.http.javadsl.server.Route;
public class DirectivesSample {

    private static final ContentType TEXT_XML = akka.http.scaladsl.model.ContentType$.MODULE$.parse("text/xml").right().get();

    public static Route serveContent(String content) {
        Marshaller<String, RequestEntity> contentAsXML = Marshaller.withFixedContentType(TEXT_XML, c ->
        HttpEntities.create(TEXT_XML, content.getBytes()));
        return completeOK(content, contentAsXML);
    }

    public Route apply() {
        return route(
            pathEndOrSingleSlash(() ->
                get(() ->
                    serveContent("sample string")
                )
            )
        );
    }
}

```
Requests:
`curl -i  http://localhost:8865/documents -H "accept:text/xml"`
=>

> HTTP/1.1 200 OK
> Server: akka-http/10.0.13
> Date: Wed, 15 Aug 2018 07:56:22 GMT
> Content-Type: text/xml
> Content-Length: 13
> 
> sample string

===================
`curl -i  http://localhost:8865/documents -H "accept:text/Xml"`
=>

> HTTP/1.1 406 Not Acceptable
> Server: akka-http/10.0.13
> Date: Wed, 15 Aug 2018 07:56:30 GMT
> Content-Type: text/plain; charset=UTF-8
> Content-Length: 68
> 
> Resource representation is only available with these types:
> text/xml

**Comment by raboof** [comment] 2018-08-15 08:55
I haven't looked too closely but could this be a duplicate of #2126?

**Comment by jrudolph** [comment] 2019-07-30 11:49
Yep, seems like a duplicate of #2126. Closing for now.

**Closed by jrudolph** 2019-07-30 11:49 UTC
