### ISSUE TITLE
max-open-requests misbehaviour

### ISSUE THREAD

**Issue by georgeyanev** [akka/akka-http#1186] opened 2017-06-09 12:56 UTC
I'm testing the `akka.http.host-connection-pool.max-open-requests` with the value of 1. It seems that if I issue two requests one right after the other, the second does not fail with `Status.Failure`. The future never completes instead.  
This happens only if these two http requests are not the first ones on the given http connection, if they are the first - it works as expected returning `Status.Failure`.

Here is a reproducer containing two test cases and a dummy server. [https://github.com/georgeyanev/max-open-req](https://github.com/georgeyanev/max-open-req)

First test case shows the failing scenario where we expect the `Status.Failure` with BufferOverflow but it does not come. In that case we have a previous http request over this connection with a consumed response.

Second case shows the successful scenario where we receive the expected BufferOverflow. In this case there are no previous http requests over that connection.

**Comment by jrudolph** [comment] 2017-06-14 10:32
Hi @georgeyanev, thanks for the report and reproducer.

Have you seen the documentation on `max-open-requests` here: http://doc.akka.io/docs/akka-http/current/scala/http/client-side/pool-overflow.html? The setting doesn't strictly limit the number of outstanding requests per host but is used to configure an internal buffer.

In the reproducer, in the `testOverload` case, the last request is never dispatched because you never read the entity from the second request, so the slot was taken indefinitely. It didn't fail with a `BufferOverflowException` because `max-open-requests = 1` means that one undispatched request can be buffered.

In the `testOverloadSuccess` case that seems to work as expected, it's only accidentally because the first request wasn't dispatched when the second arrived but this is just a timing issue.

**Comment by georgeyanev** [comment] 2017-06-15 06:51
And if a http server starts to respond very slow how do I detect this and stop overloading it with requests?

**Comment by jrudolph** [comment] 2018-02-19 15:49
@georgeyanev, sorry for never responding. Is this still an issue for you?

**Comment by georgeyanev** [comment] 2018-02-21 14:48
If this is not actually an issue, then I'm still interested in an answer to my question before.

**Comment by mbknor** [comment] 2018-09-09 11:39
I'm also having concerns with this issue.


I have a rest service using akka-http server. Sometime I need to request data from an external rest-server. For this I use akka-http client:
```
Http().singleRequest(request)
```

I'm experimenting with
```
akka.http.host-connection-pool.max-connections = 1
akka.http.host-connection-pool.max-open-requests = 1
```
to test out what happens if I'm trying to start too many requests to external service.

In a test I created a "slow" rest-server.
Then I start the first connection to it using *singleRequest()*. It returns a Future that will not complete for a long time.

Then I make another request, which fails immediately with *akka.stream.BufferOverflowException* as expected.

The next one also fails with *akka.stream.BufferOverflowException* (as expected).

But if I do it a third time, I do not het the exepction. Nothing happens until the Future times out.

This cannot be a good solution.

This means that I cannot distinguish between the request timing out due to slow external server, or if it times out due to too many requests (more than *akka.http.host-connection-pool.max-open-requests*)

To make things more complext, I'm actually wrapping the singleRequest() using a circuitBreaker.
By default, it tripped, when it received *BufferOverflowException*. This was not a good solution, but I managed to fix it by using a custom *defineFailureFn*-function.

But I do want my circuit breaker to break, if the external server is too slow (I'm getting timeouts).
But with this *BufferOverflowException*-bug, I cannot do it, since I cannot distinguish between the to cases.

I'm actually thinking about creating a workaround for this problem, by keeping track of open request on my own, so that my own code can throw BufferOverflowException BEFORE akka-http-clients starts to do it, to prevent it from resulting in timeouts.

What do you think about this workaround?

Best regards,
Morten Kjetland

**Comment by jrudolph** [comment] 2020-02-06 12:49
@mbknor sorry for never answering that. The behavior seems weird indeed. Maybe it has been fixed with the new pool implementation? Also implementing proper request timeouts (#42) will help.

Closing this one for now.

**Closed by jrudolph** 2020-02-06 12:49 UTC
Labels: 0 - new
