### ISSUE TITLE
Accept header accepts "abc" as any MediaType

### ISSUE THREAD

**Issue by linda11111** [akka/akka-http#2022] opened 2018-05-18 07:13 UTC
In my api call I return an application/json response.

If I set the header Accept = application/octet-stream I get the response:
406 Not Acceptable, Resource representation is only available with these types:application/json

If I add a rubbish value e.g abc to the Accept header (Accept = abc or Accept = application/octet-stream,abc)  I get my application/json response.

I believe this is a bug. Should I not get a 406 Not Acceptable here too?

**Comment by johanandren** [comment] 2018-05-21 13:27
Sounds like a bug to me

**Comment by raboof** [comment] 2018-05-23 15:12
These 'rubbish' headers (`Accept: abc` or `Accept: application/octet-stream,abc`) don't just contain 'rubbish' media types, but are actually formatted in a way that doesn't adhere to the spec (https://tools.ietf.org/html/rfc2616#section-14.1), and thus cannot even be parsed.

When a header cannot be parsed, it is ignored (kept as a `RawHeader` and not considered at all during negotiation). I can't find anything specific about it in the RFC, but I think ignoring malformed headers is a reasonable approach.

Note that `Accept` headers that have an unknown but well-formed media type are properly rejected with `406 Not Acceptable`.

So I think I'd say this is expected/acceptable behaviour. WDYT?

**Comment by raboof** [comment] 2018-06-14 07:06
Closing this as 'intended behavior' for now, feel free to re-open if we find any additional references that suggest this is not reasonable behavior after all.

**Closed by raboof** 2018-06-14 07:06 UTC
Labels: 0 - new, t:server
