### ISSUE TITLE
Form field directives require buffering of all content

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#8] opened 2016-08-24 12:51 UTC
The current `formField` and friends require buffering of the full request, since we don't know when each field is going to come in from the live TCP stream.

Futures won't work very well for this, since not consuming them may cause the source stream to stop in case "bigfile" comes before "smallvalue".

Suggestion: chop up the TCP stream into `FormField` elements (or maybe an `HMap`-like thingy to make things more type and keep the extractors), where  each `FormField` contains, at lowest level, a `name:String` and `contents:Source[ByteString,NotUsed]`. Then require that those sub streams are consumed in order, unless explicitly buffered.

Related: https://github.com/akka/akka/issues/18426

**Comment by 2beaucoup** [comment] 2016-08-24 14:09
The problem is that the `formFields` directive unmarshals  `application/x-www-form-urlencoded` and `multipart/form-data` entities to `StrictForm` whereas the latter should be replaced by `entity(as[Multipart.FormData])` for large entities. Maybe we should warn when the `formFields` directive is used for getting file contents and use a small default size limit.

**Comment by 2beaucoup** [comment] 2016-08-24 14:17
https://github.com/akka/akka/issues/18591 seems related

**Comment by jrudolph** [comment] 2017-07-17 13:55
Also related: #73

**Comment by jrudolph** [comment] 2018-12-12 13:21
Let's close this as a duplicate of #73 which contains all the information about how we could improve the situation.

**Closed by jrudolph** 2018-12-12 13:21 UTC
Labels: 1 - triaged, t:routing, t:server
