### ISSUE TITLE
Possible leak when using Http pool with Flow.completionTimeout

### ISSUE THREAD

**Issue by jubecker** [akka/akka-http#1203] opened 2017-06-15 06:49 UTC
With the following (simplified) code (from our REST client which uses akka-http under the hood)
```
...
val httpPool = Http().superPool[Unit]()
...
// the pool gets reused for 'dispatching' requests.
// so, we have a stream per request
Source
  .single((request, ()))
  .via(httpPool)
  .completionTimeout(requestTimeout.duration)
  .mapAsyncHttpResponse(t => Future.fromTry(t._1))
  .runWith(Sink.head)
```

we observe the following behaviour:
During a phase of many requests,  the buffer in PoolInterfaceActor fills up.  Not all request can be handled in time and we see timeouts coming from the completionTimeout stage, canceling the stream. This continues until the buffer is full. Even after a phase of no new requests coming in, this situation does nor recover. New requests will later fail with the BufferOverflowException. 
See attached DEBUG log and gattling statistics.

This opens two questions:
1. When a request is dispatched to a connection from the http pool and the completionTimeout triggers the cancelation of the stream while the request is not finished, we have an unconsumed entity on the response, right? Which we also can't consume because we can't get a handle on it, as the stream is finished.
2. When a request was not yet dispatched to the pool and the stream times out, we might again have a leak, because the element will not be removed from the buffer (as far as I can see from the code).

Maybe we are doing something wrong or the combination of the completionTimeout with a pool can be dangerous.

This might be related to https://github.com/akka/akka-http/issues/843

[log.zip](https://github.com/akka/akka-http/files/1076780/log.zip)
[simulation-1497450507964.zip](https://github.com/akka/akka-http/files/1076790/simulation-1497450507964.zip)

**Comment by jrudolph** [comment] 2017-07-26 13:52
Hi @jubecker, thanks for the data and sorry for keeping this ticket unhandled for a while.

> When a request is dispatched to a connection from the http pool and the completionTimeout triggers the cancelation of the stream while the request is not finished, we have an unconsumed entity on the response, right? Which we also can't consume because we can't get a handle on it, as the stream is finished.

Yes, exactly, and according to #1248 that will stall a pool slot.

> When a request was not yet dispatched to the pool and the stream times out, we might again have a leak, because the element will not be removed from the buffer

That's another known issue that wouldn't be a leak if #1248 would be handled because then the idle-timeout would make sure that slots are freed eventually.

I'll close this ticket as a duplicate of #1248. I'll soon add more information there about how are going about to fix it.

**Closed by jrudolph** 2017-07-26 13:52 UTC

**Comment by jrudolph** [comment] 2017-07-26 13:54
Btw. instead of using the superpool with `Source.single` I'd suggest to use `Http.singleRequest` in the first place.
