### ISSUE TITLE
Failed: NewConnectionPoolSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#1619] opened 2017-12-12 15:56 UTC
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master/376//consoleFull
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/360/console

```
[info] - should complete a simple request/response cycle with a strict request and response *** FAILED ***
[info]   java.lang.AssertionError: expected OnNext, found OnComplete
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:327)
[info]   at akka.stream.testkit.TestSubscriber$ManualProbe.expectNext(StreamTestKit.scala:316)
[info]   at akka.stream.testkit.TestSubscriber$Probe.requestNext(StreamTestKit.scala:753)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$SetupWithServerProbes$2$ServerConnection.expectRequest(HostConnectionPoolSpec.scala:370)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$1$$anon$1.<init>(HostConnectionPoolSpec.scala:89)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$1.apply(HostConnectionPoolSpec.scala:85)
[info]   at akka.http.impl.engine.client.HostConnectionPoolSpec$$anonfun$testSet$1$$anonfun$apply$mcV$sp$1.apply(HostConnectionPoolSpec.scala:85)
```

And a few more failures.

**Comment by jrudolph** [comment] 2017-12-14 10:25
Let's treat this as a duplicate of #1610.

**Closed by jrudolph** 2017-12-14 10:25 UTC
Labels: failed, t:client-new-pool
