### ISSUE TITLE
HttpHeader parses Accept header value as lowercase

### ISSUE THREAD

**Issue by rwiskerke** [akka/akka-http#2266] opened 2018-10-25 11:57 UTC
When upgrading from 10.0.9 to the current version (10.1.5) of akka-http, one of my test started failing (which specifies a specific Accept Header).

I've been able to recreate it by adding this test to the HttpHeaderSpec:

```
"Accept: application/vnd.WithCapitals" =!=
  Accept(MediaType.applicationBinary("vnd.WithCapitals", MediaType.Compressible))
```

So it seems to convert the value part of the Accept header to lowercase. And that's a problem because the matching is currently case-sensitive and I get this error, which is really weird: 
```
Resource representation is only available with these types:
application/json
application/vnd.WithCapitals
```

So if I copy-paste the `application/vnd.WithCapitals` mediatype to the Accept header, it will still fail.

**Comment by raboof** [comment] 2018-11-05 14:17
This looks like a duplicate of #2147, unless I'm mistaken?

**Closed by raboof** 2018-11-05 14:17 UTC
