### ISSUE TITLE
Make idleTimeout not scare people with "No elements passed in the last 1 minute." errors

### ISSUE THREAD

**Issue by chauhraj** [akka/akka-http#505] opened 2016-11-09 20:51 UTC
In `akka-http v2.4.11`, I got this following exception:-

```
java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
        at akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
        at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
        at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
        at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
        at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
        at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
        at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
        at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I am not doing anything fancy but just calling Source.single(request) to akka http server. In my case, akka-stream is just a blackbox.

Under what circumstances, will I see this error?

However, when this exception happened, I also see another exception that occurred prior to this.

akka.stream.StreamTcpException: Tcp command [Connect(:,None,List(),Some(10 seconds),true)] failed`

Can this exception manifest the TimeoutException? Strangely, StreamTcpException doesn't have any Stacktrace. Besides, I cannot reproduce any of the above errors. So, I am clueless when it may happen. I do not see any exceptions in my server logs.

> I see a similar [issue](https://github.com/akka/akka/issues/18982) filed for v2.4.3 but that issue was closed. I didn't know how to reopen the existing one so created a new one.

**Comment by ktoso** [comment] 2016-11-09 23:05
Just a quick answer here - it's not a bug, it is simply the "idle timeout" of connections triggering.
I.e. you're not actually transfering any data over a connection within a minute, so it shuts down.

This is not a bug but proper behaviour.
I do agree however that the reporting it as an error like we do right now is very confusing to people coming to akka http and we should fix it - this should be done by changing the `idleTimeout` to a specialized stage which does the same thing in the http infrastructure. Help contributing this would be awesome btw, if you're up for it.

**Comment by chauhraj** [comment] 2016-11-11 17:55
Would love to do the contribution. If it is a proper behavior then why even a stacktrace. Are you suggesting to downgrade the logLevel from ERROR to something else. IMO, if it is correct behavior and connection is shutdown, then the stacktrace should be suppressed altogether. Since, in my particular case, I am not using Host/Request Level Cache Pool, what will be the implication of shutting down the connection.

what does it mean when you say "this should be done by changing the idleTimeout to a specialized stage which does the same thing in the http infrastructure"?

**Comment by ktoso** [comment] 2016-11-11 19:05
> what does it mean when you say "this should be done by changing the idleTimeout to a specialized stage which does the same thing in the http infrastructure"?

That basically explains how to implement this :)
We have a `.idleTimeout` on these connections, it's an Akka provided operation, but it logs the failure. We should build one that won't log basically. It needs some digging around if we can change .idleTimeout or not really, since AFAIR if a stage throws then we log it hm... Another way would be to add a `mapError` (which I think is alredy there, but seems not to work as we want it to) that would convert this error to a different one that we don't log - the logging stage would know it does not have to log this one.

Needs some digging :) Happy to guide / provide tips, let us know if you start on it.
We'd rather want to fix this soon

**Comment by chauhraj** [comment] 2016-11-12 21:58
Yes, I would need some hand holding initially. This would help in future
contribution. I tried to look into Timers.java where it was calling
failStage, if I remember correctly.

On Nov 11, 2016 2:05 PM, "Konrad Malawski" <notifications@github.com> wrote:

what does it mean when you say "this should be done by changing the
idleTimeout to a specialized stage which does the same thing in the http
infrastructure"?

That basically explains how to implement this :)
We have a .idleTimeout on these connections, it's an Akka provided
operation, but it logs the failure. We should build one that won't log
basically. It needs some digging around if we can change .idleTimeout or
not really, since AFAIR if a stage throws then we log it hm... Another way
would be to add a mapError (which I think is alredy there, but seems not to
work as we want it to) that would convert this error to a different one
that we don't log - the logging stage would know it does not have to log
this one.

Needs some digging :) Happy to guide / provide tips, let us know if you
start on it.
We'd rather want to fix this soon

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/505#issuecomment-260030845>, or mute
the thread

**Comment by ktoso** [comment] 2016-12-02 12:34
> Is the workaround for this then to suppress my logs from this class right
> now?  We use ERROR level for alerting across our application, so this is
> quite annoying when false alarms come up...

@gmalouf same as with any other logging, you should be able to configure the given log source to be OFF for certain conditions. It's outside of Akka really.

The log message itself will be fixed / much better, however it's a larger effort I keep getting pulled away from.

**Comment by gmalouf** [comment] 2016-12-02 12:38
The issue is it's not just logging but an actual timeout exception that bubbles up from the application.  We currently have alerts configured on our web application when an ERROR level message is triggered, so this thrown exception bubbles up to our catch all handler multiple times/day leading to false alarms.  

It's not quite as easy as just turning off - we'd have to catch the timeout exception and log that at a lower level (hoping it's safe).

**Comment by ktoso** [comment] 2016-12-02 12:40
The message is harmless; it should not have been ERROR - long story related to it.
It needs a custom stage, but was implemented using a generic operation.

I disagree that it's not about how it's logged - it is, and that root cause needs to be fixed. Also it should include information which request triggered it, which is why it's hard to complete properly.

**Comment by gmalouf** [comment] 2016-12-02 13:42
I'm saying there is an exception being thrown which many of us end up logging at ERROR level.  The current work-around I am doing is checking for the timeout exception and making sure the message matches the expected one currently being thrown.

**Comment by ktoso** [comment] 2016-12-02 14:07
Yeah, that's the problem and workaround.
Happy to accept help in the form of pull requests while I attempt to make time to work on this :)

**Comment by abdelrahmanmohamed** [comment] 2016-12-11 23:41
Hello @ktoso I use completeOK in my router and I got the same error , should completeOK close the connection or leave it opened, if I want to close the connection should I use low level?

**Comment by ktoso** [comment] 2016-12-12 16:39
Again:

- it's not an error, it is logged on `debug` level.
- yes, I'm fixing it such that it does not look so "scary", i.e. does not include stack trace, which makes people think it's an error.
- the stream must fail, as this is how stream shutdown works.

PR soon.

**Closed** 2016-12-22 15:59 UTC
Labels: 3 - in progress, t:core

**Comment by dancohensmith** [comment] 2017-01-06 16:57
This exception bubbles up on a request when the server is completing with completeOKWithSource and the source has intermittent elements by design this is my logging on the client side i am watching the response stream termination:
6:52:50.114 [default-akka.actor.default-dispatcher-5] DEBUG akka.actor.RepointableActorRef - Aborting tcp connection because of upstream failure: No elements passed in the last 1 minute.
akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
akka.actor.Actor$class.aroundReceive(Actor.scala:484)
akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
akka.actor.ActorCell.invoke(ActorCell.scala:495)
akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
akka.dispatch.Mailbox.run(Mailbox.scala:224)
akka.dispatch.Mailbox.exec(Mailbox.scala:234)
scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
16:52:50.121 [default-akka.actor.default-dispatcher-9] ERROR com.hsbc.dtc.de.pp.payments.TestHTTP - response process flow terminated badly
java.util.concurrent.CompletionException: java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:647)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21)
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:63)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:78)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:55)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:54)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
	at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:106)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:40)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:248)
	at scala.concurrent.Promise$class.complete(Promise.scala:55)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:153)
	at scala.concurrent.Promise$class.failure(Promise.scala:104)
	at scala.concurrent.impl.Promise$DefaultPromise.failure(Promise.scala:153)
	at akka.stream.impl.fusing.GraphStages$TerminationWatcher$$anon$3.onUpstreamFailure(GraphStages.scala:134)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:733)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:616)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:471)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:423)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:603)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:618)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:529)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.concurrent.TimeoutException: No elements passed in the last 1 minute.
	at akka.stream.impl.Timers$IdleTimeoutBidi$$anon$7.onTimer(Timers.scala:160)
	at akka.stream.stage.TimerGraphStageLogic.akka$stream$stage$TimerGraphStageLogic$$onInternalTimer(GraphStage.scala:1152)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
	at akka.stream.stage.TimerGraphStageLogic$$anonfun$akka$stream$stage$TimerGraphStageLogic$$getTimerAsyncCallback$1.apply(GraphStage.scala:1141)
	at akka.stream.impl.fusing.GraphInterpreter.runAsyncInput(GraphInterpreter.scala:691)
	at akka.stream.impl.fusing.GraphInterpreterShell.receive(ActorGraphInterpreter.scala:419)
	... 13 common frames omitted

**Comment by dancohensmith** [comment] 2017-01-06 17:00
Why does the stream need to fail? why can't a stream be idle? this is valid if you have a streaming source pushing to a client and the elements are intermittent.  i.e if you were to use akka-http completeOKWithSource and then start processing the response. there is no reason for the stream to die just because no data has flowed.

**Comment by jrudolph** [comment] 2017-01-09 16:48
@dancohensmith it's a safety precaution to prevent that streams stay alive indefinitely either due to a bug or a peer having gone away silently. You can disable it in the configuration if doesn't fit your application.

**Comment by dancohensmith** [comment] 2017-01-10 08:30
I set all the akka-http timeouts to infinite for client, host-pool and server . Is  there anything else I can set?

**Comment by dancohensmith** [comment] 2017-01-12 21:13
@jrudolph Would really appreciate your assistance..

**Comment by ktoso** [comment] 2017-01-12 21:15
The settings work correctly... you can disable ti timeouts if you want, it works, i confirmed it a few days ago.
Update to latest akka.
Read the docs, set the correct settings.

**Comment by ktoso** [comment] 2017-01-12 21:15
Please do not continue this thread here, this issue is closed and solved. If you uncover Akka not working properly (aka. a bug) please report a new ticket with reproducer.
