### ISSUE TITLE
HttpServer Post request entity have HTTPEntity.strict and HTTPEntity.default type(the probability of 1/5000 ) 

### ISSUE THREAD

**Issue by ktoso** [akka/akka-http#1187] opened 2017-06-12 12:51 UTC
<a href="https://github.com/kejiawu"><img src="https://avatars2.githubusercontent.com/u/17840185?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kejiawu](https://github.com/kejiawu)**
_Friday Jun 09, 2017 at 01:39 GMT_
_Originally opened as https://github.com/akka/akka/issues/23128_

----

I found a problem.
Create Httpserver and send Post request . not keep-alive
The request content length is 594. Usually HttpRequestEntity type is strict, but the probability of 1/5000 will be HttpRequestEntity default type, and I read entity content timeout(3s).

When request content length is 465,  HttpRequestEntity default type didn't appear.
Does anyone know how to solve the problem.
Please help me.
Thanks.

Request HttpEntity object toString, the result is:
HttpEntity.Default(text/xml; charset=UTF-8,594 bytes total)

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/ktoso"><img src="https://avatars2.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 09, 2017 at 01:43 GMT_

----

Please read http://doc.akka.io/docs/akka-http/10.0.6/java/http/implications-of-streaming-http-entity.html which explains what's happening here.
Akka HTTP is streaming by nature, so yeah, requests don't have to be strict - they are often streaming. simply consume the entity stream using streaming (`entity.runWith...`) or use directives to convert into case classes. you can also call `toStrict` on it which will give you a strict entity - it  will however be loaded in full into memory then

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/ktoso"><img src="https://avatars2.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 09, 2017 at 01:44 GMT_

----

As this does not look to be an issue, but more of a question, closing - feel free to add more details if you think this is a bug and we can reopen it. Generally github is only used for issues / bugs, not asking questions You can ask on [community mailing list](https://groups.google.com/forum/#!forum/akka-user) if you have more questions about using akka

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/ktoso"><img src="https://avatars2.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 09, 2017 at 01:44 GMT_

----

Also please note that the right repo for Akka HTTP things is: https://github.com/akka/akka-http

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/kejiawu"><img src="https://avatars2.githubusercontent.com/u/17840185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kejiawu](https://github.com/kejiawu)**
_Friday Jun 09, 2017 at 01:59 GMT_

----

I use entity.toStrict(2300, materializer).whenComplete((strict, th) -> {});
The result is timeout exception.  

The code is:
entity.toStrict(2300, materializer).whenComplete((strict, th) -> {
					if (strict != null) {
						String data = strict.getData().decodeString(HttpCharsets.UTF_8.value());
						sender.tell(setResult(ResultCode.SUCCESS, ResultCode.SUCCESS_DESC, data), self);
					} else {
						logOut("Get content length :"+len);
						logOut(LogUtil.printExceptionToString(th));
						sender.tell(setResult(ResultCode.FAILED, ResultCode.FAILED), self);
					}
				});

What's the problem with this??

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/ktoso"><img src="https://avatars2.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 09, 2017 at 02:13 GMT_

----

what's the request though

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/kejiawu"><img src="https://avatars2.githubusercontent.com/u/17840185?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kejiawu](https://github.com/kejiawu)**
_Friday Jun 09, 2017 at 02:37 GMT_

----


POST http://192.168.99.203:8080/

POST data:
[no cookies]

Request Headers:
Connection: close
Content-Type: text/xml; charset="utf-8"
Accept-Encoding: gzip,deflate
Content-Length: 594
Host: 192.168.99.203:8080
User-Agent: Apache-HttpClient/4.2.6 (java 1.5)

<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:gg="http://www.ggggggggggg.com/ggg/">
   <soapenv:Header>
      <hss:PassWord>boss@123</hss:PassWord>
      <hss:UserName>boss1</hss:UserName>
   </soapenv:Header>
   <soapenv:Body>
      <hss:AAA_BBBB>
         <hss:HLRSN>1</hss:HLRSN>
         
         
         
         <hss:BBBB>0000000000000</hss:BBBB>
         
      
      </hss:AAA_BBBB>
   </soapenv:Body>
</soapenv:Envelope>

**Comment by ktoso** [comment] 2017-06-12 12:51
<a href="https://github.com/ktoso"><img src="https://avatars2.githubusercontent.com/u/120979?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ktoso](https://github.com/ktoso)**
_Friday Jun 09, 2017 at 02:38 GMT_

----

Should just work, you may be doing something weird somewhere else?
Please prepare a reproducer in case you think it's Akka at fault so we can reproduce the issue

**Comment by ktoso** [comment] 2017-06-12 12:52
Ported the discussion, however not quite sure what to do with this; would be ok with closing as unactionable as no reproducer was provided, WDYT?

**Comment by jrudolph** [comment] 2017-06-14 10:21
Hi @kejiawu, thanks for the report but we need more information to reproduce the issue. I'm closing the issue for now but we will reopen if you can provide more info.

**Closed by jrudolph** 2017-06-14 10:21 UTC
Labels: 0 - new

**Comment by kejiawu** [comment] 2017-06-16 02:30
Hi, I found that, when  read entity content timeout(3s) exception show, the akka log write this: 
`[WARN] [06/15/2017 20:13:38.528] [SOAP_AGENT_SOAP1-akka.actor.default-dispatcher-2] [akka.actor.ActorSystemImpl(SOAP_AGENT_SOAP1)] Sending an 2xx 'early' response before end of request was received... Note that the connection will be closed after this response. Also, many clients will not read early responses! Consider only issuing this response after the request data has been completely read!
`
This warning has also been linked to a timeout exception with me ??

I read other 2xx 'early' problem. I think read reqeust entity timout means request is not full read, so when I break up stream, return response, this warning will show, does is right?

Is anywhy to avoid it.

my read entity content code is:

`public class ProtocalHandle extends AbstractActor {
	ActorRef sender ;
	ActorRef self ;
	int count =0 ;

	@Override
	public Receive createReceive() {
		ActorMaterializer materializer = ActorMaterializer.create(getContext());
		return receiveBuilder().match(
				HttpRequest.class,
				request -> {
					sender = getSender();
					self = getSelf();
					try {
						CompletionStage<HttpEntity.Strict> strictEntity = request.entity().toStrict(
								FiniteDuration.create(3, TimeUnit.SECONDS).toMillis(), materializer);
						strictEntity.thenCompose(strict -> strict.getDataBytes()
								.runFold(ByteString.empty(), (acc, b) -> acc.concat(b), materializer)
//								.thenApply(this::parse)
								.thenApply(bs ->{
									System.out.println("actor count: "+count++);
									if (bs != null) {
										sender.tell(bs, self);
//										System.out.println("person.name:"+bs.name);
										return bs;
									}else {
										sender.tell("exception", self);
										return "exception";
									}
								}));
					} catch (Exception e) {
						System.out.println("timeout");
						e.printStackTrace();
						sender.tell("exception", self);
					}
					
				}).matchEquals("test", s ->{
					getSender().tell("test result: success", getSelf());
				}).build();
	}

	public static Props createProps() {
		return Props.create(ProtocalHandle.class);
	}
}`


and Httpserver code :

private static void test2HttpServer(ActorSystem system) {
		final Materializer materializer = ActorMaterializer.create(system);

		Http http = Http.get(system);

		Source<IncomingConnection, CompletionStage<ServerBinding>> serverSource = http.bind(
				ConnectHttp.toHost("0.0.0.0", 8080), materializer);

		Flow<HttpRequest, HttpRequest, NotUsed> failureDetection = Flow.of(HttpRequest.class).watchTermination(
				(notUsed, termination) -> {
					termination.whenComplete((done, cause) -> {
						if (cause != null) {
							// signal the failure to external monitoring
							// service!
						}
					});
					return NotUsed.getInstance();
				});
		ActorRef protocolHander = system.actorOf(ProtocalHandle.createProps().withRouter(new RoundRobinPool(100)), "protocal");
		Timeout timeout = new Timeout(Duration.create(5, "seconds"));
		Future<Object> future1 = Patterns.ask(protocolHander, "test", timeout);
		String result1;
		try {
			result1 = (String) Await.result(future1, timeout.duration());
		} catch (Exception e1) {
			e1.printStackTrace();
		}

		Flow<HttpRequest, HttpResponse, NotUsed> httpExecutionFlow = handleRequest(failureDetection, protocolHander,
				timeout);

		CompletionStage<ServerBinding> serverBindingFuture = serverSource.to(Sink.foreach(conn -> {
//			System.out.println("Accepted new connection from " + conn.remoteAddress());
			conn.handleWith(httpExecutionFlow, materializer);
		})).run(materializer);
	}

	private static Flow<HttpRequest, HttpResponse, NotUsed> handleRequest(
			Flow<HttpRequest, HttpRequest, NotUsed> failureDetection, ActorRef protocolHander, Timeout timeout) {
		Flow<HttpRequest, HttpResponse, NotUsed> httpExecutionFlow = Flow.of(HttpRequest.class).via(failureDetection)
				.map(request -> {
					HttpResponse response = null;
					System.out.println("server count: "+count++);
					Future<Object> future = Patterns.ask(protocolHander, request, timeout);
					String result;
					try {
						result = (String) Await.result(future, timeout.duration());
						response = HttpResponse.create().withEntity(result);
					} catch (TimeoutException e) {
						e.printStackTrace();
						response = HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, "Timeout");
					} catch (Exception e) {
						e.printStackTrace();
						response = HttpResponse.create().withEntity(ContentTypes.TEXT_PLAIN_UTF8, "Exception ");
					}
					return response;
				});
		return httpExecutionFlow;
	}

**Comment by kejiawu** [comment] 2017-06-16 05:55
Use wireshark, I found when post content lenght is 465,  content data bind in HTTP for sending to server side， when post content length is 594, content data didn't bind with HTTP, use TCP to send to server side. Is there has problem??

**Comment by kejiawu** [comment] 2017-06-16 09:49
@ktoso Please answer me for this issue.

**Comment by ktoso** [comment] 2017-06-16 10:37
This is not a private hot-line, you will have to wait for us to get to the issue.
If you want to be served as-soon-as-possible first-thing-we-do then consider a [Lightbend subscription](https://www.lightbend.com/platform/subscription).

Thanks for your understanding, we're all human with limited time and resources.

**Comment by neurolabs** [comment] 2017-06-16 13:51
I see something similar. Very rarely, I see `HttpEntity.Default`s instead of `HttpEntity.Strict`s. I am using akka-http 10.0.6. I don't see the warning about early responses @kejiawu mentioned. Here's the code:

`
    post {
      mapRequest(logRequest) {
        mapResponse(logErrors) {
          mapRejections(logRejections) {
            optionalHeaderValueByType[headers.`User-Agent`]() { uaOpt =>
              optionalHeaderValueByType[headers.Host]() { hostOpt =>
                formFieldMap { (fields: Map[String, String]) =>
                  val scheduledReporting = someFutureReturningFunction()
                  scheduledReporting.failed.foreach(logger.error("error in reporting", _))
                  respondWithHeader(headers.`Access-Control-Allow-Origin`.*) {
                    complete(NoContent)
                  }
                }
              }
            }
          }
        }
      }
    }
`

So as you can see, there is potential for an early response here because the response is sent after scheduling the consuming future. But I thought that `formFieldMap` would already consume the body and eagerly convert it to the `Map[String, String]`, at least that is what I see in line 74 of FormFieldDirectives.scala file.

Am I obviously doing something wrong? Or can I help debugging this issue (which occurs around every two days on our application)?

**Comment by ktoso** [comment] 2017-06-16 13:54
> Very rarely, I see HttpEntity.Defaults instead of HttpEntity.Stricts. I am using akka-http 10.0.6.

Because akka-http is streaming by default, and the Default entity is streaming. If you want a strict one, make it so by doing `toStrict {}`. Please read http://doc.akka.io/docs/akka-http/current/scala/http/implications-of-streaming-http-entity.html

**Comment by neurolabs** [comment] 2017-06-16 13:59
Hi @ktoso, I am aware of the streaming nature of akka-http. This is why I pointed to line 75 of FormFieldDirectives.scala, where the conversion to a Strict Entity is happening IMHO. This code is transiently called by the `formFieldMap` directive, AFAICS, and as described in http://doc.akka.io/docs/akka-http/current/scala/http/implications-of-streaming-http-entity.html#consuming-the-http-request-entity-server-

I am not directly working with an HttpEntity, so I don't see where I should convert it to Strict. If I am wrong, could you point that out for me, please?

Thanks

**Comment by neurolabs** [comment] 2017-06-16 14:16
@ktoso please also note the scaladoc on `StrictForm`, which explicitly mentions not to use it on unbounded sources, since the source gets 'strictified'.

**Comment by neurolabs** [comment] 2017-06-19 07:43
I have verified that for my case 404s and HttpEntity.Default are just a correlation, not a cause. Most HttpEntity.Default cases are handled just fine. So for me it's ok to keep this issue closed.

Thanks for the support.

**Comment by kejiawu** [comment] 2017-06-20 03:26
Cloud you send you Demo to me，@neurolabs  I want to know what's deference with me.
My email : wukejia.com.cn@163.com

**Comment by jrudolph** [comment] 2017-06-26 09:53
@kejiawu a few remarks on your code:

 * If you use `toStrict` you can get at the data more easily using `HttpEntity.Strict::getData`. No need to collect it through a stream. That's what `toStrict` already does for you.
 * Try to avoid to use `Await.result` or other blocking constructs. You will run into all kinds of deadlocks because blocking may prevent crucial infrastructure from running your program. That might very well be the source of the timeouts you are seeing. Instead of `Await.result` use `mapAsync` in streams to unpack futures, or use one of the methods of `Future` to further process the results without blocking.

If you need further help to rewrite your code in a non-blocking way, please use the akka-user mailing list at https://groups.google.com/forum/#!forum/akka-user or the gitter channel to ask for help.

**Comment by jrudolph** [comment] 2017-06-26 09:54
@neurolabs glad you figured it out. I guess your `logRequest` did log the original entity type and not the strictified version that was later produced by `formFieldMap`.
