### ISSUE TITLE
Configuration idleTimeout through config does not work

### ISSUE THREAD

**Issue by Elufimov** [akka/akka-http#742] opened 2017-01-10 09:24 UTC
Hi! 
I had this error 
```
TCP idle-timeout encountered on connection to [my_site:443], no bytes passed in the last 1 minute
akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [my_site:443], no bytes passed in the last 1 minute
```
and in first I tried to use this settings
```
akka.http.client.idle-timeout
akka.http.http-connection-pool.idle-timeout
akka.http.http-connection-pool.client.idle-timeout
```
however it did not work for me. I ended up with this workaround 
 ```
      val orig = ConnectionPoolSettings(system.settings.config).copy(idleTimeout = 10 minutes)
      val clientSettings = orig.connectionSettings.withIdleTimeout(10 minutes)
      val settings = orig.copy(connectionSettings = clientSettings)

      Http().singleRequest(
        HttpRequest(
          entity = HttpEntity(
            `application/json`,
            write(entity)
          ),
          uri = url,
          method = httpMethod,
          headers = cookies
        ),
        settings = settings
      )
```

**Comment by ktoso** [comment] 2017-01-10 09:26
Hmm, weird... I'll have a look - thanks for reporting!

**Comment by ktoso** [comment] 2017-01-10 09:27
Seems that's on 10.0.1? (Please include version number when reporting things like this - this time I could guess it on message ;-))

**Comment by ktoso** [comment] 2017-01-10 10:04
I can not reproduce, this works, as expected:

```scala
  val orig = ConnectionPoolSettings(system.settings.config).copy(idleTimeout = 37 seconds)
  val clientSettings = orig.connectionSettings.withIdleTimeout(12 seconds)
  val settings = orig.copy(connectionSettings = clientSettings)

  val x = Http().singleRequest(
    HttpRequest(
      entity = HttpEntity(
        ContentTypes.`application/json`,
        Source.maybe
      ),
      uri = "http://127.0.0.1:8080/post"
    ),
    settings = settings)

  println("mAwait.ready(x, 100.minutes)aterializer = ${Await.ready(x, 100.minutes) aterializer}")
```

> [WARN] [01/10/2017 11:01:45.321] [ServerTest-akka.actor.default-dispatcher-9] [akka://ServerTest/system/IO-TCP/selectors/$a/1] unhandled message from Actor[akka://ServerTest/user/StreamSupervisor-1/$$a#-1866345296]: ResumeReading
> [DEBUG] [01/10/2017 11:01:58.478] [ServerTest-akka.actor.default-dispatcher-3] [akka://ServerTest/user/StreamSupervisor-1/flow-1-0-unknown-operation] Aborting tcp connection to 127.0.0.1:8080 because of upstream failure: TCP idle-timeout encountered on connection to [127.0.0.1:8080], no bytes passed in the last 12 seconds
> akka.stream.impl.io.TcpIdleTimeout$$anonfun$1.applyOrElse(TcpStages.scala:374)
> akka.stream.impl.io.TcpIdleTimeout$$anonfun$1.applyOrElse(TcpStages.scala:372)

Please post a fully working reproducer and say which version you're on. This clearly works on current master, and was fixed in v10.0.1

**Comment by ktoso** [comment] 2017-01-10 10:05
Eh you mean the config settings don't work. Wasn't quite clear... Trying again.

**Comment by Elufimov** [comment] 2017-01-10 10:08
Yes I use
```
    "com.typesafe.akka" %% "akka-actor" % "2.4.16",
    "com.typesafe.akka" %% "akka-http-core" % "10.0.1",
    "com.typesafe.akka" %% "akka-http" % "10.0.1",
```
And yes config settings do not work for me. Sorry for insufficient description.

**Comment by ktoso** [comment] 2017-01-10 10:12
Looks like a bug, thanks a ton for reporting. Will add tests and fix.

**Comment by ktoso** [comment] 2017-01-10 11:17
The correct setting is: `    akka.http.host-connection-pool.client.idle-timeout = 12s`
Which makes sense in accordance to how the structures ale laid out... I'll make sure we document the right values.

**Comment by ktoso** [comment] 2017-01-10 11:20
Your setting was wrong: `akka.http.http-connection-pool.client.idle-timeout`. It's not http-connection-pool. It is `host-connection-pool`.

If you were a customer this plugin would have detected this mistake and logged warnings: http://doc.akka.io/docs/akka/akka-commercial-addons-1.0/common/config-checker.html

We document the correct settings in the docs. http://doc.akka.io/docs/akka-http/current/scala/http/common/timeouts.html

Closing as invalid.

**Closed by ktoso** 2017-01-10 11:20 UTC
Labels: 3 - in progress, bug, t:client

**Comment by Elufimov** [comment] 2017-01-10 12:15
I have found this settings here http://doc.akka.io/docs/akka/2.4.4/scala/http/common/timeouts.html Now I know that akka-http has its own documentation site. I did not even think that config was change after separation of http project. I will check this setting later.

**Comment by ktoso** [comment] 2017-01-10 12:17
If you're using 10.0.x please read the docs for 10.0.x ;-)

Esp. since routing was experimental in 2.4.


If reading 2.4 docs please read the latest, 2.4.16 in any case btw. There
is a warning on the bottom of the site urging to do so too.


Cheers


On 10 January 2017 at 13:15:41, Michael Elufimov (notifications@github.com)
wrote:

I have found this settings here
http://doc.akka.io/docs/akka/2.4.4/scala/http/common/timeouts.html Now I
know that akka-http has its own documentation site. I did not even think
that config was change after separation of http project. I will check this
setting later.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/akka/akka-http/issues/742#issuecomment-271560869>, or mute
the thread

**Comment by pianista215** [comment] 2017-11-12 18:29
Hi, 

Is possible that the timeout configuration is not being used in Akka 10.0.10?

Doing:

`val timeoutSettings =
        ConnectionPoolSettings(context.system.settings.config).withIdleTimeout(10 minutes)

      http.singleRequest(
        HttpRequest(
          method = HttpMethods.POST,
          uri = endpoint,
          entity = rqEntity
        ), settings = timeoutSettings)`

I'm getting:
akka.stream.scaladsl.TcpIdleTimeoutException: TCP idle-timeout encountered on connection to [localhost:9080], no bytes passed in the last 1 minute.
