### ISSUE TITLE
 'Remote-Address' header does not get detected when processing httprequest

### ISSUE THREAD

**Issue by dsashikanth** [akka/akka-http#1171] opened 2017-06-01 18:12 UTC
I am trying to block httprequests based on the 'Remote-Addres' header. Here is a KISS version on my application

```import akka.actor.ActorSystem
import akka.http.scaladsl.Http
import akka.http.scaladsl.model._
import akka.http.scaladsl.server._
import akka.http.scaladsl.server.Directives._
import akka.http.scaladsl.server.directives.{HeaderDirectives, RouteDirectives}
import akka.stream.ActorMaterializer
import com.typesafe.config.ConfigFactory

trait RemoteAddressBlacklistProvider {
  def containsAddress(remoteAddress: String): Boolean
}

case class BlacklistedRejection(remoteAddress: String) extends Rejection

object TrafficSourceDirectiveex01 extends App with RestInterface02  {


  implicit def myRejectionHandler = RejectionHandler.newBuilder().handle {

    case BlacklistedRejection(message) => {
      complete(StatusCodes.BadRequest,"This ip address is not allowed here")
    }

  }.result()

  val config = ConfigFactory.load()
  val host = config.getString("http.host")
  val port = config.getInt("http.port")

  val miniConfig = ConfigFactory.parseString(
    s"""
       |akka.http.server.remote-address-header = on
      """.stripMargin)

  println(miniConfig)


  implicit val system = ActorSystem("My-ActorSystem",miniConfig)
  implicit val executionContext = system.dispatcher
  implicit val materializer = ActorMaterializer()
  //implicit val timeout = Timeout(10 seconds)

  val api = routes

  Http().bindAndHandle(api, host, port) map {
    binding => println(s"The binding local address is ${binding.localAddress}")
  }

}

case class Results(message : String, num : Int)
case class Stringer02(str1 : String, str2 : String, str3 : String)

trait RestInterface02 extends RemoteAddressDirectiveChecker {
  val routes = blacklistaddressroute ~ myroute
}

trait TrafficSourceDirectives  {
  import akka.http.scaladsl.server.directives.BasicDirectives._
  import akka.http.scaladsl.server.directives.MiscDirectives._
  import akka.http.scaladsl.server.directives.RouteDirectives._


  def blacklistRemoteAddress(blackListAddressProvider: RemoteAddressBlacklistProvider): Directive0 =
    extractClientIP.flatMap{
      case ip if blackListAddressProvider.containsAddress(ip.toOption.map(_.getHostAddress).getOrElse("")) => {
        println("no not that ip address")
        reject(BlacklistedRejection(ip.toOption.map(_.getHostAddress).getOrElse("")))
      }
      case _ => pass
    }
     cancelRejection(MissingHeaderRejection("Remote-Address"))
}

object TrafficSourceDirectives extends TrafficSourceDirectives

trait RemoteAddressDirectiveChecker {

  val timeoutResponse = HttpResponse(
    StatusCodes.EnhanceYourCalm,
    entity = "Unable to serve response within time limit, please enhance your calm.")

  object RemoteAddress extends RemoteAddressBlacklistProvider {

    def containsAddress(remoteAddress: String): Boolean = {
      if (remoteAddress == "192.168.1.13")
        true
      else
        false
    }
  }

  def blacklistaddressroute(): Route = {

    val blacklistedclientdirective = TrafficSourceDirectives.blacklistRemoteAddress(RemoteAddress)


        path("rest" / "v1" / "checkblacklistedipaddress") {
          blacklistedclientdirective {
            {
              get {
                complete("not blacklisted")
              }
            }
          }
        }
  }
  val myroute = HeaderDirectives.headerValueByName("Remote-Address") {
    remaddr => RouteDirectives.complete(s"Remote-Address = $remaddr ")
  }
}
```

I am sending a request like this

> GET /rest/v1/checkblacklistedipaddress HTTP/1.1 Host: 127.0.0.1:8080 Remote-Address: 192.168.1.13 Cache-Control: no-cache Postman-Token: f7d42832-7c25-8df3-f688-4b278fe9e19b

my issue is that the 'Remote-Address' header is not being detected. Well it works for X-Forwarded-For header but that is not I want. Let me know where I am going wrong. Thanks

**Comment by jrudolph** [comment] 2017-06-06 09:07
Hi @dsashikanth, thanks for the report.

> my issue is that the 'Remote-Address' header is not being detected

What do you mean with "it is not being detected"? Is it missing from the request? Or is one of our or your directives not being able to extract it? Or something else?

**Comment by Bigdatascholar** [comment] 2017-06-07 16:21
Hi @jrudolph , thanks for getting back. In this example, When I send the a request with 'X-Forwarded-For' header = 192.168.1.13, I get response "Remote-Address =  127.0.0.1:49819" .Whereas if I send the request with 'Remote-Address' header = 192.168.1.13, I get the response 'not blacklisted'. But the expected behavior is that I should have it blocked for that 'Remote-Address' header value just like the previous one. May I know what is the issue here? Thanks

**Comment by jrudolph** [comment] 2017-06-14 10:38
Maybe it's because the `extractClientIP` directives looks at a bunch of headers and returns the value of the first one it finds. See here https://github.com/akka/akka-http/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/directives/MiscDirectives.scala#L106

So could it be that your route is looking at the wrong header?

**Comment by jrudolph** [comment] 2017-07-26 14:42
Closing for now because it's unclear what is wrong. Feel free to comment if you have more information that would help us to understand this issue.

**Closed by jrudolph** 2017-07-26 14:42 UTC
Labels: 0 - new
