### ISSUE TITLE
Http Client - Slot execution failed

### ISSUE THREAD

**Issue by ANorwell** [akka/akka-http#1809] opened 2018-01-23 16:39 UTC
Using 10.1.0-M1, I get the error: "Slot execution failed. That's probably a bug." At scale, this seems to happen relatively frequently. It causes the future to never be fulfilled.

The full debug log:

```
{"@timestamp":"2018-01-23T16:31:31.873+00:00","@version":1,"message":"[0 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-108","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-60","akkaTimestamp":"16:31:31.873UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:31.874+00:00","@version":1,"message":"[0 (Idle)] Slot became idle... Trying to pull","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-108","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-60","akkaTimestamp":"16:31:31.873UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.863+00:00","@version":1,"message":"[0 (Idle)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-62","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-70","akkaTimestamp":"16:31:32.863UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.863+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-62","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-70","akkaTimestamp":"16:31:32.863UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.863+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-62","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-70","akkaTimestamp":"16:31:32.863UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.866+00:00","@version":1,"message":"[0 (WaitingForResponse)] Received response","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.866+00:00","@version":1,"message":"[0 (WaitingForResponseDispatch)] State change [WaitingForResponse] -> [WaitingForResponseDispatch]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.867+00:00","@version":1,"message":"[0 (WaitingForResponseEntitySubscription)] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.867+00:00","@version":1,"message":"[0 (WaitingForEndOfResponseEntity)] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.867+00:00","@version":1,"message":"[0 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:32.867+00:00","@version":1,"message":"[0 (Idle)] Slot became idle... Trying to pull","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-62","akkaTimestamp":"16:31:32.866UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.623+00:00","@version":1,"message":"[0 (Idle)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-78","akkaTimestamp":"16:31:35.623UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.623+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-78","akkaTimestamp":"16:31:35.623UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.623+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-107","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-78","akkaTimestamp":"16:31:35.623UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (WaitingForResponse)] Received response","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-78","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.624UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (WaitingForResponseDispatch)] State change [WaitingForResponse] -> [WaitingForResponseDispatch]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.625UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (WaitingForResponseEntitySubscription)] State change [WaitingForResponseDispatch] -> [WaitingForResponseEntitySubscription]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.625UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (WaitingForEndOfResponseEntity)] State change [WaitingForResponseEntitySubscription] -> [WaitingForEndOfResponseEntity]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.625UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (Idle)] State change [WaitingForEndOfResponseEntity] -> [Idle]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.625UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:35.625+00:00","@version":1,"message":"[0 (Idle)] Slot became idle... Trying to pull","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-107","akkaTimestamp":"16:31:35.625UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[0 (Idle)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-114","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.408UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-114","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.408UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[0 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-114","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.408UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[1 (Idle)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego","akkaTimestamp":"16:31:36.408UTC"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[1 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.408UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.408+00:00","@version":1,"message":"[1 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.408UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.410+00:00","@version":1,"message":"[2 (Idle)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.410+00:00","@version":1,"message":"[2 (WaitingForResponse)] State change [WaitingForEndOfRequestEntity] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.410+00:00","@version":1,"message":"[2 (WaitingForResponse)] State change [Idle] -> [WaitingForResponse]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-103","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.410+00:00","@version":1,"message":"[3 (Unconnected)] Dispatching request","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-114","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-56","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.413+00:00","@version":1,"message":"[3 (Unconnected)] Slot execution failed. That's probably a bug. Please file a bug at https://github.com/akka/akka-http/issues. Slot is restarted.","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"ERROR","level_value":40000,"stack_trace":"java.lang.IllegalStateException: Cannot open connection when slot still has an open connection\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.openConnection(NewHostConnectionPool.scala:285)\n\tat akka.http.impl.engine.client.pool.SlotState$Unconnected$.onNewRequest(SlotState.scala:156)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:147)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot$$anonfun$dispatchRequest$1.apply(NewHostConnectionPool.scala:147)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.runOneTransition$1(NewHostConnectionPool.scala:175)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.loop$1(NewHostConnectionPool.scala:239)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.updateState(NewHostConnectionPool.scala:248)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1$Slot.dispatchRequest(NewHostConnectionPool.scala:147)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.dispatchRequest(NewHostConnectionPool.scala:114)\n\tat akka.http.impl.engine.client.pool.NewHostConnectionPool$HostConnectionPoolStage$$anon$1.onPush(NewHostConnectionPool.scala:81)\n\tat akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499)\n\tat akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462)\n\tat akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent$class.execute(ActorGraphInterpreter.scala:42)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75)\n\tat akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740)\n\tat akka.actor.Actor$class.aroundReceive(Actor.scala:513)\n\tat akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650)\n\tat akka.actor.ActorCell.receiveMessage(ActorCell.scala:519)\n\tat akka.actor.ActorCell.invoke(ActorCell.scala:488)\n\tat akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)\n\tat akka.dispatch.Mailbox.run(Mailbox.scala:224)\n\tat akka.dispatch.Mailbox.exec(Mailbox.scala:234)\n\tat akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)\n\tat akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)\n\tat akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)\n\tat akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)\n","sourceThread":"lego-akka.actor.default-dispatcher-56","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.413+00:00","@version":1,"message":"[3 (Unconnected)] Establishing connection","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-56","akkaTimestamp":"16:31:36.410UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
{"@timestamp":"2018-01-23T16:31:36.413+00:00","@version":1,"message":"[3 (PreConnecting)] State change [Unconnected] -> [PreConnecting]","logger_name":"akka.http.impl.engine.client.PoolGateway","thread_name":"lego-akka.actor.default-dispatcher-80","level":"DEBUG","level_value":10000,"sourceThread":"lego-akka.actor.default-dispatcher-56","akkaTimestamp":"16:31:36.412UTC","akkaSource":"lego/Pool(shared->http://localhost:9995)","sourceActorSystem":"lego"}
```

**Comment by jrudolph** [comment] 2018-01-23 16:43
That's probably a duplicate of https://github.com/akka/akka-http/issues/1724. Can you try version "10.1.0-RC1+64-3a7a288f" from this maven repository `https://dl.bintray.com/akka/maven/`?

**Comment by ANorwell** [comment] 2018-01-24 15:49
@jrudolph it appears to be fixed on that version.

**Comment by jrudolph** [comment] 2018-01-24 16:16
Great, thanks for checking. Closing this one...

**Closed by jrudolph** 2018-01-24 16:16 UTC
Labels: 0 - new
