### ISSUE TITLE
Concurrency bug (?) in server-side 100-Continue handling "Cannot pull port (requestParsingIn)" and "Cannot push port (requestPrepOut) twice"

### ISSUE THREAD

**Issue by jypma** [akka/akka-http#448] opened 2016-10-31 11:04 UTC
Akka seems to upset its internal state when handling a streaming request that is failed asynchronously, but immediately, when materializing the request consuming stream, for a request that has an `Expect: 100-continue` header. A reproducer is [here](https://github.com/Tradeshift/ts-reaktive/pull/41/files#diff-018b0aa7e6fd1cbcb6f61b497fd736ecR110).

The reproducer prints this in the console after correctly sending both a `100 Continue` and then `500 Internal Server Error`:

```
java.lang.IllegalArgumentException: requirement failed: Cannot pull port (requestParsingIn) twice
	at scala.Predef$.require(Predef.scala:224)
	at akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:355)
	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$15.onPush(HttpServerBluePrint.scala:432)
```

Curiously, I was trying to reproduce the failure that my real server has in a similar situation. However, the real server prints a different message after handling such a request:

```
[info] java.lang.IllegalArgumentException: requirement failed: Cannot push port (requestPrepOut) twice
[info] 	at scala.Predef$.require(Predef.scala:224)
[info] 	at akka.stream.stage.GraphStageLogic.push(GraphStage.scala:459)
[info] 	at akka.http.impl.engine.server.HttpServerBluePrint$ControllerStage$$anon$12$$anon$13.onPush(HttpServerBluePrint.scala:394)
```

Either way, it seems `HttpServerBluePrint` gets its state messed up when a request manages to fail right at the same time as it's already sending out the `100 Continue` response.

Related: https://github.com/akka/akka/issues/20642 https://github.com/akka/akka/issues/21008 https://github.com/akka/akka/issues/20789

**Comment by jrudolph** [comment] 2017-02-21 08:26
Closing as duplicate of #516 (which had the most information). Fixed in #869 to be released in 10.0.4.

**Closed by jrudolph** 2017-02-21 08:26 UTC
Labels: 1 - triaged, bug, t:core, t:server
