### ISSUE TITLE
Proxy Authentication Required Issue since 10.2.0

### ISSUE THREAD

**Issue by MJ97** [akka/akka-http#3450] opened 2020-08-26 08:33 UTC
Hello,

following code does work without issues in 10.1.11 but since 10.2.0 it's getting me following error:
Failure(e) because of The HTTP(S) proxy rejected to open a connection to google.com:443 with status code: 407 Proxy Authentication Required

Before the proxy authentication did went through without problems, but now it seems to stuck there somewhere. Any help to be able to stay up to date with the versions is highly appreciated. :)

  val url = "https://google.com"

  implicit val system = akka.actor.ActorSystem("ClusterSystem")
  implicit val executionContext: ExecutionContextExecutor = system.dispatchers.lookup("my-dispatcher")

  val username : String = "your username"
  val password : String = "your password"
  val host : String = "165.231.108.185"
  val port : Int = 12345

  val req = HttpRequest(method = HttpMethods.GET, uri = url)

  val auth = headers.BasicHttpCredentials(username, password)
  val httpsProxyTransport = ClientTransport.httpsProxy(
    InetSocketAddress.createUnresolved(host, port),
    auth
  )
  val settings = ConnectionPoolSettings(system)
    .withConnectionSettings(
      ClientConnectionSettings(system)
        .withTransport(httpsProxyTransport)
    )
  Http(system)
    .singleRequest(req, settings = settings)
    .flatMap(_.toStrict(2.seconds))
    .flatMap { resp =>
      Unmarshal(resp.entity).to[String].map((resp.status, _))
    }
    .onComplete { result =>
      result match {
        case Success((statusCode, bodyString)) => {
          println("INFO | Successfully proxied.")
        }
        case Failure(e) => {
          println(s"ERROR | case Failure(e) because of ${e.getMessage}")
        }
      }
    }

**Comment by raboof** [comment] 2020-08-27 08:26
I wonder if this could be a duplicate of #3435 - could you try to see if the problem is still there when you use a snapshot release from https://bintray.com/akka/snapshots/akka-http ?

**Comment by jrudolph** [comment] 2020-09-01 09:20
Let's treat it as a duplicate of #3435. Let us know if the snapshot doesn't fix the issue.

**Closed by jrudolph** 2020-09-01 09:20 UTC
Labels: 0 - new
