### ISSUE TITLE
FAILED: nightly build against Akka master

### ISSUE THREAD

**Issue by johanandren** [akka/akka-http#1498] opened 2017-10-30 08:21 UTC
Possibly because of upgrade to sbt 1.0:

```
Cloning into '/home/jenkins/.sbt/1.0/staging/8bd016127453b4b8fefa/akka'...
/home/jenkins/.sbt/1.0/staging/8bd016127453b4b8fefa/akka/project/plugins.sbt:1: error: value typesafeResolver is not a member of object sbt.Classpaths
resolvers += Classpaths.typesafeResolver
```

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master/328//consoleFull
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-release-2.4-on-2.12/309//consoleFull
https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-release-2.4/327//consoleFull

**Comment by 2m** [comment] 2017-10-30 08:29
The akka-http sbt 1.0 build got merged earlier than akka's. This morning we merged akka sbt 1.0 build as well. So there should be no failures like this anymore. Lets wait and see...

**Comment by raboof** [comment] 2017-11-06 10:31
Oddly they're still there.. leftover from a previous build?

https://jenkins.akka.io:8498/job/akka-http-nightly-against-akka-master-on-2.12/321/console

**Comment by jrudolph** [comment] 2017-11-06 11:32
The problem is that the staging repository needs to be purged in the beginning and it still purges the 0.13 one:

```
rm -rf /home/jenkins/.sbt/0.13/staging/8bd016127453b4b8fefa

...

/home/jenkins/.sbt/1.0/staging/8bd016127453b4b8fefa/akka/project/plugins.sbt
```

**Comment by jrudolph** [comment] 2017-11-06 11:36
I fixed the config and restarted all the builds

**Comment by jrudolph** [comment] 2017-11-06 12:32
It's now fixed for `master`. 

The reason was because of including the akka project by git source uri. sbt then creates this directory in `.sbt/1.0/staging/<hash_of_url>`. But it doesn't update the sources when you refer to a branch and the branch has been updated. So we have a step in the build that deletes the directory before running the build and since the version number is in the path and the version number is hard-coded in the build step it purged the wrong directory. So, it still used an older, pre-sbt-1.0 version of akka master.

We cannot fix it right now for Akka's `release-2.4` branch because that's still on sbt 0.13 and I guess will stay like this. Right now that's no problem because we still build against Akka 2.4. When we finally change that, we need to make sure to keep running tests against 2.4 binaries.

**Comment by jrudolph** [comment] 2017-11-06 12:33
(I disabled the builds against 2.4)

**Closed by jrudolph** 2017-11-06 12:32 UTC
Labels: failed

**Comment by raboof** [comment] 2017-11-06 12:37
I guess building against 2.4 binaries can be done later by just building with `-Dakka.build.version=2.4.19` :+1:
