### ISSUE TITLE
akka http - Socks proxy support

### ISSUE THREAD

**Issue by tahelc** [akka/akka-http#1969] opened 2018-04-01 15:42 UTC
Hi,
I tried to work with socks proxy just like with http proxy and i couldn't find any easy way. 
Are you planing to provide a socks proxy support?

**Comment by ktoso** [comment] 2018-04-02 00:55
Please first search tickets before opening new ones; The SOCKS ticket is here: https://github.com/akka/akka-http/issues/846

We are currently not planning on working on SOCKS support, if you would like to contribute it that would be a welcome PR though.
Closing as duplicate.

**Comment by ktoso** [comment] 2018-04-02 00:56
Duplicate of https://github.com/akka/akka-http/issues/846

**Closed by ktoso** 2018-04-02 00:56 UTC
