### ISSUE TITLE
 HTTP idle-timeout with web sockets causes stream to be completed

### ISSUE THREAD

**Issue by chbatey** [akka/akka-http#1496] opened 2017-10-27 13:06 UTC
If a web socket is idle for the timeout then the user stream is completed rather than failed.

This means that the user flow can't distinguish a client gracefully disconnecting vs the idle timeout closing the connection internally.

Do we think this behaviour should remain?

**Comment by jrudolph** [comment] 2017-10-30 09:51
The current behavior elsewhere is to fail the streams in those cases.

We've had similar kinds of bugs in other areas. The usual cause of the problem is that the idle-timeout triggers both an error and cancellation. If cancellation reaches the controller stage before the error it might interpret it as regular completion (often because that's what the default `onDownstreamFinish` handler does by calling `completeStage`). The solution in those other cases was to introduce a `delayCancellation` stage that prevents cancellation from overtaking the error.

Just found #1026 again which seems to be the same case as this one. Closing this one...

Duplicate of #1026.

**Closed by jrudolph** 2017-10-30 09:51 UTC
Labels: 1 - triaged, bug, t:core, t:server, t:websocket
